namespace exxen2._0.capaVisual.Entrenador
{
    partial class MisSociosFormulario
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.ErrorProvider indicadorErrores;
        private System.Windows.Forms.Label lblBuscar;
        private System.Windows.Forms.TextBox buscador;
        private System.Windows.Forms.Label lblFiltroRutina;
        private System.Windows.Forms.ComboBox filtroRutina;
        private System.Windows.Forms.Button actualizar;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.SplitContainer splitContenido;
        private System.Windows.Forms.Label lblListadoTitulo;
        private System.Windows.Forms.DataGridView tabla;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIdSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIdMembresia;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDni;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPlan;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRutina;
        private System.Windows.Forms.DataGridViewTextBoxColumn colVencimiento;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEstadoRutina;
        private System.Windows.Forms.Label lblDetalleTitulo;
        private System.Windows.Forms.Label lblRutinaTitulo;
        private System.Windows.Forms.Label lblSocio;
        private System.Windows.Forms.TextBox txtSocio;
        private System.Windows.Forms.Label lblDni;
        private System.Windows.Forms.TextBox txtDni;
        private System.Windows.Forms.Label lblPlan;
        private System.Windows.Forms.TextBox txtPlan;
        private System.Windows.Forms.Label lblEntrenador;
        private System.Windows.Forms.TextBox txtEntrenador;
        private System.Windows.Forms.Label lblVencimiento;
        private System.Windows.Forms.TextBox txtVencimiento;
        private System.Windows.Forms.Label lblRutina;
        private System.Windows.Forms.TextBox txtRutina;
        private System.Windows.Forms.DataGridView tablaRutina;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDia;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEjercicio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSeries;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRepeticiones;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPeso;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDescanso;
        private System.Windows.Forms.Label lblAccionInfo;
        private System.Windows.Forms.ComboBox rutinaDisponible;
        private System.Windows.Forms.Button asignarRutina;
        private System.Windows.Forms.Button verRutina;
        private System.Windows.Forms.Button crearPersonalizada;
        private System.Windows.Forms.Button exportarPdf;

        protected override void Dispose(bool liberarRecursos)
        {
            if (liberarRecursos && components != null) components.Dispose();
            base.Dispose(liberarRecursos);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            indicadorErrores = new System.Windows.Forms.ErrorProvider(components);
            lblBuscar = new System.Windows.Forms.Label();
            lblBuscar.Name = "lblBuscar";
            buscador = new System.Windows.Forms.TextBox();
            buscador.Name = "buscador";
            buscador.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            lblFiltroRutina = new System.Windows.Forms.Label();
            lblFiltroRutina.Name = "lblFiltroRutina";
            filtroRutina = new System.Windows.Forms.ComboBox();
            filtroRutina.Name = "filtroRutina";
            filtroRutina.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            actualizar = new System.Windows.Forms.Button();
            actualizar.ForeColor = System.Drawing.Color.FromArgb(48, 68, 95);
            actualizar.Name = "actualizar";
            lblEstado = new System.Windows.Forms.Label();
            splitContenido = new System.Windows.Forms.SplitContainer();
            splitContenido.BorderStyle = System.Windows.Forms.BorderStyle.None;
            splitContenido.Location = new System.Drawing.Point(16, 16);
            splitContenido.Size = new System.Drawing.Size(1068, 620);
            lblListadoTitulo = new System.Windows.Forms.Label();
            lblListadoTitulo.Name = "lblListadoTitulo";
            lblListadoTitulo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblListadoTitulo.Size = new System.Drawing.Size(398, 30);
            lblListadoTitulo.Location = new System.Drawing.Point(3, 0);
            tabla = new System.Windows.Forms.DataGridView();
            tabla.Name = "tabla";
            tabla.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            tabla.Size = new System.Drawing.Size(398, 456);
            tabla.Location = new System.Drawing.Point(3, 148);
            colIdSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colIdMembresia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colDni = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colPlan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colRutina = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colVencimiento = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colEstadoRutina = new System.Windows.Forms.DataGridViewTextBoxColumn();
            lblDetalleTitulo = new System.Windows.Forms.Label();
            lblDetalleTitulo.Name = "lblDetalleTitulo";
            lblDetalleTitulo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblDetalleTitulo.Size = new System.Drawing.Size(616, 28);
            lblDetalleTitulo.Location = new System.Drawing.Point(10, 8);
            lblRutinaTitulo = new System.Windows.Forms.Label();
            lblRutinaTitulo.Name = "lblRutinaTitulo";
            lblRutinaTitulo.Text = "Rutina semanal";
            lblRutinaTitulo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblRutinaTitulo.Size = new System.Drawing.Size(616, 28);
            lblRutinaTitulo.Location = new System.Drawing.Point(10, 148);
            lblRutinaTitulo.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblRutinaTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold);
            lblSocio = new System.Windows.Forms.Label();
            lblSocio.Name = "lblSocio";
            lblSocio.Size = new System.Drawing.Size(100, 24);
            lblSocio.Location = new System.Drawing.Point(10, 42);
            txtSocio = new System.Windows.Forms.TextBox();
            txtSocio.Size = new System.Drawing.Size(180, 24);
            txtSocio.Location = new System.Drawing.Point(116, 42);
            lblDni = new System.Windows.Forms.Label();
            lblDni.Name = "lblDni";
            lblDni.Size = new System.Drawing.Size(100, 24);
            lblDni.Location = new System.Drawing.Point(306, 42);
            txtDni = new System.Windows.Forms.TextBox();
            txtDni.Size = new System.Drawing.Size(214, 24);
            txtDni.Location = new System.Drawing.Point(412, 42);
            lblPlan = new System.Windows.Forms.Label();
            lblPlan.Name = "lblPlan";
            lblPlan.Size = new System.Drawing.Size(100, 24);
            lblPlan.Location = new System.Drawing.Point(10, 74);
            txtPlan = new System.Windows.Forms.TextBox();
            txtPlan.Size = new System.Drawing.Size(180, 24);
            txtPlan.Location = new System.Drawing.Point(116, 74);
            lblEntrenador = new System.Windows.Forms.Label();
            lblEntrenador.Name = "lblEntrenador";
            lblEntrenador.Size = new System.Drawing.Size(100, 24);
            lblEntrenador.Location = new System.Drawing.Point(306, 74);
            txtEntrenador = new System.Windows.Forms.TextBox();
            txtEntrenador.Size = new System.Drawing.Size(214, 24);
            txtEntrenador.Location = new System.Drawing.Point(412, 74);
            lblVencimiento = new System.Windows.Forms.Label();
            lblVencimiento.Name = "lblVencimiento";
            lblVencimiento.Size = new System.Drawing.Size(100, 24);
            lblVencimiento.Location = new System.Drawing.Point(10, 106);
            txtVencimiento = new System.Windows.Forms.TextBox();
            txtVencimiento.Size = new System.Drawing.Size(180, 24);
            txtVencimiento.Location = new System.Drawing.Point(116, 106);
            lblRutina = new System.Windows.Forms.Label();
            lblRutina.Name = "lblRutina";
            lblRutina.Size = new System.Drawing.Size(100, 24);
            lblRutina.Location = new System.Drawing.Point(306, 106);
            txtRutina = new System.Windows.Forms.TextBox();
            txtRutina.Size = new System.Drawing.Size(214, 24);
            txtRutina.Location = new System.Drawing.Point(412, 106);
            tablaRutina = new System.Windows.Forms.DataGridView();
            tablaRutina.Name = "tablaRutina";
            colDia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colEjercicio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colSeries = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colRepeticiones = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colPeso = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colDescanso = new System.Windows.Forms.DataGridViewTextBoxColumn();
            lblAccionInfo = new System.Windows.Forms.Label();
            lblAccionInfo.Name = "lblAccionInfo";
            rutinaDisponible = new System.Windows.Forms.ComboBox();
            rutinaDisponible.Name = "rutinaDisponible";
            asignarRutina = new System.Windows.Forms.Button();
            asignarRutina.Name = "asignarRutina";
            verRutina = new System.Windows.Forms.Button();
            verRutina.ForeColor = System.Drawing.Color.FromArgb(48, 68, 95);
            verRutina.Name = "verRutina";
            crearPersonalizada = new System.Windows.Forms.Button();
            crearPersonalizada.ForeColor = System.Drawing.Color.FromArgb(255, 255, 255);
            crearPersonalizada.Name = "crearPersonalizada";
            exportarPdf = new System.Windows.Forms.Button();
            exportarPdf.ForeColor = System.Drawing.Color.FromArgb(48, 68, 95);
            ((System.ComponentModel.ISupportInitialize)(tabla)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(tablaRutina)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContenido)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(indicadorErrores)).BeginInit();
            splitContenido.Panel1.SuspendLayout();
            splitContenido.Panel2.SuspendLayout();
            splitContenido.SuspendLayout();
            SuspendLayout();


            lblBuscar.AutoSize = false;
            lblBuscar.Location = new System.Drawing.Point(3, 36);
            lblBuscar.Size = new System.Drawing.Size(60, 26);
            lblBuscar.Text = "Buscar:";
            lblBuscar.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            buscador.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            buscador.Location = new System.Drawing.Point(67, 36);
            buscador.Size = new System.Drawing.Size(331, 24);
            buscador.TabIndex = 1;
            buscador.TextChanged += new System.EventHandler(buscador_TextChanged);
            lblFiltroRutina.AutoSize = false;
            lblFiltroRutina.Location = new System.Drawing.Point(3, 68);
            lblFiltroRutina.Size = new System.Drawing.Size(60, 26);
            lblFiltroRutina.Text = "Rutina:";
            lblFiltroRutina.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            filtroRutina.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            filtroRutina.Items.AddRange(new object[] { "Todas", "Con rutina", "Sin rutina" });
            filtroRutina.Location = new System.Drawing.Point(67, 68);
            filtroRutina.Size = new System.Drawing.Size(331, 25);
            filtroRutina.TabIndex = 2;
            filtroRutina.SelectedIndex = 0;
            filtroRutina.SelectedIndexChanged += new System.EventHandler(filtroRutina_SelectedIndexChanged);
            actualizar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            actualizar.BackColor = System.Drawing.Color.FromArgb(231, 237, 247);
            actualizar.FlatAppearance.BorderSize = 0;
            actualizar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            actualizar.Location = new System.Drawing.Point(3, 104);
            actualizar.Size = new System.Drawing.Size(150, 32);
            actualizar.TabIndex = 3;
            actualizar.Text = "Actualizar listado";
            actualizar.UseVisualStyleBackColor = false;
            actualizar.Click += new System.EventHandler(actualizar_Click);

            lblEstado.BackColor = System.Drawing.Color.Transparent;
            lblEstado.Dock = System.Windows.Forms.DockStyle.Bottom;
            lblEstado.Height = 28;
            lblEstado.Padding = new System.Windows.Forms.Padding(16, 0, 8, 0);
            lblEstado.Text = "";
            lblEstado.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            splitContenido.Dock = System.Windows.Forms.DockStyle.Fill;
            splitContenido.FixedPanel = System.Windows.Forms.FixedPanel.None;
            splitContenido.IsSplitterFixed = true;
            splitContenido.MinimumSize = new System.Drawing.Size(862, 420);
            splitContenido.Panel1MinSize = 300;
            splitContenido.Panel2MinSize = 550;
            splitContenido.SplitterWidth = 6;
            splitContenido.TabStop = false;
            splitContenido.Panel1.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            splitContenido.Panel1.Padding = new System.Windows.Forms.Padding(16);
            splitContenido.Panel2.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            splitContenido.Panel2.Padding = new System.Windows.Forms.Padding(0, 16, 16, 16);

            lblListadoTitulo.Dock = System.Windows.Forms.DockStyle.None;
            lblListadoTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold);
            lblListadoTitulo.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblListadoTitulo.Height = 30;
            lblListadoTitulo.Text = "Socios con membresía activa";
            lblListadoTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            tabla.Dock = System.Windows.Forms.DockStyle.None;
            tabla.AllowUserToAddRows = false;
            tabla.AllowUserToDeleteRows = false;
            tabla.AllowUserToResizeRows = false;
            tabla.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            tabla.BackgroundColor = System.Drawing.Color.White;
            tabla.BorderStyle = System.Windows.Forms.BorderStyle.None;
            tabla.ColumnHeadersHeight = 34;
            tabla.MultiSelect = false;
            tabla.ReadOnly = true;
            tabla.RowHeadersVisible = false;
            tabla.RowTemplate.Height = 28;
            tabla.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            tabla.TabIndex = 4;
            tabla.SelectionChanged += new System.EventHandler(tabla_SelectionChanged);
            colIdSocio.Name = "colIdSocio"; colIdSocio.Visible = false;
            colIdMembresia.Name = "colIdMembresia"; colIdMembresia.Visible = false;
            colSocio.HeaderText = "Socio"; colSocio.Name = "colSocio"; colSocio.FillWeight = 28; colSocio.MinimumWidth = 60;
            colDni.HeaderText = "DNI"; colDni.Name = "colDni"; colDni.FillWeight = 16; colDni.MinimumWidth = 50;
            colPlan.HeaderText = "Plan"; colPlan.Name = "colPlan"; colPlan.FillWeight = 20; colPlan.MinimumWidth = 50;
            colRutina.HeaderText = "Rutina"; colRutina.Name = "colRutina"; colRutina.FillWeight = 22; colRutina.MinimumWidth = 62;
            colVencimiento.HeaderText = "Vence"; colVencimiento.Name = "colVencimiento"; colVencimiento.FillWeight = 16; colVencimiento.MinimumWidth = 62;
            colEstadoRutina.HeaderText = "Estado"; colEstadoRutina.Name = "colEstadoRutina"; colEstadoRutina.FillWeight = 16; colEstadoRutina.MinimumWidth = 66;
            tabla.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colIdSocio, colIdMembresia, colSocio, colDni, colPlan, colRutina, colVencimiento, colEstadoRutina });

            lblDetalleTitulo.Dock = System.Windows.Forms.DockStyle.None;
            lblDetalleTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold);
            lblDetalleTitulo.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblDetalleTitulo.Height = 28;
            lblDetalleTitulo.Text = "Socio seleccionado";
            lblSocio.Dock = System.Windows.Forms.DockStyle.None;
            lblSocio.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblSocio.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblSocio.Text = "Socio:";
            lblSocio.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtSocio.Name = "txtSocio";
            txtSocio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            txtSocio.BackColor = System.Drawing.SystemColors.Window;
            txtSocio.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtSocio.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtSocio.ReadOnly = true;
            txtSocio.TabStop = false;
            txtSocio.Text = "Selecciona un socio";
            lblDni.Dock = System.Windows.Forms.DockStyle.None;
            lblDni.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblDni.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblDni.Text = "DNI:";
            lblDni.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtDni.Name = "txtDni";
            txtDni.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtDni.BackColor = System.Drawing.SystemColors.Window;
            txtDni.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtDni.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtDni.ReadOnly = true;
            txtDni.TabStop = false;
            txtDni.Text = "-";
            lblPlan.Dock = System.Windows.Forms.DockStyle.None;
            lblPlan.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblPlan.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblPlan.Text = "Plan:";
            lblPlan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtPlan.Name = "txtPlan";
            txtPlan.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            txtPlan.BackColor = System.Drawing.SystemColors.Window;
            txtPlan.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtPlan.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtPlan.ReadOnly = true;
            txtPlan.TabStop = false;
            txtPlan.Text = "-";
            lblEntrenador.Dock = System.Windows.Forms.DockStyle.None;
            lblEntrenador.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblEntrenador.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblEntrenador.Text = "Entrenador:";
            lblEntrenador.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtEntrenador.Name = "txtEntrenador";
            txtEntrenador.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtEntrenador.BackColor = System.Drawing.SystemColors.Window;
            txtEntrenador.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtEntrenador.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtEntrenador.ReadOnly = true;
            txtEntrenador.TabStop = false;
            txtEntrenador.Text = "-";
            lblVencimiento.Dock = System.Windows.Forms.DockStyle.None;
            lblVencimiento.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblVencimiento.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblVencimiento.Text = "Vencimiento:";
            lblVencimiento.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtVencimiento.Name = "txtVencimiento";
            txtVencimiento.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            txtVencimiento.BackColor = System.Drawing.SystemColors.Window;
            txtVencimiento.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtVencimiento.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtVencimiento.ReadOnly = true;
            txtVencimiento.TabStop = false;
            txtVencimiento.Text = "-";
            lblRutina.Dock = System.Windows.Forms.DockStyle.None;
            lblRutina.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblRutina.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblRutina.Text = "Rutina:";
            lblRutina.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtRutina.Name = "txtRutina";
            txtRutina.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtRutina.BackColor = System.Drawing.SystemColors.Window;
            txtRutina.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            txtRutina.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtRutina.ReadOnly = true;
            txtRutina.TabStop = false;
            txtRutina.Text = "-";

            tablaRutina.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            tablaRutina.Location = new System.Drawing.Point(10, 184);
            tablaRutina.Size = new System.Drawing.Size(616, 256);
            tablaRutina.AllowUserToAddRows = false;
            tablaRutina.AllowUserToDeleteRows = false;
            tablaRutina.AllowUserToResizeRows = false;
            tablaRutina.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            tablaRutina.BackgroundColor = System.Drawing.Color.White;
            tablaRutina.BorderStyle = System.Windows.Forms.BorderStyle.None;
            tablaRutina.ColumnHeadersHeight = 34;
            tablaRutina.Font = new System.Drawing.Font("Segoe UI", 9F);
            tablaRutina.MultiSelect = false;
            tablaRutina.ReadOnly = true;
            tablaRutina.RowHeadersVisible = false;
            tablaRutina.RowTemplate.Height = 28;
            tablaRutina.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            tablaRutina.TabIndex = 5;
            colDia.HeaderText = "Dia"; colDia.Name = "colDia"; colDia.FillWeight = 16; colDia.MinimumWidth = 54;
            colEjercicio.HeaderText = "Ejercicio"; colEjercicio.Name = "colEjercicio"; colEjercicio.FillWeight = 30; colEjercicio.MinimumWidth = 100;
            colSeries.HeaderText = "Series"; colSeries.Name = "colSeries"; colSeries.FillWeight = 12; colSeries.MinimumWidth = 48;
            colRepeticiones.HeaderText = "Repeticiones"; colRepeticiones.Name = "colRepeticiones"; colRepeticiones.FillWeight = 17; colRepeticiones.MinimumWidth = 94;
            colPeso.HeaderText = "Peso"; colPeso.Name = "colPeso"; colPeso.FillWeight = 12; colPeso.MinimumWidth = 48;
            colDescanso.HeaderText = "Descanso"; colDescanso.Name = "colDescanso"; colDescanso.FillWeight = 15; colDescanso.MinimumWidth = 78;
            tablaRutina.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colDia, colEjercicio, colSeries, colRepeticiones, colPeso, colDescanso });
            lblAccionInfo.AutoSize = false;
            lblAccionInfo.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblAccionInfo.Margin = new System.Windows.Forms.Padding(0, 4, 8, 0);
            lblAccionInfo.Location = new System.Drawing.Point(10, 450);
            lblAccionInfo.Size = new System.Drawing.Size(616, 44);
            lblAccionInfo.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            lblAccionInfo.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblAccionInfo.Text = "Selecciona un socio para ver su rutina y acciones.";
            lblAccionInfo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            rutinaDisponible.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            rutinaDisponible.Margin = new System.Windows.Forms.Padding(0, 4, 8, 0);
            rutinaDisponible.Location = new System.Drawing.Point(10, 510);
            rutinaDisponible.Size = new System.Drawing.Size(464, 25);
            rutinaDisponible.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            rutinaDisponible.TabIndex = 6;
            rutinaDisponible.Visible = false;
            asignarRutina.AutoSize = false;
            asignarRutina.BackColor = System.Drawing.Color.FromArgb(72, 66, 217);
            asignarRutina.FlatAppearance.BorderSize = 0;
            asignarRutina.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            asignarRutina.ForeColor = System.Drawing.Color.White;
            asignarRutina.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            asignarRutina.Size = new System.Drawing.Size(136, 32);
            asignarRutina.Location = new System.Drawing.Point(490, 506);
            asignarRutina.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            asignarRutina.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            asignarRutina.TabIndex = 7;
            asignarRutina.Text = "Asignar rutina";
            asignarRutina.UseVisualStyleBackColor = false;
            asignarRutina.Visible = false;
            asignarRutina.Click += new System.EventHandler(asignarRutina_Click);
            verRutina.AutoSize = false;
            verRutina.BackColor = System.Drawing.Color.FromArgb(231, 237, 247);
            verRutina.FlatAppearance.BorderSize = 0;
            verRutina.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            verRutina.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            verRutina.Size = new System.Drawing.Size(192, 32);
            verRutina.Location = new System.Drawing.Point(282, 550);
            verRutina.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            verRutina.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            verRutina.TabIndex = 8;
            verRutina.Text = "Ver / editar";
            verRutina.UseVisualStyleBackColor = false;
            verRutina.Visible = false;
            verRutina.Click += new System.EventHandler(verRutina_Click);
            crearPersonalizada.AutoSize = false;
            crearPersonalizada.BackColor = System.Drawing.Color.FromArgb(9, 149, 111);
            crearPersonalizada.FlatAppearance.BorderSize = 0;
            crearPersonalizada.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            crearPersonalizada.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            crearPersonalizada.Size = new System.Drawing.Size(192, 32);
            crearPersonalizada.Location = new System.Drawing.Point(282, 550);
            crearPersonalizada.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            crearPersonalizada.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            crearPersonalizada.TabIndex = 9;
            crearPersonalizada.Text = "Crear personalizada";
            crearPersonalizada.UseVisualStyleBackColor = false;
            crearPersonalizada.Visible = false;
            crearPersonalizada.Click += new System.EventHandler(crearPersonalizada_Click);
            exportarPdf.Name = "exportarPdf";
            exportarPdf.Text = "Exportar PDF";
            exportarPdf.Size = new System.Drawing.Size(136, 32);
            exportarPdf.Location = new System.Drawing.Point(490, 550);
            exportarPdf.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            exportarPdf.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            exportarPdf.BackColor = System.Drawing.Color.FromArgb(231, 237, 247);
            exportarPdf.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            exportarPdf.FlatAppearance.BorderSize = 0;
            exportarPdf.UseVisualStyleBackColor = false;
            exportarPdf.Enabled = false;
            exportarPdf.TabIndex = 10;
            exportarPdf.Click += new System.EventHandler(exportarPdf_Click);

            splitContenido.Panel1.Controls.Add(lblListadoTitulo);
            splitContenido.Panel1.Controls.Add(lblBuscar);
            splitContenido.Panel1.Controls.Add(buscador);
            splitContenido.Panel1.Controls.Add(lblFiltroRutina);
            splitContenido.Panel1.Controls.Add(filtroRutina);
            splitContenido.Panel1.Controls.Add(actualizar);
            splitContenido.Panel1.Controls.Add(tabla);
            splitContenido.Panel2.Controls.Add(lblDetalleTitulo);
            splitContenido.Panel2.Controls.Add(lblSocio);
            splitContenido.Panel2.Controls.Add(txtSocio);
            splitContenido.Panel2.Controls.Add(lblDni);
            splitContenido.Panel2.Controls.Add(txtDni);
            splitContenido.Panel2.Controls.Add(lblPlan);
            splitContenido.Panel2.Controls.Add(txtPlan);
            splitContenido.Panel2.Controls.Add(lblEntrenador);
            splitContenido.Panel2.Controls.Add(txtEntrenador);
            splitContenido.Panel2.Controls.Add(lblVencimiento);
            splitContenido.Panel2.Controls.Add(txtVencimiento);
            splitContenido.Panel2.Controls.Add(lblRutina);
            splitContenido.Panel2.Controls.Add(txtRutina);
            splitContenido.Panel2.Controls.Add(lblRutinaTitulo);
            splitContenido.Panel2.Controls.Add(tablaRutina);
            splitContenido.Panel2.Controls.Add(lblAccionInfo);
            splitContenido.Panel2.Controls.Add(rutinaDisponible);
            splitContenido.Panel2.Controls.Add(asignarRutina);
            splitContenido.Panel2.Controls.Add(verRutina);
            splitContenido.Panel2.Controls.Add(crearPersonalizada);
            splitContenido.Panel2.Controls.Add(exportarPdf);
            Controls.Add(splitContenido);
            Controls.Add(lblEstado);
            indicadorErrores.BlinkStyle = System.Windows.Forms.ErrorBlinkStyle.NeverBlink;
            indicadorErrores.ContainerControl = this;
            AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            Padding = new System.Windows.Forms.Padding(16);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            ClientSize = new System.Drawing.Size(1100, 680);
            Font = new System.Drawing.Font("Segoe UI", 9.5F);
            MinimumSize = new System.Drawing.Size(916, 560);
            Name = "MisSociosFormulario";
            StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            Text = "SysGym | Mis socios y rutinas";
            Load += new System.EventHandler(MisSociosFormulario_Load);
            splitContenido.SplitterDistance = 404;
            splitContenido.Panel2.ResumeLayout(false);
            splitContenido.Panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(splitContenido)).EndInit();
            splitContenido.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(tablaRutina)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(tabla)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(indicadorErrores)).EndInit();
            ResumeLayout(false);
        }

    }
}
