namespace exxen2._0.capaVisual.Entrenador
{
    partial class MisSociosFormulario
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.Panel panelEncabezado;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblDescripcion;
        private System.Windows.Forms.Button btnVolver;
        private System.Windows.Forms.Panel barraAcciones;
        private System.Windows.Forms.Label lblBuscar;
        private System.Windows.Forms.TextBox buscador;
        private System.Windows.Forms.Label lblFiltroRutina;
        private System.Windows.Forms.ComboBox filtroRutina;
        private System.Windows.Forms.Button actualizar;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.SplitContainer splitContenido;
        private System.Windows.Forms.Panel panelListado;
        private System.Windows.Forms.Label lblListadoTitulo;
        private System.Windows.Forms.DataGridView tabla;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIdSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIdMembresia;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDni;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPlan;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRutina;
        private System.Windows.Forms.DataGridViewTextBoxColumn colVencimiento;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEstadoRutina;
        private System.Windows.Forms.Panel panelDetalle;
        private System.Windows.Forms.GroupBox grupoSocio;
        private System.Windows.Forms.Label lblDetalleTitulo;
        private System.Windows.Forms.TableLayoutPanel tablaSocio;
        private System.Windows.Forms.Label lblSocio;
        private System.Windows.Forms.Label lblSocioValor;
        private System.Windows.Forms.Label lblDni;
        private System.Windows.Forms.Label lblDniValor;
        private System.Windows.Forms.Label lblPlan;
        private System.Windows.Forms.Label lblPlanValor;
        private System.Windows.Forms.Label lblEntrenador;
        private System.Windows.Forms.Label lblEntrenadorValor;
        private System.Windows.Forms.Label lblVencimiento;
        private System.Windows.Forms.Label lblVencimientoValor;
        private System.Windows.Forms.Label lblRutina;
        private System.Windows.Forms.Label lblRutinaValor;
        private System.Windows.Forms.GroupBox grupoRutina;
        private System.Windows.Forms.DataGridView tablaRutina;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDia;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEjercicio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSeries;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRepeticiones;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPeso;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDescanso;
        private System.Windows.Forms.FlowLayoutPanel accionesRutina;
        private System.Windows.Forms.Label lblAccionInfo;
        private System.Windows.Forms.ComboBox rutinaDisponible;
        private System.Windows.Forms.Button asignarRutina;
        private System.Windows.Forms.Button verRutina;
        private System.Windows.Forms.Button crearPersonalizada;

        protected override void Dispose(bool liberarRecursos)
        {
            if (liberarRecursos && components != null) components.Dispose();
            base.Dispose(liberarRecursos);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            panelEncabezado = new System.Windows.Forms.Panel();
            lblTitulo = new System.Windows.Forms.Label();
            lblDescripcion = new System.Windows.Forms.Label();
            btnVolver = new System.Windows.Forms.Button();
            barraAcciones = new System.Windows.Forms.Panel();
            lblBuscar = new System.Windows.Forms.Label();
            buscador = new System.Windows.Forms.TextBox();
            lblFiltroRutina = new System.Windows.Forms.Label();
            filtroRutina = new System.Windows.Forms.ComboBox();
            actualizar = new System.Windows.Forms.Button();
            lblEstado = new System.Windows.Forms.Label();
            splitContenido = new System.Windows.Forms.SplitContainer();
            panelListado = new System.Windows.Forms.Panel();
            lblListadoTitulo = new System.Windows.Forms.Label();
            tabla = new System.Windows.Forms.DataGridView();
            colIdSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colIdMembresia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colDni = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colPlan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colRutina = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colVencimiento = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colEstadoRutina = new System.Windows.Forms.DataGridViewTextBoxColumn();
            panelDetalle = new System.Windows.Forms.Panel();
            grupoSocio = new System.Windows.Forms.GroupBox();
            lblDetalleTitulo = new System.Windows.Forms.Label();
            tablaSocio = new System.Windows.Forms.TableLayoutPanel();
            lblSocio = new System.Windows.Forms.Label();
            lblSocioValor = new System.Windows.Forms.Label();
            lblDni = new System.Windows.Forms.Label();
            lblDniValor = new System.Windows.Forms.Label();
            lblPlan = new System.Windows.Forms.Label();
            lblPlanValor = new System.Windows.Forms.Label();
            lblEntrenador = new System.Windows.Forms.Label();
            lblEntrenadorValor = new System.Windows.Forms.Label();
            lblVencimiento = new System.Windows.Forms.Label();
            lblVencimientoValor = new System.Windows.Forms.Label();
            lblRutina = new System.Windows.Forms.Label();
            lblRutinaValor = new System.Windows.Forms.Label();
            grupoRutina = new System.Windows.Forms.GroupBox();
            tablaRutina = new System.Windows.Forms.DataGridView();
            colDia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colEjercicio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colSeries = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colRepeticiones = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colPeso = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colDescanso = new System.Windows.Forms.DataGridViewTextBoxColumn();
            accionesRutina = new System.Windows.Forms.FlowLayoutPanel();
            lblAccionInfo = new System.Windows.Forms.Label();
            rutinaDisponible = new System.Windows.Forms.ComboBox();
            asignarRutina = new System.Windows.Forms.Button();
            verRutina = new System.Windows.Forms.Button();
            crearPersonalizada = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(tabla)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(tablaRutina)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContenido)).BeginInit();
            splitContenido.Panel1.SuspendLayout();
            splitContenido.Panel2.SuspendLayout();
            splitContenido.SuspendLayout();
            panelEncabezado.SuspendLayout();
            barraAcciones.SuspendLayout();
            panelListado.SuspendLayout();
            grupoSocio.SuspendLayout();
            tablaSocio.SuspendLayout();
            grupoRutina.SuspendLayout();
            accionesRutina.SuspendLayout();
            SuspendLayout();

            panelEncabezado.BackColor = System.Drawing.Color.FromArgb(79, 70, 229);
            panelEncabezado.Dock = System.Windows.Forms.DockStyle.Top;
            panelEncabezado.Height = 70;
            panelEncabezado.Controls.Add(lblTitulo);
            panelEncabezado.Controls.Add(lblDescripcion);
            panelEncabezado.Controls.Add(btnVolver);
            lblTitulo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblTitulo.AutoSize = false;
            lblTitulo.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            lblTitulo.ForeColor = System.Drawing.Color.White;
            lblTitulo.Location = new System.Drawing.Point(20, 8);
            lblTitulo.Size = new System.Drawing.Size(850, 30);
            lblTitulo.Text = "Mis socios y rutinas";
            lblDescripcion.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblDescripcion.AutoSize = false;
            lblDescripcion.ForeColor = System.Drawing.Color.FromArgb(226, 232, 240);
            lblDescripcion.Location = new System.Drawing.Point(22, 39);
            lblDescripcion.Size = new System.Drawing.Size(850, 22);
            lblDescripcion.Text = "Selecciona un socio para revisar su contexto y su rutina semanal";
            btnVolver.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            btnVolver.BackColor = System.Drawing.Color.White;
            btnVolver.FlatAppearance.BorderSize = 0;
            btnVolver.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnVolver.Location = new System.Drawing.Point(980, 17);
            btnVolver.Size = new System.Drawing.Size(100, 36);
            btnVolver.TabIndex = 0;
            btnVolver.Text = "Volver";
            btnVolver.UseVisualStyleBackColor = false;
            btnVolver.Click += new System.EventHandler(btnVolver_Click);
            panelEncabezado.Height = 56;
            lblTitulo.Size = new System.Drawing.Size(850, 40);
            lblTitulo.Text = "Socios y rutinas | Consulta de rutinas de socios";
            lblTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            lblDescripcion.Visible = false;
            panelEncabezado.Visible = false;
            btnVolver.Location = new System.Drawing.Point(980, 10);

            barraAcciones.BackColor = System.Drawing.Color.White;
            barraAcciones.Dock = System.Windows.Forms.DockStyle.Top;
            barraAcciones.Height = 54;
            barraAcciones.Controls.Add(lblBuscar);
            barraAcciones.Controls.Add(buscador);
            barraAcciones.Controls.Add(lblFiltroRutina);
            barraAcciones.Controls.Add(filtroRutina);
            barraAcciones.Controls.Add(actualizar);
            lblBuscar.AutoSize = false;
            lblBuscar.Location = new System.Drawing.Point(16, 10);
            lblBuscar.Size = new System.Drawing.Size(52, 28);
            lblBuscar.Text = "Buscar:";
            lblBuscar.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            buscador.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            buscador.Location = new System.Drawing.Point(72, 13);
            buscador.Size = new System.Drawing.Size(210, 24);
            buscador.TabIndex = 1;
            buscador.TextChanged += new System.EventHandler(buscador_TextChanged);
            lblFiltroRutina.AutoSize = false;
            lblFiltroRutina.Location = new System.Drawing.Point(310, 10);
            lblFiltroRutina.Size = new System.Drawing.Size(56, 28);
            lblFiltroRutina.Text = "Rutina:";
            lblFiltroRutina.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            filtroRutina.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            filtroRutina.Items.AddRange(new object[] { "Todas", "Con rutina", "Sin rutina" });
            filtroRutina.Location = new System.Drawing.Point(370, 13);
            filtroRutina.Size = new System.Drawing.Size(160, 25);
            filtroRutina.TabIndex = 2;
            filtroRutina.SelectedIndex = 0;
            filtroRutina.SelectedIndexChanged += new System.EventHandler(filtroRutina_SelectedIndexChanged);
            actualizar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            actualizar.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            actualizar.FlatAppearance.BorderSize = 0;
            actualizar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            actualizar.Location = new System.Drawing.Point(914, 9);
            actualizar.Size = new System.Drawing.Size(166, 34);
            actualizar.TabIndex = 3;
            actualizar.Text = "Actualizar listado";
            actualizar.UseVisualStyleBackColor = false;
            actualizar.Click += new System.EventHandler(actualizar_Click);

            lblEstado.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            lblEstado.Dock = System.Windows.Forms.DockStyle.Bottom;
            lblEstado.Height = 28;
            lblEstado.Padding = new System.Windows.Forms.Padding(16, 0, 8, 0);
            lblEstado.Text = "Listo";
            lblEstado.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            splitContenido.Dock = System.Windows.Forms.DockStyle.Fill;
            splitContenido.FixedPanel = System.Windows.Forms.FixedPanel.None;
            splitContenido.IsSplitterFixed = false;
            splitContenido.MinimumSize = new System.Drawing.Size(900, 420);
            splitContenido.Panel1MinSize = 300;
            splitContenido.Panel2MinSize = 500;
            splitContenido.SplitterWidth = 6;
            splitContenido.Panel1.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            splitContenido.Panel1.Padding = new System.Windows.Forms.Padding(16);
            splitContenido.Panel2.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            splitContenido.Panel2.Padding = new System.Windows.Forms.Padding(0, 16, 16, 16);

            panelListado.Dock = System.Windows.Forms.DockStyle.Fill;
            panelListado.Controls.Add(tabla);
            panelListado.Controls.Add(lblListadoTitulo);
            lblListadoTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            lblListadoTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            lblListadoTitulo.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblListadoTitulo.Height = 34;
            lblListadoTitulo.Text = "Socios con membresia activa";
            lblListadoTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            tabla.Dock = System.Windows.Forms.DockStyle.Fill;
            tabla.AllowUserToAddRows = false;
            tabla.AllowUserToDeleteRows = false;
            tabla.AllowUserToResizeRows = false;
            tabla.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            tabla.BackgroundColor = System.Drawing.Color.White;
            tabla.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            tabla.ColumnHeadersHeight = 34;
            tabla.MultiSelect = false;
            tabla.ReadOnly = true;
            tabla.RowHeadersVisible = false;
            tabla.RowTemplate.Height = 30;
            tabla.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            tabla.TabIndex = 4;
            tabla.SelectionChanged += new System.EventHandler(tabla_SelectionChanged);
            colIdSocio.Name = "colIdSocio"; colIdSocio.Visible = false;
            colIdMembresia.Name = "colIdMembresia"; colIdMembresia.Visible = false;
            colSocio.HeaderText = "Socio"; colSocio.Name = "colSocio"; colSocio.FillWeight = 28; colSocio.MinimumWidth = 90;
            colDni.HeaderText = "DNI"; colDni.Name = "colDni"; colDni.FillWeight = 16; colDni.MinimumWidth = 60;
            colPlan.HeaderText = "Plan"; colPlan.Name = "colPlan"; colPlan.FillWeight = 20; colPlan.MinimumWidth = 72;
            colRutina.HeaderText = "Rutina"; colRutina.Name = "colRutina"; colRutina.FillWeight = 22; colRutina.MinimumWidth = 72;
            colVencimiento.HeaderText = "Vence"; colVencimiento.Name = "colVencimiento"; colVencimiento.FillWeight = 16; colVencimiento.MinimumWidth = 64;
            colEstadoRutina.HeaderText = "Estado"; colEstadoRutina.Name = "colEstadoRutina"; colEstadoRutina.FillWeight = 16; colEstadoRutina.MinimumWidth = 72;
            tabla.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colIdSocio, colIdMembresia, colSocio, colDni, colPlan, colRutina, colVencimiento, colEstadoRutina });

            panelDetalle.Dock = System.Windows.Forms.DockStyle.Fill;
            panelDetalle.Controls.Add(grupoRutina);
            panelDetalle.Controls.Add(grupoSocio);
            grupoSocio.Dock = System.Windows.Forms.DockStyle.Top;
            grupoSocio.Height = 172;
            grupoSocio.BackColor = System.Drawing.Color.White;
            grupoSocio.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            grupoSocio.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            grupoSocio.Padding = new System.Windows.Forms.Padding(16);
            grupoSocio.Text = "Socio seleccionado";
            grupoSocio.Controls.Add(tablaSocio);
            grupoSocio.Controls.Add(lblDetalleTitulo);
            lblDetalleTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            lblDetalleTitulo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            lblDetalleTitulo.ForeColor = System.Drawing.Color.FromArgb(79, 70, 229);
            lblDetalleTitulo.Height = 30;
            lblDetalleTitulo.Text = "Selecciona un socio";
            tablaSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            tablaSocio.ColumnCount = 4;
            tablaSocio.RowCount = 3;
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 82F));
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 39F));
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 92F));
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 61F));
            tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            tablaSocio.Padding = new System.Windows.Forms.Padding(0, 6, 0, 0);
            tablaSocio.Controls.Add(lblSocio, 0, 0); tablaSocio.Controls.Add(lblSocioValor, 1, 0); tablaSocio.Controls.Add(lblDni, 2, 0); tablaSocio.Controls.Add(lblDniValor, 3, 0);
            tablaSocio.Controls.Add(lblPlan, 0, 1); tablaSocio.Controls.Add(lblPlanValor, 1, 1); tablaSocio.Controls.Add(lblEntrenador, 2, 1); tablaSocio.Controls.Add(lblEntrenadorValor, 3, 1);
            tablaSocio.Controls.Add(lblVencimiento, 0, 2); tablaSocio.Controls.Add(lblVencimientoValor, 1, 2); tablaSocio.Controls.Add(lblRutina, 2, 2); tablaSocio.Controls.Add(lblRutinaValor, 3, 2);
            ConfigurarEtiqueta(lblSocio, "Socio:"); ConfigurarValor(lblSocioValor, "-"); ConfigurarEtiqueta(lblDni, "DNI:"); ConfigurarValor(lblDniValor, "-");
            ConfigurarEtiqueta(lblPlan, "Plan:"); ConfigurarValor(lblPlanValor, "-"); ConfigurarEtiqueta(lblEntrenador, "Entrenador:"); ConfigurarValor(lblEntrenadorValor, "-");
            ConfigurarEtiqueta(lblVencimiento, "Vencimiento:"); ConfigurarValor(lblVencimientoValor, "-"); ConfigurarEtiqueta(lblRutina, "Rutina:"); ConfigurarValor(lblRutinaValor, "-");

            grupoRutina.Dock = System.Windows.Forms.DockStyle.Fill;
            grupoRutina.BackColor = System.Drawing.Color.White;
            grupoRutina.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            grupoRutina.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            grupoRutina.Padding = new System.Windows.Forms.Padding(12);
            grupoRutina.Text = "Rutina semanal";
            grupoRutina.Controls.Add(tablaRutina);
            grupoRutina.Controls.Add(accionesRutina);
            tablaRutina.Dock = System.Windows.Forms.DockStyle.Fill;
            tablaRutina.AllowUserToAddRows = false;
            tablaRutina.AllowUserToDeleteRows = false;
            tablaRutina.AllowUserToResizeRows = false;
            tablaRutina.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            tablaRutina.BackgroundColor = System.Drawing.Color.White;
            tablaRutina.BorderStyle = System.Windows.Forms.BorderStyle.None;
            tablaRutina.ColumnHeadersHeight = 32;
            tablaRutina.MultiSelect = false;
            tablaRutina.ReadOnly = true;
            tablaRutina.RowHeadersVisible = false;
            tablaRutina.RowTemplate.Height = 28;
            tablaRutina.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            tablaRutina.TabIndex = 5;
            colDia.HeaderText = "Dia"; colDia.Name = "colDia"; colDia.FillWeight = 16; colDia.MinimumWidth = 54;
            colEjercicio.HeaderText = "Ejercicio"; colEjercicio.Name = "colEjercicio"; colEjercicio.FillWeight = 30; colEjercicio.MinimumWidth = 100;
            colSeries.HeaderText = "Series"; colSeries.Name = "colSeries"; colSeries.FillWeight = 12; colSeries.MinimumWidth = 48;
            colRepeticiones.HeaderText = "Repeticiones"; colRepeticiones.Name = "colRepeticiones"; colRepeticiones.FillWeight = 17; colRepeticiones.MinimumWidth = 70;
            colPeso.HeaderText = "Peso"; colPeso.Name = "colPeso"; colPeso.FillWeight = 12; colPeso.MinimumWidth = 48;
            colDescanso.HeaderText = "Descanso"; colDescanso.Name = "colDescanso"; colDescanso.FillWeight = 15; colDescanso.MinimumWidth = 64;
            tablaRutina.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colDia, colEjercicio, colSeries, colRepeticiones, colPeso, colDescanso });
            accionesRutina.Dock = System.Windows.Forms.DockStyle.Bottom;
            accionesRutina.AutoSize = false;
            accionesRutina.Height = 82;
            accionesRutina.Padding = new System.Windows.Forms.Padding(0, 8, 0, 0);
            accionesRutina.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            accionesRutina.WrapContents = true;
            lblAccionInfo.AutoSize = false;
            lblAccionInfo.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblAccionInfo.Margin = new System.Windows.Forms.Padding(0, 4, 8, 0);
            lblAccionInfo.Size = new System.Drawing.Size(220, 34);
            lblAccionInfo.Text = "Selecciona un socio para ver su rutina y acciones.";
            lblAccionInfo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            rutinaDisponible.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            rutinaDisponible.Margin = new System.Windows.Forms.Padding(0, 4, 8, 0);
            rutinaDisponible.Size = new System.Drawing.Size(180, 25);
            rutinaDisponible.TabIndex = 6;
            rutinaDisponible.Visible = false;
            asignarRutina.AutoSize = false;
            asignarRutina.BackColor = System.Drawing.Color.FromArgb(79, 70, 229);
            asignarRutina.FlatAppearance.BorderSize = 0;
            asignarRutina.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            asignarRutina.ForeColor = System.Drawing.Color.White;
            asignarRutina.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            asignarRutina.Size = new System.Drawing.Size(136, 32);
            asignarRutina.TabIndex = 7;
            asignarRutina.Text = "Asignar rutina";
            asignarRutina.UseVisualStyleBackColor = false;
            asignarRutina.Visible = false;
            asignarRutina.Click += new System.EventHandler(asignarRutina_Click);
            verRutina.AutoSize = false;
            verRutina.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            verRutina.FlatAppearance.BorderSize = 0;
            verRutina.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            verRutina.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            verRutina.Size = new System.Drawing.Size(134, 32);
            verRutina.TabIndex = 8;
            verRutina.Text = "Ver / editar";
            verRutina.UseVisualStyleBackColor = false;
            verRutina.Visible = false;
            verRutina.Click += new System.EventHandler(verRutina_Click);
            crearPersonalizada.AutoSize = false;
            crearPersonalizada.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            crearPersonalizada.FlatAppearance.BorderSize = 0;
            crearPersonalizada.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            crearPersonalizada.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            crearPersonalizada.Size = new System.Drawing.Size(160, 32);
            crearPersonalizada.TabIndex = 9;
            crearPersonalizada.Text = "Crear personalizada";
            crearPersonalizada.UseVisualStyleBackColor = false;
            crearPersonalizada.Visible = false;
            crearPersonalizada.Click += new System.EventHandler(crearPersonalizada_Click);
            accionesRutina.Controls.Add(lblAccionInfo);
            accionesRutina.Controls.Add(rutinaDisponible);
            accionesRutina.Controls.Add(asignarRutina);
            accionesRutina.Controls.Add(verRutina);
            accionesRutina.Controls.Add(crearPersonalizada);

            splitContenido.Panel1.Controls.Add(panelListado);
            splitContenido.Panel2.Controls.Add(panelDetalle);
            Controls.Add(splitContenido);
            Controls.Add(lblEstado);
            Controls.Add(barraAcciones);
            Controls.Add(panelEncabezado);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            ClientSize = new System.Drawing.Size(1100, 680);
            Font = new System.Drawing.Font("Segoe UI", 9.5F);
            MinimumSize = new System.Drawing.Size(900, 560);
            Name = "MisSociosFormulario";
            StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            Text = "SysGym | Mis socios y rutinas";
            Load += new System.EventHandler(MisSociosFormulario_Load);
            splitContenido.SplitterDistance = 360;
            accionesRutina.ResumeLayout(false);
            grupoRutina.ResumeLayout(false);
            tablaSocio.ResumeLayout(false);
            grupoSocio.ResumeLayout(false);
            panelListado.ResumeLayout(false);
            splitContenido.Panel2.ResumeLayout(false);
            splitContenido.Panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(splitContenido)).EndInit();
            splitContenido.ResumeLayout(false);
            barraAcciones.ResumeLayout(false);
            barraAcciones.PerformLayout();
            panelEncabezado.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(tablaRutina)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(tabla)).EndInit();
            ResumeLayout(false);
        }

        private static void ConfigurarEtiqueta(System.Windows.Forms.Label etiqueta, string texto)
        {
            etiqueta.Dock = System.Windows.Forms.DockStyle.Fill;
            etiqueta.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            etiqueta.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            etiqueta.Text = texto;
            etiqueta.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
        }

        private static void ConfigurarValor(System.Windows.Forms.Label etiqueta, string texto)
        {
            etiqueta.Dock = System.Windows.Forms.DockStyle.Fill;
            etiqueta.ForeColor = System.Drawing.Color.FromArgb(51, 65, 85);
            etiqueta.Text = texto;
            etiqueta.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
        }
    }
}
