namespace exxen2._0.capaVisual.Entrenador
{
    partial class MisSociosFormulario
    {
        private System.ComponentModel.IContainer components;
        private System.Windows.Forms.Panel barraAcciones;
        private System.Windows.Forms.Label lblBuscar;
        private System.Windows.Forms.TextBox buscador;
        private System.Windows.Forms.Label lblFiltroRutina;
        private System.Windows.Forms.ComboBox filtroRutina;
        private System.Windows.Forms.Button actualizar;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.SplitContainer splitContenido;
        private System.Windows.Forms.Panel panelListado;
        private System.Windows.Forms.Label lblListadoTitulo;
        private System.Windows.Forms.DataGridView tabla;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIdSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIdMembresia;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDni;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPlan;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRutina;
        private System.Windows.Forms.DataGridViewTextBoxColumn colVencimiento;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEstadoRutina;
        private System.Windows.Forms.Panel panelDetalle;
        private System.Windows.Forms.GroupBox grupoSocio;
        private System.Windows.Forms.Label lblDetalleTitulo;
        private System.Windows.Forms.TableLayoutPanel tablaSocio;
        private System.Windows.Forms.Label lblSocio;
        private System.Windows.Forms.TextBox txtSocio;
        private System.Windows.Forms.Label lblDni;
        private System.Windows.Forms.TextBox txtDni;
        private System.Windows.Forms.Label lblPlan;
        private System.Windows.Forms.TextBox txtPlan;
        private System.Windows.Forms.Label lblEntrenador;
        private System.Windows.Forms.TextBox txtEntrenador;
        private System.Windows.Forms.Label lblVencimiento;
        private System.Windows.Forms.TextBox txtVencimiento;
        private System.Windows.Forms.Label lblRutina;
        private System.Windows.Forms.TextBox txtRutina;
        private System.Windows.Forms.GroupBox grupoRutina;
        private System.Windows.Forms.DataGridView tablaRutina;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDia;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEjercicio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colSeries;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRepeticiones;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPeso;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDescanso;
        private System.Windows.Forms.Label lblAccionInfo;
        private System.Windows.Forms.ComboBox rutinaDisponible;
        private System.Windows.Forms.Button asignarRutina;
        private System.Windows.Forms.Button verRutina;
        private System.Windows.Forms.Button crearPersonalizada;
        private System.Windows.Forms.Button exportarPdf;

        protected override void Dispose(bool liberarRecursos)
        {
            if (liberarRecursos && components != null) components.Dispose();
            base.Dispose(liberarRecursos);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            barraAcciones = new System.Windows.Forms.Panel();
            lblBuscar = new System.Windows.Forms.Label();
            buscador = new System.Windows.Forms.TextBox();
            lblFiltroRutina = new System.Windows.Forms.Label();
            filtroRutina = new System.Windows.Forms.ComboBox();
            actualizar = new System.Windows.Forms.Button();
            lblEstado = new System.Windows.Forms.Label();
            splitContenido = new System.Windows.Forms.SplitContainer();
            panelListado = new System.Windows.Forms.Panel();
            lblListadoTitulo = new System.Windows.Forms.Label();
            tabla = new System.Windows.Forms.DataGridView();
            colIdSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colIdMembresia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colDni = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colPlan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colRutina = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colVencimiento = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colEstadoRutina = new System.Windows.Forms.DataGridViewTextBoxColumn();
            panelDetalle = new System.Windows.Forms.Panel();
            grupoSocio = new System.Windows.Forms.GroupBox();
            lblDetalleTitulo = new System.Windows.Forms.Label();
            tablaSocio = new System.Windows.Forms.TableLayoutPanel();
            lblSocio = new System.Windows.Forms.Label();
            txtSocio = new System.Windows.Forms.TextBox();
            lblDni = new System.Windows.Forms.Label();
            txtDni = new System.Windows.Forms.TextBox();
            lblPlan = new System.Windows.Forms.Label();
            txtPlan = new System.Windows.Forms.TextBox();
            lblEntrenador = new System.Windows.Forms.Label();
            txtEntrenador = new System.Windows.Forms.TextBox();
            lblVencimiento = new System.Windows.Forms.Label();
            txtVencimiento = new System.Windows.Forms.TextBox();
            lblRutina = new System.Windows.Forms.Label();
            txtRutina = new System.Windows.Forms.TextBox();
            grupoRutina = new System.Windows.Forms.GroupBox();
            tablaRutina = new System.Windows.Forms.DataGridView();
            colDia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colEjercicio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colSeries = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colRepeticiones = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colPeso = new System.Windows.Forms.DataGridViewTextBoxColumn();
            colDescanso = new System.Windows.Forms.DataGridViewTextBoxColumn();
            lblAccionInfo = new System.Windows.Forms.Label();
            rutinaDisponible = new System.Windows.Forms.ComboBox();
            asignarRutina = new System.Windows.Forms.Button();
            verRutina = new System.Windows.Forms.Button();
            crearPersonalizada = new System.Windows.Forms.Button();
            exportarPdf = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(tabla)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(tablaRutina)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContenido)).BeginInit();
            splitContenido.Panel1.SuspendLayout();
            splitContenido.Panel2.SuspendLayout();
            splitContenido.SuspendLayout();
            barraAcciones.SuspendLayout();
            panelListado.SuspendLayout();
            panelDetalle.SuspendLayout();
            grupoSocio.SuspendLayout();
            tablaSocio.SuspendLayout();
            grupoRutina.SuspendLayout();
            SuspendLayout();


            barraAcciones.BackColor = System.Drawing.Color.White;
            barraAcciones.Dock = System.Windows.Forms.DockStyle.Top;
            barraAcciones.Size = new System.Drawing.Size(1100, 54);
            barraAcciones.Controls.Add(lblBuscar);
            barraAcciones.Controls.Add(buscador);
            barraAcciones.Controls.Add(lblFiltroRutina);
            barraAcciones.Controls.Add(filtroRutina);
            barraAcciones.Controls.Add(actualizar);
            lblBuscar.AutoSize = false;
            lblBuscar.Location = new System.Drawing.Point(16, 10);
            lblBuscar.Size = new System.Drawing.Size(52, 28);
            lblBuscar.Text = "Buscar:";
            lblBuscar.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            buscador.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            buscador.Location = new System.Drawing.Point(72, 13);
            buscador.Size = new System.Drawing.Size(210, 24);
            buscador.TabIndex = 1;
            buscador.TextChanged += new System.EventHandler(buscador_TextChanged);
            lblFiltroRutina.AutoSize = false;
            lblFiltroRutina.Location = new System.Drawing.Point(310, 10);
            lblFiltroRutina.Size = new System.Drawing.Size(56, 28);
            lblFiltroRutina.Text = "Rutina:";
            lblFiltroRutina.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            filtroRutina.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            filtroRutina.Items.AddRange(new object[] { "Todas", "Con rutina", "Sin rutina" });
            filtroRutina.Location = new System.Drawing.Point(370, 13);
            filtroRutina.Size = new System.Drawing.Size(160, 25);
            filtroRutina.TabIndex = 2;
            filtroRutina.SelectedIndex = 0;
            filtroRutina.SelectedIndexChanged += new System.EventHandler(filtroRutina_SelectedIndexChanged);
            actualizar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            actualizar.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            actualizar.FlatAppearance.BorderSize = 0;
            actualizar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            actualizar.Location = new System.Drawing.Point(914, 9);
            actualizar.Size = new System.Drawing.Size(166, 34);
            actualizar.TabIndex = 3;
            actualizar.Text = "Actualizar listado";
            actualizar.UseVisualStyleBackColor = false;
            actualizar.Click += new System.EventHandler(actualizar_Click);

            lblEstado.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            lblEstado.Dock = System.Windows.Forms.DockStyle.Bottom;
            lblEstado.Height = 28;
            lblEstado.Padding = new System.Windows.Forms.Padding(16, 0, 8, 0);
            lblEstado.Text = "";
            lblEstado.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;

            splitContenido.Dock = System.Windows.Forms.DockStyle.Fill;
            splitContenido.FixedPanel = System.Windows.Forms.FixedPanel.None;
            splitContenido.IsSplitterFixed = false;
            splitContenido.MinimumSize = new System.Drawing.Size(900, 420);
            splitContenido.Panel1MinSize = 300;
            splitContenido.Panel2MinSize = 500;
            splitContenido.SplitterWidth = 6;
            splitContenido.Panel1.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            splitContenido.Panel1.Padding = new System.Windows.Forms.Padding(16);
            splitContenido.Panel2.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            splitContenido.Panel2.Padding = new System.Windows.Forms.Padding(0, 16, 16, 16);

            panelListado.Dock = System.Windows.Forms.DockStyle.Fill;
            panelListado.Controls.Add(tabla);
            panelListado.Controls.Add(lblListadoTitulo);
            lblListadoTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            lblListadoTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            lblListadoTitulo.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            lblListadoTitulo.Height = 34;
            lblListadoTitulo.Text = "Socios con membresia activa";
            lblListadoTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            tabla.Dock = System.Windows.Forms.DockStyle.Fill;
            tabla.AllowUserToAddRows = false;
            tabla.AllowUserToDeleteRows = false;
            tabla.AllowUserToResizeRows = false;
            tabla.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            tabla.BackgroundColor = System.Drawing.Color.White;
            tabla.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            tabla.ColumnHeadersHeight = 34;
            tabla.MultiSelect = false;
            tabla.ReadOnly = true;
            tabla.RowHeadersVisible = false;
            tabla.RowTemplate.Height = 30;
            tabla.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            tabla.TabIndex = 4;
            tabla.SelectionChanged += new System.EventHandler(tabla_SelectionChanged);
            colIdSocio.Name = "colIdSocio"; colIdSocio.Visible = false;
            colIdMembresia.Name = "colIdMembresia"; colIdMembresia.Visible = false;
            colSocio.HeaderText = "Socio"; colSocio.Name = "colSocio"; colSocio.FillWeight = 28; colSocio.MinimumWidth = 60;
            colDni.HeaderText = "DNI"; colDni.Name = "colDni"; colDni.FillWeight = 16; colDni.MinimumWidth = 50;
            colPlan.HeaderText = "Plan"; colPlan.Name = "colPlan"; colPlan.FillWeight = 20; colPlan.MinimumWidth = 50;
            colRutina.HeaderText = "Rutina"; colRutina.Name = "colRutina"; colRutina.FillWeight = 22; colRutina.MinimumWidth = 62;
            colVencimiento.HeaderText = "Vence"; colVencimiento.Name = "colVencimiento"; colVencimiento.FillWeight = 16; colVencimiento.MinimumWidth = 62;
            colEstadoRutina.HeaderText = "Estado"; colEstadoRutina.Name = "colEstadoRutina"; colEstadoRutina.FillWeight = 16; colEstadoRutina.MinimumWidth = 66;
            tabla.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colIdSocio, colIdMembresia, colSocio, colDni, colPlan, colRutina, colVencimiento, colEstadoRutina });

            panelDetalle.Size = new System.Drawing.Size(718, 566);
            panelDetalle.Dock = System.Windows.Forms.DockStyle.Fill;
            panelDetalle.Controls.Add(grupoRutina);
            panelDetalle.Controls.Add(grupoSocio);
            grupoSocio.Dock = System.Windows.Forms.DockStyle.Top;
            grupoSocio.Height = 180;
            grupoSocio.BackColor = System.Drawing.Color.White;
            grupoSocio.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            grupoSocio.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            grupoSocio.Padding = new System.Windows.Forms.Padding(16);
            grupoSocio.Text = "Socio seleccionado";
            grupoSocio.Controls.Add(tablaSocio);
            grupoSocio.Controls.Add(lblDetalleTitulo);
            lblDetalleTitulo.Dock = System.Windows.Forms.DockStyle.Top;
            lblDetalleTitulo.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            lblDetalleTitulo.ForeColor = System.Drawing.Color.FromArgb(79, 70, 229);
            lblDetalleTitulo.Height = 30;
            lblDetalleTitulo.Text = "Selecciona un socio";
            tablaSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            tablaSocio.ColumnCount = 4;
            tablaSocio.RowCount = 3;
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 108F));
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33F));
            tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.34F));
            tablaSocio.Padding = new System.Windows.Forms.Padding(0, 6, 0, 0);
            tablaSocio.Controls.Add(lblSocio, 0, 0); tablaSocio.Controls.Add(txtSocio, 1, 0); tablaSocio.Controls.Add(lblDni, 2, 0); tablaSocio.Controls.Add(txtDni, 3, 0);
            tablaSocio.Controls.Add(lblPlan, 0, 1); tablaSocio.Controls.Add(txtPlan, 1, 1); tablaSocio.Controls.Add(lblEntrenador, 2, 1); tablaSocio.Controls.Add(txtEntrenador, 3, 1);
            tablaSocio.Controls.Add(lblVencimiento, 0, 2); tablaSocio.Controls.Add(txtVencimiento, 1, 2); tablaSocio.Controls.Add(lblRutina, 2, 2); tablaSocio.Controls.Add(txtRutina, 3, 2);
            lblSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            lblSocio.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblSocio.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblSocio.Text = "Socio:";
            lblSocio.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtSocio.Name = "txtSocio";
            txtSocio.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtSocio.BackColor = System.Drawing.SystemColors.Window;
            txtSocio.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            txtSocio.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtSocio.ReadOnly = true;
            txtSocio.TabStop = false;
            txtSocio.Text = "Selecciona un socio";
            lblDni.Dock = System.Windows.Forms.DockStyle.Fill;
            lblDni.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblDni.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblDni.Text = "DNI:";
            lblDni.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtDni.Name = "txtDni";
            txtDni.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtDni.BackColor = System.Drawing.SystemColors.Window;
            txtDni.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            txtDni.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtDni.ReadOnly = true;
            txtDni.TabStop = false;
            txtDni.Text = "-";
            lblPlan.Dock = System.Windows.Forms.DockStyle.Fill;
            lblPlan.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblPlan.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblPlan.Text = "Plan:";
            lblPlan.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtPlan.Name = "txtPlan";
            txtPlan.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtPlan.BackColor = System.Drawing.SystemColors.Window;
            txtPlan.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            txtPlan.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtPlan.ReadOnly = true;
            txtPlan.TabStop = false;
            txtPlan.Text = "-";
            lblEntrenador.Dock = System.Windows.Forms.DockStyle.Fill;
            lblEntrenador.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblEntrenador.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblEntrenador.Text = "Entrenador:";
            lblEntrenador.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtEntrenador.Name = "txtEntrenador";
            txtEntrenador.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtEntrenador.BackColor = System.Drawing.SystemColors.Window;
            txtEntrenador.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            txtEntrenador.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtEntrenador.ReadOnly = true;
            txtEntrenador.TabStop = false;
            txtEntrenador.Text = "-";
            lblVencimiento.Dock = System.Windows.Forms.DockStyle.Fill;
            lblVencimiento.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblVencimiento.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblVencimiento.Text = "Vencimiento:";
            lblVencimiento.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtVencimiento.Name = "txtVencimiento";
            txtVencimiento.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtVencimiento.BackColor = System.Drawing.SystemColors.Window;
            txtVencimiento.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            txtVencimiento.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtVencimiento.ReadOnly = true;
            txtVencimiento.TabStop = false;
            txtVencimiento.Text = "-";
            lblRutina.Dock = System.Windows.Forms.DockStyle.Fill;
            lblRutina.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold);
            lblRutina.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblRutina.Text = "Rutina:";
            lblRutina.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            txtRutina.Name = "txtRutina";
            txtRutina.Anchor = System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            txtRutina.BackColor = System.Drawing.SystemColors.Window;
            txtRutina.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            txtRutina.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            txtRutina.ReadOnly = true;
            txtRutina.TabStop = false;
            txtRutina.Text = "-";

            grupoRutina.Size = new System.Drawing.Size(718, 386);
            grupoRutina.Dock = System.Windows.Forms.DockStyle.Fill;
            grupoRutina.BackColor = System.Drawing.Color.White;
            grupoRutina.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            grupoRutina.ForeColor = System.Drawing.Color.FromArgb(30, 41, 59);
            grupoRutina.Padding = new System.Windows.Forms.Padding(12);
            grupoRutina.Text = "Rutina semanal";
            grupoRutina.Controls.Add(lblAccionInfo);
            grupoRutina.Controls.Add(rutinaDisponible);
            grupoRutina.Controls.Add(asignarRutina);
            grupoRutina.Controls.Add(verRutina);
            grupoRutina.Controls.Add(crearPersonalizada);
            grupoRutina.Controls.Add(exportarPdf);
            grupoRutina.Controls.Add(tablaRutina);
            tablaRutina.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            tablaRutina.Location = new System.Drawing.Point(12, 30);
            tablaRutina.Size = new System.Drawing.Size(694, 194);
            tablaRutina.AllowUserToAddRows = false;
            tablaRutina.AllowUserToDeleteRows = false;
            tablaRutina.AllowUserToResizeRows = false;
            tablaRutina.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            tablaRutina.BackgroundColor = System.Drawing.Color.White;
            tablaRutina.BorderStyle = System.Windows.Forms.BorderStyle.None;
            tablaRutina.ColumnHeadersHeight = 34;
            tablaRutina.Font = new System.Drawing.Font("Segoe UI", 9F);
            tablaRutina.MultiSelect = false;
            tablaRutina.ReadOnly = true;
            tablaRutina.RowHeadersVisible = false;
            tablaRutina.RowTemplate.Height = 28;
            tablaRutina.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            tablaRutina.TabIndex = 5;
            colDia.HeaderText = "Dia"; colDia.Name = "colDia"; colDia.FillWeight = 16; colDia.MinimumWidth = 54;
            colEjercicio.HeaderText = "Ejercicio"; colEjercicio.Name = "colEjercicio"; colEjercicio.FillWeight = 30; colEjercicio.MinimumWidth = 100;
            colSeries.HeaderText = "Series"; colSeries.Name = "colSeries"; colSeries.FillWeight = 12; colSeries.MinimumWidth = 48;
            colRepeticiones.HeaderText = "Repeticiones"; colRepeticiones.Name = "colRepeticiones"; colRepeticiones.FillWeight = 17; colRepeticiones.MinimumWidth = 94;
            colPeso.HeaderText = "Peso"; colPeso.Name = "colPeso"; colPeso.FillWeight = 12; colPeso.MinimumWidth = 48;
            colDescanso.HeaderText = "Descanso"; colDescanso.Name = "colDescanso"; colDescanso.FillWeight = 15; colDescanso.MinimumWidth = 78;
            tablaRutina.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { colDia, colEjercicio, colSeries, colRepeticiones, colPeso, colDescanso });
            lblAccionInfo.AutoSize = false;
            lblAccionInfo.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            lblAccionInfo.Margin = new System.Windows.Forms.Padding(0, 4, 8, 0);
            lblAccionInfo.Location = new System.Drawing.Point(12, 234);
            lblAccionInfo.Size = new System.Drawing.Size(694, 44);
            lblAccionInfo.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            lblAccionInfo.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            lblAccionInfo.Text = "Selecciona un socio para ver su rutina y acciones.";
            lblAccionInfo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            rutinaDisponible.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            rutinaDisponible.Margin = new System.Windows.Forms.Padding(0, 4, 8, 0);
            rutinaDisponible.Location = new System.Drawing.Point(12, 296);
            rutinaDisponible.Size = new System.Drawing.Size(550, 25);
            rutinaDisponible.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            rutinaDisponible.TabIndex = 6;
            rutinaDisponible.Visible = false;
            asignarRutina.AutoSize = false;
            asignarRutina.BackColor = System.Drawing.Color.FromArgb(79, 70, 229);
            asignarRutina.FlatAppearance.BorderSize = 0;
            asignarRutina.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            asignarRutina.ForeColor = System.Drawing.Color.White;
            asignarRutina.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            asignarRutina.Size = new System.Drawing.Size(136, 34);
            asignarRutina.Location = new System.Drawing.Point(570, 292);
            asignarRutina.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            asignarRutina.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            asignarRutina.TabIndex = 7;
            asignarRutina.Text = "Asignar rutina";
            asignarRutina.UseVisualStyleBackColor = false;
            asignarRutina.Visible = false;
            asignarRutina.Click += new System.EventHandler(asignarRutina_Click);
            verRutina.AutoSize = false;
            verRutina.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            verRutina.FlatAppearance.BorderSize = 0;
            verRutina.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            verRutina.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            verRutina.Size = new System.Drawing.Size(192, 34);
            verRutina.Location = new System.Drawing.Point(370, 332);
            verRutina.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            verRutina.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            verRutina.TabIndex = 8;
            verRutina.Text = "Ver / editar";
            verRutina.UseVisualStyleBackColor = false;
            verRutina.Visible = false;
            verRutina.Click += new System.EventHandler(verRutina_Click);
            crearPersonalizada.AutoSize = false;
            crearPersonalizada.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            crearPersonalizada.FlatAppearance.BorderSize = 0;
            crearPersonalizada.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            crearPersonalizada.Margin = new System.Windows.Forms.Padding(0, 2, 8, 0);
            crearPersonalizada.Size = new System.Drawing.Size(192, 34);
            crearPersonalizada.Location = new System.Drawing.Point(370, 332);
            crearPersonalizada.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            crearPersonalizada.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            crearPersonalizada.TabIndex = 9;
            crearPersonalizada.Text = "Crear personalizada";
            crearPersonalizada.UseVisualStyleBackColor = false;
            crearPersonalizada.Visible = false;
            crearPersonalizada.Click += new System.EventHandler(crearPersonalizada_Click);
            exportarPdf.Name = "exportarPdf";
            exportarPdf.Text = "Exportar PDF";
            exportarPdf.Size = new System.Drawing.Size(136, 34);
            exportarPdf.Location = new System.Drawing.Point(570, 332);
            exportarPdf.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right;
            exportarPdf.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            exportarPdf.BackColor = System.Drawing.Color.FromArgb(226, 232, 240);
            exportarPdf.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            exportarPdf.FlatAppearance.BorderSize = 0;
            exportarPdf.UseVisualStyleBackColor = false;
            exportarPdf.Enabled = false;
            exportarPdf.TabIndex = 10;
            exportarPdf.Click += new System.EventHandler(exportarPdf_Click);

            splitContenido.Panel1.Controls.Add(panelListado);
            splitContenido.Panel2.Controls.Add(panelDetalle);
            Controls.Add(splitContenido);
            Controls.Add(lblEstado);
            Controls.Add(barraAcciones);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            ClientSize = new System.Drawing.Size(1100, 680);
            Font = new System.Drawing.Font("Segoe UI", 9.5F);
            MinimumSize = new System.Drawing.Size(900, 560);
            Name = "MisSociosFormulario";
            StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            Text = "SysGym | Mis socios y rutinas";
            Load += new System.EventHandler(MisSociosFormulario_Load);
            splitContenido.SplitterDistance = 360;
            grupoRutina.ResumeLayout(false);
            tablaSocio.ResumeLayout(false);
            tablaSocio.PerformLayout();
            grupoSocio.ResumeLayout(false);
            panelDetalle.ResumeLayout(false);
            panelListado.ResumeLayout(false);
            splitContenido.Panel2.ResumeLayout(false);
            splitContenido.Panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(splitContenido)).EndInit();
            splitContenido.ResumeLayout(false);
            barraAcciones.ResumeLayout(false);
            barraAcciones.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(tablaRutina)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(tabla)).EndInit();
            ResumeLayout(false);
        }

    }
}
