using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Entrenador
{
    partial class RutinasEntrenadorForm
    {
        private IContainer components;
        private Panel panelEncabezado; private Label lblTitulo; private Label lblDescripcion; private Button btnVolver; private FlowLayoutPanel barraAcciones; private Label lblEstado; private Panel panelContenido; private Panel panelFormulario; private TableLayoutPanel layoutFormulario; private Label lblNombre; private Label lblDescripcionRutina; private Label lblEjercicio; private Label lblSeries; private Label lblRepeticiones; private Label lblPeso; private Label lblDescanso; private Label lblOrden; private Label lblMembresia; private DataGridView tabla; private DataGridViewTextBoxColumn colId; private DataGridViewTextBoxColumn colRutina; private DataGridViewTextBoxColumn colCreador; private DataGridViewTextBoxColumn colAsignados; private DataGridViewTextBoxColumn colCreacion;
        private ComboBox membresia; private ComboBox ejercicio; private TextBox nombre; private TextBox descripcion; private TextBox series; private TextBox repeticiones; private TextBox peso; private TextBox descanso; private TextBox orden; private Button nuevaRutina; private Button guardarRutina; private Button actualizar; private Button agregarEjercicio; private Button asignar; private Button darDeBaja;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new Container(); panelEncabezado = new Panel(); lblTitulo = new Label(); lblDescripcion = new Label(); btnVolver = new Button(); barraAcciones = new FlowLayoutPanel(); nuevaRutina = new Button(); guardarRutina = new Button(); actualizar = new Button(); agregarEjercicio = new Button(); asignar = new Button(); darDeBaja = new Button(); lblEstado = new Label(); panelContenido = new Panel(); panelFormulario = new Panel(); layoutFormulario = new TableLayoutPanel(); lblNombre = new Label(); nombre = new TextBox(); lblDescripcionRutina = new Label(); descripcion = new TextBox(); lblEjercicio = new Label(); ejercicio = new ComboBox(); lblSeries = new Label(); series = new TextBox(); lblRepeticiones = new Label(); repeticiones = new TextBox(); lblPeso = new Label(); peso = new TextBox(); lblDescanso = new Label(); descanso = new TextBox(); lblOrden = new Label(); orden = new TextBox(); lblMembresia = new Label(); membresia = new ComboBox(); tabla = new DataGridView(); colId = new DataGridViewTextBoxColumn(); colRutina = new DataGridViewTextBoxColumn(); colCreador = new DataGridViewTextBoxColumn(); colAsignados = new DataGridViewTextBoxColumn(); colCreacion = new DataGridViewTextBoxColumn(); panelEncabezado.SuspendLayout(); barraAcciones.SuspendLayout(); panelContenido.SuspendLayout(); panelFormulario.SuspendLayout(); layoutFormulario.SuspendLayout(); ((ISupportInitialize)(tabla)).BeginInit(); SuspendLayout();
            panelEncabezado.BackColor = Color.FromArgb(14, 116, 144); panelEncabezado.Dock = DockStyle.Top; panelEncabezado.Height = 80; panelEncabezado.Controls.Add(lblDescripcion); panelEncabezado.Controls.Add(lblTitulo); panelEncabezado.Controls.Add(btnVolver); lblTitulo.AutoSize = true; lblTitulo.Font = new Font("Segoe UI", 18F, FontStyle.Bold); lblTitulo.ForeColor = Color.White; lblTitulo.Location = new Point(22, 10); lblTitulo.Text = "Catalogo de rutinas"; lblDescripcion.AutoSize = true; lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240); lblDescripcion.Location = new Point(24, 47); lblDescripcion.Text = "Crea plantillas y asigna ejercicios a tus socios"; btnVolver.Anchor = AnchorStyles.Top | AnchorStyles.Right; btnVolver.BackColor = Color.White; btnVolver.FlatStyle = FlatStyle.Flat; btnVolver.FlatAppearance.BorderSize = 0; btnVolver.ForeColor = Color.FromArgb(14, 116, 144); btnVolver.Location = new Point(930, 22); btnVolver.Size = new Size(92, 34); btnVolver.Text = "Volver"; btnVolver.UseVisualStyleBackColor = false;
            barraAcciones.BackColor = Color.White; barraAcciones.Dock = DockStyle.Top; barraAcciones.Height = 52; barraAcciones.Padding = new Padding(16, 8, 16, 8); barraAcciones.WrapContents = false; barraAcciones.Controls.Add(nuevaRutina); barraAcciones.Controls.Add(guardarRutina); barraAcciones.Controls.Add(actualizar); barraAcciones.Controls.Add(agregarEjercicio); barraAcciones.Controls.Add(asignar); barraAcciones.Controls.Add(darDeBaja);
            lblEstado.AutoSize = false; lblEstado.BackColor = Color.FromArgb(226, 232, 240); lblEstado.Dock = DockStyle.Bottom; lblEstado.ForeColor = Color.FromArgb(51, 65, 85); lblEstado.Height = 32; lblEstado.Padding = new Padding(18, 8, 8, 0); lblEstado.Text = "Listo"; panelContenido.BackColor = Color.FromArgb(248, 250, 252); panelContenido.Dock = DockStyle.Fill; panelContenido.Padding = new Padding(20); panelContenido.Controls.Add(tabla); panelContenido.Controls.Add(panelFormulario); panelFormulario.BackColor = Color.White; panelFormulario.BorderStyle = BorderStyle.FixedSingle; panelFormulario.Dock = DockStyle.Top; panelFormulario.Height = 190; panelFormulario.Padding = new Padding(12); panelFormulario.Controls.Add(layoutFormulario); layoutFormulario.ColumnCount = 6; layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 82F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 24F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 88F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 24F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 78F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 52F)); layoutFormulario.Dock = DockStyle.Fill; layoutFormulario.RowCount = 4; layoutFormulario.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F)); layoutFormulario.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F)); layoutFormulario.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F)); layoutFormulario.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            layoutFormulario.Controls.Add(lblNombre, 0, 0); layoutFormulario.Controls.Add(nombre, 1, 0); layoutFormulario.Controls.Add(lblDescripcionRutina, 2, 0); layoutFormulario.Controls.Add(descripcion, 3, 0); layoutFormulario.Controls.Add(lblEjercicio, 0, 1); layoutFormulario.Controls.Add(ejercicio, 1, 1); layoutFormulario.Controls.Add(lblSeries, 2, 1); layoutFormulario.Controls.Add(series, 3, 1); layoutFormulario.Controls.Add(lblRepeticiones, 4, 1); layoutFormulario.Controls.Add(repeticiones, 5, 1); layoutFormulario.Controls.Add(lblPeso, 0, 2); layoutFormulario.Controls.Add(peso, 1, 2); layoutFormulario.Controls.Add(lblDescanso, 2, 2); layoutFormulario.Controls.Add(descanso, 3, 2); layoutFormulario.Controls.Add(lblOrden, 4, 2); layoutFormulario.Controls.Add(orden, 5, 2); layoutFormulario.Controls.Add(lblMembresia, 0, 3); layoutFormulario.Controls.Add(membresia, 5, 3); nombre.Dock = DockStyle.Fill; descripcion.Dock = DockStyle.Fill; ejercicio.Dock = DockStyle.Fill; ejercicio.DropDownStyle = ComboBoxStyle.DropDownList; series.Dock = DockStyle.Fill; repeticiones.Dock = DockStyle.Fill; peso.Dock = DockStyle.Fill; descanso.Dock = DockStyle.Fill; orden.Dock = DockStyle.Fill; membresia.Dock = DockStyle.Fill; membresia.DropDownStyle = ComboBoxStyle.DropDownList;
            layoutFormulario.SetColumnSpan(membresia, 5);
            tabla.AllowUserToAddRows = false; tabla.AllowUserToDeleteRows = false; tabla.AllowUserToResizeRows = false; tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; tabla.BackgroundColor = Color.White; tabla.BorderStyle = BorderStyle.None; tabla.ColumnHeadersHeight = 38; tabla.Dock = DockStyle.Fill; tabla.MultiSelect = false; tabla.ReadOnly = true; tabla.RowHeadersVisible = false; tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect; tabla.Columns.AddRange(new DataGridViewColumn[] { colId, colRutina, colCreador, colAsignados, colCreacion }); colId.HeaderText = "Id"; colId.Name = "colId"; colId.Visible = false; colRutina.HeaderText = "Rutina"; colRutina.Name = "colRutina"; colCreador.HeaderText = "Entrenador"; colCreador.Name = "colCreador"; colAsignados.HeaderText = "Socios asignados"; colAsignados.Name = "colAsignados"; colCreacion.HeaderText = "Creacion"; colCreacion.Name = "colCreacion";
            panelEncabezado.Location = new Point(0, 0); panelEncabezado.Name = "panelEncabezado"; panelEncabezado.Size = new Size(1100, 80); panelEncabezado.TabIndex = 0;
            lblTitulo.Name = "lblTitulo"; lblTitulo.Size = new Size(247, 32); lblTitulo.TabIndex = 0; lblDescripcion.Name = "lblDescripcion"; lblDescripcion.Size = new Size(306, 17); lblDescripcion.TabIndex = 1; btnVolver.Name = "btnVolver"; btnVolver.TabIndex = 2;
            barraAcciones.Location = new Point(0, 80); barraAcciones.Name = "barraAcciones"; barraAcciones.Size = new Size(1100, 52); barraAcciones.TabIndex = 1;
            nuevaRutina.AutoSize = true; nuevaRutina.BackColor = Color.FromArgb(226, 232, 240); nuevaRutina.FlatAppearance.BorderSize = 0; nuevaRutina.FlatStyle = FlatStyle.Flat; nuevaRutina.ForeColor = Color.FromArgb(30, 41, 59); nuevaRutina.Height = 36; nuevaRutina.Margin = new Padding(4, 0, 4, 0); nuevaRutina.Name = "nuevaRutina"; nuevaRutina.Padding = new Padding(10, 0, 10, 0); nuevaRutina.Text = "+ Nueva rutina"; nuevaRutina.UseVisualStyleBackColor = false;
            guardarRutina.AutoSize = true; guardarRutina.BackColor = Color.FromArgb(14, 116, 144); guardarRutina.FlatAppearance.BorderSize = 0; guardarRutina.FlatStyle = FlatStyle.Flat; guardarRutina.ForeColor = Color.White; guardarRutina.Height = 36; guardarRutina.Margin = new Padding(4, 0, 4, 0); guardarRutina.Name = "guardarRutina"; guardarRutina.Padding = new Padding(10, 0, 10, 0); guardarRutina.Text = "Guardar"; guardarRutina.UseVisualStyleBackColor = false;
            actualizar.AutoSize = true; actualizar.BackColor = Color.FromArgb(226, 232, 240); actualizar.FlatAppearance.BorderSize = 0; actualizar.FlatStyle = FlatStyle.Flat; actualizar.ForeColor = Color.FromArgb(30, 41, 59); actualizar.Height = 36; actualizar.Margin = new Padding(4, 0, 4, 0); actualizar.Name = "actualizar"; actualizar.Padding = new Padding(10, 0, 10, 0); actualizar.Text = "Actualizar"; actualizar.UseVisualStyleBackColor = false;
            agregarEjercicio.AutoSize = true; agregarEjercicio.BackColor = Color.FromArgb(14, 116, 144); agregarEjercicio.FlatAppearance.BorderSize = 0; agregarEjercicio.FlatStyle = FlatStyle.Flat; agregarEjercicio.ForeColor = Color.White; agregarEjercicio.Height = 36; agregarEjercicio.Margin = new Padding(4, 0, 4, 0); agregarEjercicio.Name = "agregarEjercicio"; agregarEjercicio.Padding = new Padding(10, 0, 10, 0); agregarEjercicio.Text = "Agregar ejercicio"; agregarEjercicio.UseVisualStyleBackColor = false;
            asignar.AutoSize = true; asignar.BackColor = Color.FromArgb(14, 116, 144); asignar.FlatAppearance.BorderSize = 0; asignar.FlatStyle = FlatStyle.Flat; asignar.ForeColor = Color.White; asignar.Height = 36; asignar.Margin = new Padding(4, 0, 4, 0); asignar.Name = "asignar"; asignar.Padding = new Padding(10, 0, 10, 0); asignar.Text = "Asignar a socio"; asignar.UseVisualStyleBackColor = false;
            darDeBaja.AutoSize = true; darDeBaja.BackColor = Color.FromArgb(254, 242, 242); darDeBaja.FlatAppearance.BorderSize = 0; darDeBaja.FlatStyle = FlatStyle.Flat; darDeBaja.ForeColor = Color.FromArgb(185, 28, 28); darDeBaja.Height = 36; darDeBaja.Margin = new Padding(4, 0, 4, 0); darDeBaja.Name = "darDeBaja"; darDeBaja.Padding = new Padding(10, 0, 10, 0); darDeBaja.Text = "Dar de baja"; darDeBaja.UseVisualStyleBackColor = false;
            lblEstado.Location = new Point(0, 648); lblEstado.Name = "lblEstado"; lblEstado.Size = new Size(1100, 32); lblEstado.TabIndex = 3; panelContenido.Location = new Point(0, 132); panelContenido.Name = "panelContenido"; panelContenido.Size = new Size(1100, 516); panelContenido.TabIndex = 2; panelFormulario.Location = new Point(20, 20); panelFormulario.Name = "panelFormulario"; panelFormulario.Size = new Size(1060, 190); panelFormulario.TabIndex = 0; layoutFormulario.Location = new Point(12, 12); layoutFormulario.Name = "layoutFormulario"; layoutFormulario.Size = new Size(1034, 164); layoutFormulario.TabIndex = 0;
            lblNombre.Anchor = AnchorStyles.Left; lblNombre.AutoSize = true; lblNombre.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblNombre.ForeColor = Color.FromArgb(30, 41, 59); lblNombre.Name = "lblNombre"; lblNombre.Text = "Nombre:";
            lblDescripcionRutina.Anchor = AnchorStyles.Left; lblDescripcionRutina.AutoSize = true; lblDescripcionRutina.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblDescripcionRutina.ForeColor = Color.FromArgb(30, 41, 59); lblDescripcionRutina.Name = "lblDescripcionRutina"; lblDescripcionRutina.Text = "Descripcion:";
            lblEjercicio.Anchor = AnchorStyles.Left; lblEjercicio.AutoSize = true; lblEjercicio.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblEjercicio.ForeColor = Color.FromArgb(30, 41, 59); lblEjercicio.Name = "lblEjercicio"; lblEjercicio.Text = "Ejercicio:";
            lblSeries.Anchor = AnchorStyles.Left; lblSeries.AutoSize = true; lblSeries.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblSeries.ForeColor = Color.FromArgb(30, 41, 59); lblSeries.Name = "lblSeries"; lblSeries.Text = "Series:";
            lblRepeticiones.Anchor = AnchorStyles.Left; lblRepeticiones.AutoSize = true; lblRepeticiones.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblRepeticiones.ForeColor = Color.FromArgb(30, 41, 59); lblRepeticiones.Name = "lblRepeticiones"; lblRepeticiones.Text = "Repeticiones:";
            lblPeso.Anchor = AnchorStyles.Left; lblPeso.AutoSize = true; lblPeso.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblPeso.ForeColor = Color.FromArgb(30, 41, 59); lblPeso.Name = "lblPeso"; lblPeso.Text = "Peso:";
            lblDescanso.Anchor = AnchorStyles.Left; lblDescanso.AutoSize = true; lblDescanso.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblDescanso.ForeColor = Color.FromArgb(30, 41, 59); lblDescanso.Name = "lblDescanso"; lblDescanso.Text = "Descanso:";
            lblOrden.Anchor = AnchorStyles.Left; lblOrden.AutoSize = true; lblOrden.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblOrden.ForeColor = Color.FromArgb(30, 41, 59); lblOrden.Name = "lblOrden"; lblOrden.Text = "Orden:";
            lblMembresia.Anchor = AnchorStyles.Left; lblMembresia.AutoSize = true; lblMembresia.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblMembresia.ForeColor = Color.FromArgb(30, 41, 59); lblMembresia.Name = "lblMembresia"; lblMembresia.Text = "Membresia:";
            nombre.BorderStyle = BorderStyle.FixedSingle; nombre.Margin = new Padding(0, 4, 8, 4); nombre.Name = "nombre"; descripcion.BorderStyle = BorderStyle.FixedSingle; descripcion.Margin = new Padding(0, 4, 8, 4); descripcion.Name = "descripcion"; ejercicio.Margin = new Padding(0, 4, 8, 4); ejercicio.Name = "ejercicio"; series.BorderStyle = BorderStyle.FixedSingle; series.Margin = new Padding(0, 4, 8, 4); series.Name = "series"; repeticiones.BorderStyle = BorderStyle.FixedSingle; repeticiones.Margin = new Padding(0, 4, 8, 4); repeticiones.Name = "repeticiones"; peso.BorderStyle = BorderStyle.FixedSingle; peso.Margin = new Padding(0, 4, 8, 4); peso.Name = "peso"; descanso.BorderStyle = BorderStyle.FixedSingle; descanso.Margin = new Padding(0, 4, 8, 4); descanso.Name = "descanso"; orden.BorderStyle = BorderStyle.FixedSingle; orden.Margin = new Padding(0, 4, 8, 4); orden.Name = "orden"; membresia.Margin = new Padding(0, 4, 8, 4); membresia.Name = "membresia";
            tabla.Location = new Point(20, 210); tabla.Name = "tabla"; tabla.Size = new Size(1060, 286); tabla.TabIndex = 1; colId.Width = 60; colRutina.Width = 300; colCreador.Width = 260; colAsignados.Width = 220; colCreacion.Width = 220;
            Controls.Add(panelContenido); Controls.Add(lblEstado); Controls.Add(barraAcciones); Controls.Add(panelEncabezado); AutoScaleMode = AutoScaleMode.Font; BackColor = Color.FromArgb(241, 245, 249); ClientSize = new Size(1100, 680); Font = new Font("Segoe UI", 9.5F); MinimumSize = new Size(760, 540); Name = "RutinasEntrenadorForm"; StartPosition = FormStartPosition.CenterParent; Text = "SysGym | Catalogo de rutinas"; nuevaRutina.Click += NuevaRutina; guardarRutina.Click += CrearOActualizar; actualizar.Click += delegate { Cargar(); }; agregarEjercicio.Click += AgregarEjercicio; asignar.Click += Asignar; darDeBaja.Click += DarDeBaja;
            panelEncabezado.ResumeLayout(false); panelEncabezado.PerformLayout(); barraAcciones.ResumeLayout(false); barraAcciones.PerformLayout(); panelContenido.ResumeLayout(false); panelFormulario.ResumeLayout(false); layoutFormulario.ResumeLayout(false); layoutFormulario.PerformLayout(); ((ISupportInitialize)(tabla)).EndInit(); ResumeLayout(false);
        }

    }
}
