using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Entrenador
{
    partial class RutinasEntrenadorFormulario
    {
        private IContainer components;
        private Panel panelEncabezado; private Label lblTitulo; private Label lblDescripcion; private Button btnVolver; private Panel barraAcciones; private Label lblEstado; private Panel panelContenido; private Panel panelFormulario; private Panel contenedorFormulario; private Label lblNombre; private Label lblDescripcionRutina; private Label lblEjercicio; private Label lblSeries; private Label lblRepeticiones; private Label lblPeso; private Label lblDescanso; private Label lblOrden; private Label lblMembresia; private DataGridView tabla; private DataGridViewTextBoxColumn colId; private DataGridViewTextBoxColumn colRutina; private DataGridViewTextBoxColumn colCreador; private DataGridViewTextBoxColumn colAsignados; private DataGridViewTextBoxColumn colCreacion;
        private ComboBox membresia; private ComboBox ejercicio; private TextBox nombre; private TextBox descripcion; private TextBox series; private TextBox repeticiones; private TextBox peso; private TextBox descanso; private TextBox orden; private Button nuevaRutina; private Button guardarRutina; private Button actualizar; private Button agregarEjercicio; private Button asignar; private Button darDeBaja;
        protected override void Dispose(bool liberarRecursos) { if (liberarRecursos && components != null) components.Dispose(); base.Dispose(liberarRecursos); }

        private void InitializeComponent()
        {
            components = new Container(); panelEncabezado = new Panel(); lblTitulo = new Label(); lblDescripcion = new Label(); btnVolver = new Button(); barraAcciones = new Panel(); nuevaRutina = new Button(); guardarRutina = new Button(); actualizar = new Button(); agregarEjercicio = new Button(); asignar = new Button(); darDeBaja = new Button(); lblEstado = new Label(); panelContenido = new Panel(); panelFormulario = new Panel(); contenedorFormulario = new Panel(); lblNombre = new Label(); nombre = new TextBox(); lblDescripcionRutina = new Label(); descripcion = new TextBox(); lblEjercicio = new Label(); ejercicio = new ComboBox(); lblSeries = new Label(); series = new TextBox(); lblRepeticiones = new Label(); repeticiones = new TextBox(); lblPeso = new Label(); peso = new TextBox(); lblDescanso = new Label(); descanso = new TextBox(); lblOrden = new Label(); orden = new TextBox(); lblMembresia = new Label(); membresia = new ComboBox(); tabla = new DataGridView(); colId = new DataGridViewTextBoxColumn(); colRutina = new DataGridViewTextBoxColumn(); colCreador = new DataGridViewTextBoxColumn(); colAsignados = new DataGridViewTextBoxColumn(); colCreacion = new DataGridViewTextBoxColumn(); panelEncabezado.SuspendLayout(); barraAcciones.SuspendLayout(); panelContenido.SuspendLayout(); panelFormulario.SuspendLayout(); contenedorFormulario.SuspendLayout(); ((ISupportInitialize)(tabla)).BeginInit(); SuspendLayout();
            panelEncabezado.BackColor = Color.FromArgb(14, 116, 144);   panelEncabezado.Controls.Add(lblDescripcion); panelEncabezado.Controls.Add(lblTitulo); panelEncabezado.Controls.Add(btnVolver);  lblTitulo.Font = new Font("Segoe UI", 18F, FontStyle.Bold); lblTitulo.ForeColor = Color.White;  lblTitulo.Text = "Catalogo de rutinas";  lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240);  lblDescripcion.Text = "Crea plantillas y asigna ejercicios a tus socios";  btnVolver.BackColor = Color.White; btnVolver.FlatStyle = FlatStyle.Flat; btnVolver.FlatAppearance.BorderSize = 0; btnVolver.ForeColor = Color.FromArgb(14, 116, 144);   btnVolver.Text = "Volver"; btnVolver.UseVisualStyleBackColor = false;
            barraAcciones.BackColor = Color.White;   barraAcciones.Padding = new Padding(16, 8, 16, 8);  barraAcciones.Controls.Add(nuevaRutina); barraAcciones.Controls.Add(guardarRutina); barraAcciones.Controls.Add(actualizar); barraAcciones.Controls.Add(agregarEjercicio); barraAcciones.Controls.Add(asignar); barraAcciones.Controls.Add(darDeBaja);
             lblEstado.BackColor = Color.FromArgb(226, 232, 240);  lblEstado.ForeColor = Color.FromArgb(51, 65, 85);  lblEstado.Padding = new Padding(18, 8, 8, 0); lblEstado.Text = "Listo"; panelContenido.BackColor = Color.FromArgb(248, 250, 252);  panelContenido.Padding = new Padding(20); panelContenido.Controls.Add(tabla); panelContenido.Controls.Add(panelFormulario); panelFormulario.BackColor = Color.White; panelFormulario.BorderStyle = BorderStyle.FixedSingle;   panelFormulario.Padding = new Padding(12); panelFormulario.Controls.Add(contenedorFormulario);             
            contenedorFormulario.Controls.Add(lblNombre); contenedorFormulario.Controls.Add(nombre); contenedorFormulario.Controls.Add(lblDescripcionRutina); contenedorFormulario.Controls.Add(descripcion); contenedorFormulario.Controls.Add(lblEjercicio); contenedorFormulario.Controls.Add(ejercicio); contenedorFormulario.Controls.Add(lblSeries); contenedorFormulario.Controls.Add(series); contenedorFormulario.Controls.Add(lblRepeticiones); contenedorFormulario.Controls.Add(repeticiones); contenedorFormulario.Controls.Add(lblPeso); contenedorFormulario.Controls.Add(peso); contenedorFormulario.Controls.Add(lblDescanso); contenedorFormulario.Controls.Add(descanso); contenedorFormulario.Controls.Add(lblOrden); contenedorFormulario.Controls.Add(orden); contenedorFormulario.Controls.Add(lblMembresia); contenedorFormulario.Controls.Add(membresia);    ejercicio.DropDownStyle = ComboBoxStyle.DropDownList;       membresia.DropDownStyle = ComboBoxStyle.DropDownList;

            tabla.AllowUserToAddRows = false; tabla.AllowUserToDeleteRows = false; tabla.AllowUserToResizeRows = false; tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; tabla.BackgroundColor = Color.White; tabla.BorderStyle = BorderStyle.None; tabla.ColumnHeadersHeight = 38;  tabla.MultiSelect = false; tabla.ReadOnly = true; tabla.RowHeadersVisible = false; tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect; tabla.Columns.AddRange(new DataGridViewColumn[] { colId, colRutina, colCreador, colAsignados, colCreacion }); colId.HeaderText = "Id"; colId.Name = "colId"; colId.Visible = false; colRutina.HeaderText = "Rutina"; colRutina.Name = "colRutina"; colCreador.HeaderText = "Entrenador"; colCreador.Name = "colCreador"; colAsignados.HeaderText = "Socios asignados"; colAsignados.Name = "colAsignados"; colCreacion.HeaderText = "Creacion"; colCreacion.Name = "colCreacion";
             panelEncabezado.Name = "panelEncabezado";  panelEncabezado.TabIndex = 0;
            lblTitulo.Name = "lblTitulo";  lblTitulo.TabIndex = 0; lblDescripcion.Name = "lblDescripcion";  lblDescripcion.TabIndex = 1; btnVolver.Name = "btnVolver"; btnVolver.TabIndex = 2;
             barraAcciones.Name = "barraAcciones";  barraAcciones.TabIndex = 1;
             nuevaRutina.BackColor = Color.FromArgb(226, 232, 240); nuevaRutina.FlatAppearance.BorderSize = 0; nuevaRutina.FlatStyle = FlatStyle.Flat; nuevaRutina.ForeColor = Color.FromArgb(30, 41, 59);  nuevaRutina.Margin = new Padding(4, 0, 4, 0); nuevaRutina.Name = "nuevaRutina"; nuevaRutina.Padding = new Padding(10, 0, 10, 0); nuevaRutina.Text = "+ Nueva rutina"; nuevaRutina.UseVisualStyleBackColor = false;
             guardarRutina.BackColor = Color.FromArgb(14, 116, 144); guardarRutina.FlatAppearance.BorderSize = 0; guardarRutina.FlatStyle = FlatStyle.Flat; guardarRutina.ForeColor = Color.White;  guardarRutina.Margin = new Padding(4, 0, 4, 0); guardarRutina.Name = "guardarRutina"; guardarRutina.Padding = new Padding(10, 0, 10, 0); guardarRutina.Text = "Guardar"; guardarRutina.UseVisualStyleBackColor = false;
             actualizar.BackColor = Color.FromArgb(226, 232, 240); actualizar.FlatAppearance.BorderSize = 0; actualizar.FlatStyle = FlatStyle.Flat; actualizar.ForeColor = Color.FromArgb(30, 41, 59);  actualizar.Margin = new Padding(4, 0, 4, 0); actualizar.Name = "actualizar"; actualizar.Padding = new Padding(10, 0, 10, 0); actualizar.Text = "Actualizar"; actualizar.UseVisualStyleBackColor = false;
             agregarEjercicio.BackColor = Color.FromArgb(14, 116, 144); agregarEjercicio.FlatAppearance.BorderSize = 0; agregarEjercicio.FlatStyle = FlatStyle.Flat; agregarEjercicio.ForeColor = Color.White;  agregarEjercicio.Margin = new Padding(4, 0, 4, 0); agregarEjercicio.Name = "agregarEjercicio"; agregarEjercicio.Padding = new Padding(10, 0, 10, 0); agregarEjercicio.Text = "Agregar ejercicio"; agregarEjercicio.UseVisualStyleBackColor = false;
             asignar.BackColor = Color.FromArgb(14, 116, 144); asignar.FlatAppearance.BorderSize = 0; asignar.FlatStyle = FlatStyle.Flat; asignar.ForeColor = Color.White;  asignar.Margin = new Padding(4, 0, 4, 0); asignar.Name = "asignar"; asignar.Padding = new Padding(10, 0, 10, 0); asignar.Text = "Asignar a socio"; asignar.UseVisualStyleBackColor = false;
             darDeBaja.BackColor = Color.FromArgb(254, 242, 242); darDeBaja.FlatAppearance.BorderSize = 0; darDeBaja.FlatStyle = FlatStyle.Flat; darDeBaja.ForeColor = Color.FromArgb(185, 28, 28);  darDeBaja.Margin = new Padding(4, 0, 4, 0); darDeBaja.Name = "darDeBaja"; darDeBaja.Padding = new Padding(10, 0, 10, 0); darDeBaja.Text = "Dar de baja"; darDeBaja.UseVisualStyleBackColor = false;
             lblEstado.Name = "lblEstado";  lblEstado.TabIndex = 3;  panelContenido.Name = "panelContenido";  panelContenido.TabIndex = 2;  panelFormulario.Name = "panelFormulario";  panelFormulario.TabIndex = 0;  contenedorFormulario.Name = "contenedorFormulario";  contenedorFormulario.TabIndex = 0;
              lblNombre.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblNombre.ForeColor = Color.FromArgb(30, 41, 59); lblNombre.Name = "lblNombre"; lblNombre.Text = "Nombre:";
              lblDescripcionRutina.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblDescripcionRutina.ForeColor = Color.FromArgb(30, 41, 59); lblDescripcionRutina.Name = "lblDescripcionRutina"; lblDescripcionRutina.Text = "Descripcion:";
              lblEjercicio.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblEjercicio.ForeColor = Color.FromArgb(30, 41, 59); lblEjercicio.Name = "lblEjercicio"; lblEjercicio.Text = "Ejercicio:";
              lblSeries.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblSeries.ForeColor = Color.FromArgb(30, 41, 59); lblSeries.Name = "lblSeries"; lblSeries.Text = "Series:";
              lblRepeticiones.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblRepeticiones.ForeColor = Color.FromArgb(30, 41, 59); lblRepeticiones.Name = "lblRepeticiones"; lblRepeticiones.Text = "Repeticiones:";
              lblPeso.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblPeso.ForeColor = Color.FromArgb(30, 41, 59); lblPeso.Name = "lblPeso"; lblPeso.Text = "Peso:";
              lblDescanso.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblDescanso.ForeColor = Color.FromArgb(30, 41, 59); lblDescanso.Name = "lblDescanso"; lblDescanso.Text = "Descanso:";
              lblOrden.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblOrden.ForeColor = Color.FromArgb(30, 41, 59); lblOrden.Name = "lblOrden"; lblOrden.Text = "Orden:";
              lblMembresia.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblMembresia.ForeColor = Color.FromArgb(30, 41, 59); lblMembresia.Name = "lblMembresia"; lblMembresia.Text = "Membresia:";
            nombre.BorderStyle = BorderStyle.FixedSingle; nombre.Margin = new Padding(0, 4, 8, 4); nombre.Name = "nombre"; descripcion.BorderStyle = BorderStyle.FixedSingle; descripcion.Margin = new Padding(0, 4, 8, 4); descripcion.Name = "descripcion"; ejercicio.Margin = new Padding(0, 4, 8, 4); ejercicio.Name = "ejercicio"; series.BorderStyle = BorderStyle.FixedSingle; series.Margin = new Padding(0, 4, 8, 4); series.Name = "series"; repeticiones.BorderStyle = BorderStyle.FixedSingle; repeticiones.Margin = new Padding(0, 4, 8, 4); repeticiones.Name = "repeticiones"; peso.BorderStyle = BorderStyle.FixedSingle; peso.Margin = new Padding(0, 4, 8, 4); peso.Name = "peso"; descanso.BorderStyle = BorderStyle.FixedSingle; descanso.Margin = new Padding(0, 4, 8, 4); descanso.Name = "descanso"; orden.BorderStyle = BorderStyle.FixedSingle; orden.Margin = new Padding(0, 4, 8, 4); orden.Name = "orden"; membresia.Margin = new Padding(0, 4, 8, 4); membresia.Name = "membresia";
             tabla.Name = "tabla";  tabla.TabIndex = 1; colId.Width = 60; colRutina.Width = 300; colCreador.Width = 260; colAsignados.Width = 220; colCreacion.Width = 220;
            Controls.Add(panelContenido); Controls.Add(lblEstado); Controls.Add(barraAcciones); Controls.Add(panelEncabezado); AutoScaleMode = AutoScaleMode.Font; this.AutoScroll = true; BackColor = Color.FromArgb(241, 245, 249); ClientSize = new Size(1100, 680); Font = new Font("Segoe UI", 9.5F); MinimumSize = new Size(760, 540); this.Name = "RutinasEntrenadorFormulario"; StartPosition = FormStartPosition.CenterParent; Text = "SysGym | Catalogo de rutinas";      

            this.panelEncabezado.AutoSize = false;
            this.panelEncabezado.Dock = System.Windows.Forms.DockStyle.None;
            this.panelEncabezado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelEncabezado.Location = new System.Drawing.Point(0, 0);
            this.panelEncabezado.Size = new System.Drawing.Size(1100, 80);
            this.lblTitulo.AutoSize = false;
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.None;
            this.lblTitulo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblTitulo.Location = new System.Drawing.Point(22, 10);
            this.lblTitulo.Size = new System.Drawing.Size(236, 38);
            this.lblDescripcion.AutoSize = false;
            this.lblDescripcion.Dock = System.Windows.Forms.DockStyle.None;
            this.lblDescripcion.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblDescripcion.Location = new System.Drawing.Point(24, 47);
            this.lblDescripcion.Size = new System.Drawing.Size(263, 22);
            this.btnVolver.AutoSize = false;
            this.btnVolver.Dock = System.Windows.Forms.DockStyle.None;
            this.btnVolver.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnVolver.Location = new System.Drawing.Point(930, 22);
            this.btnVolver.Size = new System.Drawing.Size(92, 34);
            this.barraAcciones.AutoSize = false;
            this.barraAcciones.Dock = System.Windows.Forms.DockStyle.None;
            this.barraAcciones.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.barraAcciones.Location = new System.Drawing.Point(0, 80);
            this.barraAcciones.Size = new System.Drawing.Size(1100, 52);
            this.lblEstado.AutoSize = false;
            this.lblEstado.Dock = System.Windows.Forms.DockStyle.None;
            this.lblEstado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblEstado.Location = new System.Drawing.Point(0, 648);
            this.lblEstado.Size = new System.Drawing.Size(1100, 32);
            this.panelContenido.AutoSize = false;
            this.panelContenido.Dock = System.Windows.Forms.DockStyle.None;
            this.panelContenido.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelContenido.Location = new System.Drawing.Point(0, 132);
            this.panelContenido.Size = new System.Drawing.Size(1100, 516);
            this.panelFormulario.AutoSize = false;
            this.panelFormulario.Dock = System.Windows.Forms.DockStyle.None;
            this.panelFormulario.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelFormulario.Location = new System.Drawing.Point(20, 20);
            this.panelFormulario.Size = new System.Drawing.Size(1060, 220);
            this.contenedorFormulario.AutoSize = false;
            this.contenedorFormulario.Dock = System.Windows.Forms.DockStyle.None;
            this.contenedorFormulario.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.contenedorFormulario.Location = new System.Drawing.Point(12, 12);
            this.contenedorFormulario.Size = new System.Drawing.Size(1034, 194);
            this.lblNombre.AutoSize = false;
            this.lblNombre.Dock = System.Windows.Forms.DockStyle.None;
            this.lblNombre.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblNombre.Location = new System.Drawing.Point(3, 13);
            this.lblNombre.Size = new System.Drawing.Size(54, 21);
            this.lblDescripcionRutina.AutoSize = false;
            this.lblDescripcionRutina.Dock = System.Windows.Forms.DockStyle.None;
            this.lblDescripcionRutina.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblDescripcionRutina.Location = new System.Drawing.Point(273, 13);
            this.lblDescripcionRutina.Size = new System.Drawing.Size(73, 21);
            this.lblEjercicio.AutoSize = false;
            this.lblEjercicio.Dock = System.Windows.Forms.DockStyle.None;
            this.lblEjercicio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblEjercicio.Location = new System.Drawing.Point(3, 61);
            this.lblEjercicio.Size = new System.Drawing.Size(54, 21);
            this.lblSeries.AutoSize = false;
            this.lblSeries.Dock = System.Windows.Forms.DockStyle.None;
            this.lblSeries.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblSeries.Location = new System.Drawing.Point(273, 61);
            this.lblSeries.Size = new System.Drawing.Size(40, 21);
            this.lblRepeticiones.AutoSize = false;
            this.lblRepeticiones.Dock = System.Windows.Forms.DockStyle.None;
            this.lblRepeticiones.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblRepeticiones.Location = new System.Drawing.Point(549, 53);
            this.lblRepeticiones.Size = new System.Drawing.Size(70, 37);
            this.lblPeso.AutoSize = false;
            this.lblPeso.Dock = System.Windows.Forms.DockStyle.None;
            this.lblPeso.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblPeso.Location = new System.Drawing.Point(3, 109);
            this.lblPeso.Size = new System.Drawing.Size(34, 21);
            this.lblDescanso.AutoSize = false;
            this.lblDescanso.Dock = System.Windows.Forms.DockStyle.None;
            this.lblDescanso.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblDescanso.Location = new System.Drawing.Point(273, 109);
            this.lblDescanso.Size = new System.Drawing.Size(60, 21);
            this.lblOrden.AutoSize = false;
            this.lblOrden.Dock = System.Windows.Forms.DockStyle.None;
            this.lblOrden.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblOrden.Location = new System.Drawing.Point(549, 109);
            this.lblOrden.Size = new System.Drawing.Size(43, 21);
            this.lblMembresia.AutoSize = false;
            this.lblMembresia.Dock = System.Windows.Forms.DockStyle.None;
            this.lblMembresia.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblMembresia.Location = new System.Drawing.Point(3, 157);
            this.lblMembresia.Size = new System.Drawing.Size(70, 21);
            this.tabla.AutoSize = false;
            this.tabla.Dock = System.Windows.Forms.DockStyle.None;
            this.tabla.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.tabla.Location = new System.Drawing.Point(20, 240);
            this.tabla.Size = new System.Drawing.Size(1060, 256);
            this.membresia.AutoSize = false;
            this.membresia.Dock = System.Windows.Forms.DockStyle.None;
            this.membresia.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.membresia.Location = new System.Drawing.Point(82, 148);
            this.membresia.Size = new System.Drawing.Size(944, 25);
            this.ejercicio.AutoSize = false;
            this.ejercicio.Dock = System.Windows.Forms.DockStyle.None;
            this.ejercicio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.ejercicio.Location = new System.Drawing.Point(82, 52);
            this.ejercicio.Size = new System.Drawing.Size(180, 25);
            this.nombre.AutoSize = false;
            this.nombre.Dock = System.Windows.Forms.DockStyle.None;
            this.nombre.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.nombre.Location = new System.Drawing.Point(82, 4);
            this.nombre.Size = new System.Drawing.Size(180, 24);
            this.descripcion.AutoSize = false;
            this.descripcion.Dock = System.Windows.Forms.DockStyle.None;
            this.descripcion.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.descripcion.Location = new System.Drawing.Point(358, 4);
            this.descripcion.Size = new System.Drawing.Size(180, 24);
            this.series.AutoSize = false;
            this.series.Dock = System.Windows.Forms.DockStyle.None;
            this.series.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.series.Location = new System.Drawing.Point(358, 52);
            this.series.Size = new System.Drawing.Size(180, 24);
            this.repeticiones.AutoSize = false;
            this.repeticiones.Dock = System.Windows.Forms.DockStyle.None;
            this.repeticiones.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.repeticiones.Location = new System.Drawing.Point(624, 52);
            this.repeticiones.Size = new System.Drawing.Size(402, 24);
            this.peso.AutoSize = false;
            this.peso.Dock = System.Windows.Forms.DockStyle.None;
            this.peso.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.peso.Location = new System.Drawing.Point(82, 100);
            this.peso.Size = new System.Drawing.Size(180, 24);
            this.descanso.AutoSize = false;
            this.descanso.Dock = System.Windows.Forms.DockStyle.None;
            this.descanso.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.descanso.Location = new System.Drawing.Point(358, 100);
            this.descanso.Size = new System.Drawing.Size(180, 24);
            this.orden.AutoSize = false;
            this.orden.Dock = System.Windows.Forms.DockStyle.None;
            this.orden.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.orden.Location = new System.Drawing.Point(624, 100);
            this.orden.Size = new System.Drawing.Size(402, 24);
            this.nuevaRutina.AutoSize = false;
            this.nuevaRutina.Dock = System.Windows.Forms.DockStyle.None;
            this.nuevaRutina.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.nuevaRutina.Location = new System.Drawing.Point(20, 8);
            this.nuevaRutina.Size = new System.Drawing.Size(121, 36);
            this.guardarRutina.AutoSize = false;
            this.guardarRutina.Dock = System.Windows.Forms.DockStyle.None;
            this.guardarRutina.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.guardarRutina.Location = new System.Drawing.Point(149, 8);
            this.guardarRutina.Size = new System.Drawing.Size(81, 36);
            this.actualizar.AutoSize = false;
            this.actualizar.Dock = System.Windows.Forms.DockStyle.None;
            this.actualizar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.actualizar.Location = new System.Drawing.Point(238, 8);
            this.actualizar.Size = new System.Drawing.Size(91, 36);
            this.agregarEjercicio.AutoSize = false;
            this.agregarEjercicio.Dock = System.Windows.Forms.DockStyle.None;
            this.agregarEjercicio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.agregarEjercicio.Location = new System.Drawing.Point(337, 8);
            this.agregarEjercicio.Size = new System.Drawing.Size(132, 36);
            this.asignar.AutoSize = false;
            this.asignar.Dock = System.Windows.Forms.DockStyle.None;
            this.asignar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.asignar.Location = new System.Drawing.Point(477, 8);
            this.asignar.Size = new System.Drawing.Size(122, 36);
            this.darDeBaja.AutoSize = false;
            this.darDeBaja.Dock = System.Windows.Forms.DockStyle.None;
            this.darDeBaja.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.darDeBaja.Location = new System.Drawing.Point(607, 8);
            this.darDeBaja.Size = new System.Drawing.Size(101, 36);
            panelEncabezado.ResumeLayout(false); panelEncabezado.PerformLayout(); barraAcciones.ResumeLayout(false); barraAcciones.PerformLayout(); panelContenido.ResumeLayout(false); panelFormulario.ResumeLayout(false); contenedorFormulario.ResumeLayout(false); contenedorFormulario.PerformLayout(); ((ISupportInitialize)(tabla)).EndInit(); ResumeLayout(false);

            this.Load += new System.EventHandler(this.RutinasEntrenadorFormulario_Load);
            this.btnVolver.Click += new System.EventHandler(this.btnVolver_Click);
            this.membresia.Format += new System.Windows.Forms.ListControlConvertEventHandler(this.membresia_Format);
            this.tabla.SelectionChanged += new System.EventHandler(this.tabla_SelectionChanged);
            this.nuevaRutina.Click += new System.EventHandler(this.nuevaRutina_Click);
            this.guardarRutina.Click += new System.EventHandler(this.guardarRutina_Click);
            this.actualizar.Click += new System.EventHandler(this.actualizar_Click);
            this.agregarEjercicio.Click += new System.EventHandler(this.agregarEjercicio_Click);
            this.asignar.Click += new System.EventHandler(this.asignar_Click);
            this.darDeBaja.Click += new System.EventHandler(this.darDeBaja_Click);
                }

    }
}
