using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Recepcionista
{
    partial class GestionMembresiasForm
    {
        private IContainer components;
        private Panel panelEncabezado; private Label lblTitulo; private Label lblDescripcion; private Button btnVolver; private FlowLayoutPanel barraAcciones; private Label lblEstado; private Panel panelContenido; private TableLayoutPanel layoutContenido; private Panel panelListado; private Label lblListado; private Label lblAyuda; private Panel panelDetalle; private TableLayoutPanel layoutDetalle; private Label lblFormulario; private TableLayoutPanel layoutCampos; private Panel panelAcciones; private Label lblSocio; private Label lblPlan; private Label lblInicio; private Label lblVencimiento; private DataGridView tabla; private DataGridViewTextBoxColumn colId; private DataGridViewTextBoxColumn colSocio; private DataGridViewTextBoxColumn colDni; private DataGridViewTextBoxColumn colPlan; private DataGridViewTextBoxColumn colInicio; private DataGridViewTextBoxColumn colVencimiento; private DataGridViewTextBoxColumn colEstado;
        private TextBox buscador; private ComboBox socio; private ComboBox plan; private DateTimePicker inicio; private DateTimePicker vencimiento; private Button nuevo; private Button crear; private Button actualizar; private Button habilitar; private Button deshabilitar; private Button generarCuota;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new Container(); panelEncabezado = new Panel(); lblTitulo = new Label(); lblDescripcion = new Label(); btnVolver = new Button(); barraAcciones = new FlowLayoutPanel(); lblEstado = new Label(); panelContenido = new Panel(); layoutContenido = new TableLayoutPanel(); panelListado = new Panel(); lblListado = new Label(); lblAyuda = new Label(); buscador = new TextBox(); panelDetalle = new Panel(); layoutDetalle = new TableLayoutPanel(); lblFormulario = new Label(); layoutCampos = new TableLayoutPanel(); panelAcciones = new Panel(); lblSocio = new Label(); lblPlan = new Label(); lblInicio = new Label(); lblVencimiento = new Label(); socio = new ComboBox(); plan = new ComboBox(); inicio = new DateTimePicker(); vencimiento = new DateTimePicker(); nuevo = new Button(); crear = new Button(); actualizar = new Button(); habilitar = new Button(); deshabilitar = new Button(); generarCuota = new Button(); tabla = new DataGridView(); colId = new DataGridViewTextBoxColumn(); colSocio = new DataGridViewTextBoxColumn(); colDni = new DataGridViewTextBoxColumn(); colPlan = new DataGridViewTextBoxColumn(); colInicio = new DataGridViewTextBoxColumn(); colVencimiento = new DataGridViewTextBoxColumn(); colEstado = new DataGridViewTextBoxColumn(); panelEncabezado.SuspendLayout(); panelContenido.SuspendLayout(); layoutContenido.SuspendLayout(); panelListado.SuspendLayout(); ((ISupportInitialize)(tabla)).BeginInit(); panelDetalle.SuspendLayout(); layoutDetalle.SuspendLayout(); layoutCampos.SuspendLayout(); panelAcciones.SuspendLayout(); SuspendLayout();
            panelEncabezado.BackColor = Color.FromArgb(5, 150, 105); panelEncabezado.Dock = DockStyle.Top; panelEncabezado.Height = 80; panelEncabezado.Controls.Add(lblDescripcion); panelEncabezado.Controls.Add(lblTitulo); panelEncabezado.Controls.Add(btnVolver); lblTitulo.AutoSize = true; lblTitulo.Font = new Font("Segoe UI", 18F, FontStyle.Bold); lblTitulo.ForeColor = Color.White; lblTitulo.Location = new Point(22, 10); lblTitulo.Text = "Membresias"; lblDescripcion.AutoSize = true; lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240); lblDescripcion.Location = new Point(24, 47); lblDescripcion.Text = "Asignacion de planes a socios, vigencia y cuotas"; btnVolver.Anchor = AnchorStyles.Top | AnchorStyles.Right; btnVolver.BackColor = Color.White; btnVolver.FlatStyle = FlatStyle.Flat; btnVolver.FlatAppearance.BorderSize = 0; btnVolver.ForeColor = Color.FromArgb(5, 150, 105); btnVolver.Location = new Point(930, 22); btnVolver.Size = new Size(92, 34); btnVolver.Text = "Volver"; btnVolver.UseVisualStyleBackColor = false;
            lblEstado.AutoSize = false; lblEstado.BackColor = Color.FromArgb(226, 232, 240); lblEstado.Dock = DockStyle.Bottom; lblEstado.ForeColor = Color.FromArgb(51, 65, 85); lblEstado.Height = 32; lblEstado.Padding = new Padding(18, 8, 8, 0); lblEstado.Text = "Listo"; panelContenido.BackColor = Color.FromArgb(248, 250, 252); panelContenido.Dock = DockStyle.Fill; panelContenido.Padding = new Padding(12); panelContenido.Controls.Add(layoutContenido); layoutContenido.ColumnCount = 2; layoutContenido.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 57F)); layoutContenido.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 43F)); layoutContenido.Dock = DockStyle.Fill; layoutContenido.Controls.Add(panelListado, 0, 0); layoutContenido.Controls.Add(panelDetalle, 1, 0);
            panelListado.BackColor = Color.White; panelListado.BorderStyle = BorderStyle.FixedSingle; panelListado.Dock = DockStyle.Fill; panelListado.Padding = new Padding(16); panelListado.Controls.Add(tabla); panelListado.Controls.Add(buscador); panelListado.Controls.Add(lblAyuda); panelListado.Controls.Add(lblListado); lblListado.AutoSize = true; lblListado.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold); lblListado.ForeColor = Color.FromArgb(30, 41, 59); lblListado.Location = new Point(16, 14); lblListado.Text = "Membresias"; lblAyuda.AutoSize = true; lblAyuda.ForeColor = Color.FromArgb(100, 116, 139); lblAyuda.Location = new Point(16, 42); lblAyuda.Text = "Busca por socio, DNI o plan"; buscador.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right; buscador.BorderStyle = BorderStyle.FixedSingle; buscador.Location = new Point(16, 70); buscador.Size = new Size(560, 26);
            tabla.AllowUserToAddRows = false; tabla.AllowUserToDeleteRows = false; tabla.AllowUserToResizeRows = false; tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; tabla.BackgroundColor = Color.White; tabla.BorderStyle = BorderStyle.None; tabla.ColumnHeadersHeight = 38; tabla.Dock = DockStyle.Fill; tabla.MultiSelect = false; tabla.ReadOnly = true; tabla.RowHeadersVisible = false; tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect; tabla.Columns.AddRange(new DataGridViewColumn[] { colId, colSocio, colDni, colPlan, colInicio, colVencimiento, colEstado }); colId.HeaderText = "Id"; colId.Name = "colId"; colId.Visible = false; colSocio.HeaderText = "Socio"; colSocio.Name = "colSocio"; colDni.HeaderText = "DNI"; colDni.Name = "colDni"; colPlan.HeaderText = "Plan"; colPlan.Name = "colPlan"; colInicio.HeaderText = "Inicio"; colInicio.Name = "colInicio"; colVencimiento.HeaderText = "Vencimiento"; colVencimiento.Name = "colVencimiento"; colEstado.HeaderText = "Estado"; colEstado.Name = "colEstado";
            panelDetalle.BackColor = Color.White; panelDetalle.BorderStyle = BorderStyle.FixedSingle; panelDetalle.Dock = DockStyle.Fill; panelDetalle.Padding = new Padding(16); panelDetalle.Controls.Add(layoutDetalle); layoutDetalle.ColumnCount = 1; layoutDetalle.Dock = DockStyle.Fill; layoutDetalle.RowCount = 3; layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F)); layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Absolute, 160F)); layoutDetalle.Controls.Add(lblFormulario, 0, 0); layoutDetalle.Controls.Add(layoutCampos, 0, 1); layoutDetalle.Controls.Add(panelAcciones, 0, 2); lblFormulario.AutoSize = true; lblFormulario.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold); lblFormulario.ForeColor = Color.FromArgb(30, 41, 59); lblFormulario.Text = "Nueva membresia";
            layoutCampos.ColumnCount = 2; layoutCampos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F)); layoutCampos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F)); layoutCampos.Dock = DockStyle.Top; layoutCampos.RowCount = 4; layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F)); layoutCampos.Controls.Add(lblSocio, 0, 0); layoutCampos.Controls.Add(socio, 1, 0); layoutCampos.Controls.Add(lblPlan, 0, 1); layoutCampos.Controls.Add(plan, 1, 1); layoutCampos.Controls.Add(lblInicio, 0, 2); layoutCampos.Controls.Add(inicio, 1, 2); layoutCampos.Controls.Add(lblVencimiento, 0, 3); layoutCampos.Controls.Add(vencimiento, 1, 3); socio.DropDownStyle = ComboBoxStyle.DropDownList; socio.Dock = DockStyle.Fill; plan.DropDownStyle = ComboBoxStyle.DropDownList; plan.Dock = DockStyle.Fill; inicio.Format = DateTimePickerFormat.Short; inicio.Dock = DockStyle.Fill; vencimiento.Format = DateTimePickerFormat.Short; vencimiento.Dock = DockStyle.Fill;
            panelAcciones.Dock = DockStyle.Fill; panelAcciones.Controls.Add(nuevo); panelAcciones.Controls.Add(crear); panelAcciones.Controls.Add(actualizar); panelAcciones.Controls.Add(habilitar); panelAcciones.Controls.Add(deshabilitar); panelAcciones.Controls.Add(generarCuota);
            panelEncabezado.Location = new Point(0, 0); panelEncabezado.Name = "panelEncabezado"; panelEncabezado.Size = new Size(1100, 80); panelEncabezado.TabIndex = 0; lblTitulo.Name = "lblTitulo"; lblTitulo.Size = new Size(171, 32); lblTitulo.TabIndex = 0; lblDescripcion.Name = "lblDescripcion"; lblDescripcion.Size = new Size(317, 17); lblDescripcion.TabIndex = 1; btnVolver.Name = "btnVolver"; btnVolver.TabIndex = 2;
            barraAcciones.BackColor = Color.White; barraAcciones.Dock = DockStyle.Top; barraAcciones.Location = new Point(0, 80); barraAcciones.Name = "barraAcciones"; barraAcciones.Padding = new Padding(16, 8, 16, 8); barraAcciones.Size = new Size(1100, 52); barraAcciones.TabIndex = 1; barraAcciones.WrapContents = false;
            lblEstado.Location = new Point(0, 648); lblEstado.Name = "lblEstado"; lblEstado.Size = new Size(1100, 32); lblEstado.TabIndex = 3; panelContenido.Location = new Point(0, 132); panelContenido.Name = "panelContenido"; panelContenido.Size = new Size(1100, 516); panelContenido.TabIndex = 2; layoutContenido.Location = new Point(12, 12); layoutContenido.Name = "layoutContenido"; layoutContenido.RowCount = 1; layoutContenido.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); layoutContenido.Size = new Size(1076, 492); layoutContenido.TabIndex = 0;
            panelListado.Name = "panelListado"; panelListado.TabIndex = 0; lblListado.Name = "lblListado"; lblListado.Size = new Size(91, 20); lblListado.TabIndex = 0; lblAyuda.Name = "lblAyuda"; lblAyuda.Size = new Size(178, 17); lblAyuda.TabIndex = 1; buscador.Name = "buscador"; buscador.TabIndex = 2;
            tabla.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right; tabla.Dock = DockStyle.None; tabla.Location = new Point(16, 106); tabla.Name = "tabla"; tabla.Size = new Size(577, 368); tabla.TabIndex = 3; colId.Width = 50; colSocio.Width = 135; colDni.Width = 85; colPlan.Width = 90; colInicio.Width = 85; colVencimiento.Width = 95; colEstado.Width = 100;
            panelDetalle.Name = "panelDetalle"; panelDetalle.TabIndex = 1; layoutDetalle.Name = "layoutDetalle"; layoutDetalle.TabIndex = 0; lblFormulario.Name = "lblFormulario"; lblFormulario.Size = new Size(160, 21); lblFormulario.TabIndex = 0; layoutCampos.Name = "layoutCampos"; layoutCampos.Size = new Size(414, 176); layoutCampos.TabIndex = 1; panelAcciones.Name = "panelAcciones"; panelAcciones.TabIndex = 2;
            lblSocio.Anchor = AnchorStyles.Left; lblSocio.AutoSize = true; lblSocio.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblSocio.ForeColor = Color.FromArgb(51, 65, 85); lblSocio.Name = "lblSocio"; lblSocio.Text = "Socio:"; lblPlan.Anchor = AnchorStyles.Left; lblPlan.AutoSize = true; lblPlan.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblPlan.ForeColor = Color.FromArgb(51, 65, 85); lblPlan.Name = "lblPlan"; lblPlan.Text = "Plan:"; lblInicio.Anchor = AnchorStyles.Left; lblInicio.AutoSize = true; lblInicio.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblInicio.ForeColor = Color.FromArgb(51, 65, 85); lblInicio.Name = "lblInicio"; lblInicio.Text = "Inicio:"; lblVencimiento.Anchor = AnchorStyles.Left; lblVencimiento.AutoSize = true; lblVencimiento.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblVencimiento.ForeColor = Color.FromArgb(51, 65, 85); lblVencimiento.Name = "lblVencimiento"; lblVencimiento.Text = "Vencimiento:";
            socio.Margin = new Padding(0, 4, 0, 4); socio.Name = "socio"; plan.Margin = new Padding(0, 4, 0, 4); plan.Name = "plan"; inicio.Margin = new Padding(0, 4, 0, 4); inicio.Name = "inicio"; vencimiento.Margin = new Padding(0, 4, 0, 4); vencimiento.Name = "vencimiento";
            nuevo.BackColor = Color.FromArgb(5, 150, 105); nuevo.FlatAppearance.BorderSize = 0; nuevo.FlatStyle = FlatStyle.Flat; nuevo.ForeColor = Color.White; nuevo.Location = new Point(0, 2); nuevo.Name = "nuevo"; nuevo.Size = new Size(100, 32); nuevo.Text = "+ Nueva"; nuevo.UseVisualStyleBackColor = false; crear.BackColor = Color.FromArgb(5, 150, 105); crear.FlatAppearance.BorderSize = 0; crear.FlatStyle = FlatStyle.Flat; crear.ForeColor = Color.White; crear.Location = new Point(0, 42); crear.Name = "crear"; crear.Size = new Size(100, 32); crear.Text = "Crear"; crear.UseVisualStyleBackColor = false; actualizar.BackColor = Color.FromArgb(226, 232, 240); actualizar.FlatAppearance.BorderSize = 0; actualizar.FlatStyle = FlatStyle.Flat; actualizar.ForeColor = Color.FromArgb(30, 41, 59); actualizar.Location = new Point(104, 42); actualizar.Name = "actualizar"; actualizar.Size = new Size(100, 32); actualizar.Text = "Actualizar"; actualizar.UseVisualStyleBackColor = false; habilitar.BackColor = Color.FromArgb(226, 232, 240); habilitar.FlatAppearance.BorderSize = 0; habilitar.FlatStyle = FlatStyle.Flat; habilitar.ForeColor = Color.FromArgb(30, 41, 59); habilitar.Location = new Point(0, 82); habilitar.Name = "habilitar"; habilitar.Size = new Size(100, 32); habilitar.Text = "Habilitar"; habilitar.UseVisualStyleBackColor = false; deshabilitar.BackColor = Color.FromArgb(254, 242, 242); deshabilitar.FlatAppearance.BorderSize = 0; deshabilitar.FlatStyle = FlatStyle.Flat; deshabilitar.ForeColor = Color.FromArgb(185, 28, 28); deshabilitar.Location = new Point(104, 82); deshabilitar.Name = "deshabilitar"; deshabilitar.Size = new Size(100, 32); deshabilitar.Text = "Deshabilitar"; deshabilitar.UseVisualStyleBackColor = false; generarCuota.BackColor = Color.FromArgb(226, 232, 240); generarCuota.FlatAppearance.BorderSize = 0; generarCuota.FlatStyle = FlatStyle.Flat; generarCuota.ForeColor = Color.FromArgb(30, 41, 59); generarCuota.Location = new Point(0, 122); generarCuota.Name = "generarCuota"; generarCuota.Size = new Size(100, 32); generarCuota.Text = "Generar cuota"; generarCuota.UseVisualStyleBackColor = false;
            Controls.Add(panelContenido); Controls.Add(lblEstado); Controls.Add(barraAcciones); Controls.Add(panelEncabezado); AutoScaleMode = AutoScaleMode.Font; BackColor = Color.FromArgb(241, 245, 249); ClientSize = new Size(1100, 680); Font = new Font("Segoe UI", 9.5F); MinimumSize = new Size(760, 540); Name = "GestionMembresiasForm"; StartPosition = FormStartPosition.CenterParent; Text = "SysGym | Membresias"; nuevo.Click += NuevaMembresia; crear.Click += Crear; actualizar.Click += Actualizar; habilitar.Click += Habilitar; deshabilitar.Click += Deshabilitar; generarCuota.Click += GenerarCuota;
            panelEncabezado.ResumeLayout(false); panelEncabezado.PerformLayout(); panelContenido.ResumeLayout(false); layoutContenido.ResumeLayout(false); panelListado.ResumeLayout(false); panelListado.PerformLayout(); ((ISupportInitialize)(tabla)).EndInit(); panelDetalle.ResumeLayout(false); layoutDetalle.ResumeLayout(false); layoutDetalle.PerformLayout(); layoutCampos.ResumeLayout(false); layoutCampos.PerformLayout(); panelAcciones.ResumeLayout(false); ResumeLayout(false);
        }

    }
}
