using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Recepcionista
{
    partial class GestionAsignacionesFormulario
    {
        private IContainer components;
        private Panel panelEncabezado; private Label lblTitulo; private Label lblDescripcion; private Button btnVolver;
        private Panel barraAcciones; private Label lblBuscar; private TextBox buscador; private Label lblEstadoFiltro; private ComboBox filtroEstado; private Button actualizar; private Label lblEstado;
        private SplitContainer splitContenido; private Panel panelListado; private Label lblListadoTitulo; private DataGridView tabla; private DataGridViewTextBoxColumn colId; private DataGridViewTextBoxColumn colSocio; private DataGridViewTextBoxColumn colPlan; private DataGridViewTextBoxColumn colEntrenador; private DataGridViewTextBoxColumn colEstado;
        private Panel panelDetalle; private GroupBox grupoFicha; private Label lblDetalleTitulo; private TableLayoutPanel tablaFicha;
        private Label lblSocio; private Label lblSocioValor; private Label lblDni; private Label lblDniValor; private Label lblPlan; private Label lblPlanValor; private Label lblVencimiento; private Label lblVencimientoValor; private Label lblEstadoMembresia; private Label lblEstadoMembresiaValor; private Label lblEntrenadorActual; private Label lblEntrenadorActualValor; private Label lblNuevoEntrenador; private ComboBox entrenador;
        private FlowLayoutPanel accionesFicha; private Button asignar; private Button cambiar; private Button darDeBaja;

        protected override void Dispose(bool liberarRecursos) { if (liberarRecursos && components != null) components.Dispose(); base.Dispose(liberarRecursos); }

        private void InitializeComponent()
        {
            components = new Container();
            panelEncabezado = new Panel(); lblTitulo = new Label(); lblDescripcion = new Label(); btnVolver = new Button(); barraAcciones = new Panel(); lblBuscar = new Label(); buscador = new TextBox(); lblEstadoFiltro = new Label(); filtroEstado = new ComboBox(); actualizar = new Button(); lblEstado = new Label(); splitContenido = new SplitContainer(); panelListado = new Panel(); lblListadoTitulo = new Label(); tabla = new DataGridView(); colId = new DataGridViewTextBoxColumn(); colSocio = new DataGridViewTextBoxColumn(); colPlan = new DataGridViewTextBoxColumn(); colEntrenador = new DataGridViewTextBoxColumn(); colEstado = new DataGridViewTextBoxColumn(); panelDetalle = new Panel(); grupoFicha = new GroupBox(); lblDetalleTitulo = new Label(); tablaFicha = new TableLayoutPanel(); lblSocio = new Label(); lblSocioValor = new Label(); lblDni = new Label(); lblDniValor = new Label(); lblPlan = new Label(); lblPlanValor = new Label(); lblVencimiento = new Label(); lblVencimientoValor = new Label(); lblEstadoMembresia = new Label(); lblEstadoMembresiaValor = new Label(); lblEntrenadorActual = new Label(); lblEntrenadorActualValor = new Label(); lblNuevoEntrenador = new Label(); entrenador = new ComboBox(); accionesFicha = new FlowLayoutPanel(); asignar = new Button(); cambiar = new Button(); darDeBaja = new Button();
            ((ISupportInitialize)(splitContenido)).BeginInit(); splitContenido.Panel1.SuspendLayout(); splitContenido.Panel2.SuspendLayout(); splitContenido.SuspendLayout(); ((ISupportInitialize)(tabla)).BeginInit(); SuspendLayout();

            panelEncabezado.BackColor = Color.FromArgb(79, 70, 229); panelEncabezado.Dock = DockStyle.Top; panelEncabezado.Height = 70;
            lblTitulo.AutoSize = false; lblTitulo.Font = new Font("Segoe UI", 16F, FontStyle.Bold); lblTitulo.ForeColor = Color.White; lblTitulo.Location = new Point(20, 8); lblTitulo.Size = new Size(700, 30); lblTitulo.Text = "Asignar entrenador";
            lblDescripcion.AutoSize = false; lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240); lblDescripcion.Location = new Point(22, 39); lblDescripcion.Size = new Size(700, 22); lblDescripcion.Text = "Seleccioná una membresía para revisar y gestionar su vinculación";
            btnVolver.Anchor = AnchorStyles.Top | AnchorStyles.Right; btnVolver.BackColor = Color.White; btnVolver.FlatAppearance.BorderSize = 0; btnVolver.FlatStyle = FlatStyle.Flat; btnVolver.Location = new Point(980, 17); btnVolver.Size = new Size(100, 36); btnVolver.Text = "Volver"; btnVolver.UseVisualStyleBackColor = false; btnVolver.Click += btnVolver_Click; panelEncabezado.Controls.Add(btnVolver); panelEncabezado.Controls.Add(lblDescripcion); panelEncabezado.Controls.Add(lblTitulo);

            barraAcciones.BackColor = Color.White; barraAcciones.Dock = DockStyle.Top; barraAcciones.Height = 54;
            lblBuscar.AutoSize = false; lblBuscar.Location = new Point(16, 10); lblBuscar.Size = new Size(52, 28); lblBuscar.Text = "Buscar:"; lblBuscar.TextAlign = ContentAlignment.MiddleLeft;
            buscador.Location = new Point(72, 10); buscador.Size = new Size(250, 27); buscador.BorderStyle = BorderStyle.FixedSingle; buscador.TabIndex = 0; buscador.TextChanged += buscador_TextChanged;
            lblEstadoFiltro.AutoSize = false; lblEstadoFiltro.Location = new Point(340, 10); lblEstadoFiltro.Size = new Size(48, 28); lblEstadoFiltro.Text = "Estado:"; lblEstadoFiltro.TextAlign = ContentAlignment.MiddleLeft;
            filtroEstado.DropDownStyle = ComboBoxStyle.DropDownList; filtroEstado.Items.AddRange(new object[] { "Todos", "Asignados", "Sin asignar" }); filtroEstado.SelectedIndex = 0; filtroEstado.Location = new Point(392, 10); filtroEstado.Size = new Size(130, 28); filtroEstado.TabIndex = 1; filtroEstado.SelectedIndexChanged += filtroEstado_SelectedIndexChanged;
            actualizar.Anchor = AnchorStyles.Top | AnchorStyles.Right; actualizar.BackColor = Color.FromArgb(226, 232, 240); actualizar.FlatAppearance.BorderSize = 0; actualizar.FlatStyle = FlatStyle.Flat; actualizar.Location = new Point(914, 9); actualizar.Size = new Size(166, 34); actualizar.TabIndex = 2; actualizar.Text = "Actualizar listado"; actualizar.UseVisualStyleBackColor = false; actualizar.Click += actualizar_Click;
            barraAcciones.Controls.Add(actualizar); barraAcciones.Controls.Add(filtroEstado); barraAcciones.Controls.Add(lblEstadoFiltro); barraAcciones.Controls.Add(buscador); barraAcciones.Controls.Add(lblBuscar);

            lblEstado.BackColor = Color.FromArgb(226, 232, 240); lblEstado.Dock = DockStyle.Bottom; lblEstado.Height = 28; lblEstado.Padding = new Padding(16, 0, 8, 0); lblEstado.Text = "Listo"; lblEstado.TextAlign = ContentAlignment.MiddleLeft;
            splitContenido.Dock = DockStyle.Fill; splitContenido.FixedPanel = FixedPanel.None; splitContenido.IsSplitterFixed = false; splitContenido.MinimumSize = new Size(900, 420); splitContenido.SplitterWidth = 6; splitContenido.Panel1MinSize = 420; splitContenido.Panel2MinSize = 340; splitContenido.Panel1.BackColor = Color.FromArgb(248, 250, 252); splitContenido.Panel1.Padding = new Padding(16); splitContenido.Panel2.BackColor = Color.FromArgb(248, 250, 252); splitContenido.Panel2.Padding = new Padding(0, 16, 16, 16);
            lblListadoTitulo.Dock = DockStyle.Top; lblListadoTitulo.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold); lblListadoTitulo.ForeColor = Color.FromArgb(30, 41, 59); lblListadoTitulo.Height = 34; lblListadoTitulo.Text = "Membresías y asignación"; lblListadoTitulo.TextAlign = ContentAlignment.MiddleLeft;
            tabla.Dock = DockStyle.Fill; tabla.BackgroundColor = Color.White; tabla.BorderStyle = BorderStyle.FixedSingle; tabla.AllowUserToAddRows = false; tabla.AllowUserToDeleteRows = false; tabla.AllowUserToResizeRows = false; tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; tabla.ColumnHeadersHeight = 34; tabla.MultiSelect = false; tabla.ReadOnly = true; tabla.RowHeadersVisible = false; tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect; tabla.RowTemplate.Height = 30; tabla.TabIndex = 3; tabla.SelectionChanged += tabla_SelectionChanged;
            colId.Name = "colId"; colId.Visible = false; colSocio.HeaderText = "Socio"; colSocio.Name = "colSocio"; colSocio.FillWeight = 31; colSocio.MinimumWidth = 110; colPlan.HeaderText = "Plan"; colPlan.Name = "colPlan"; colPlan.FillWeight = 20; colPlan.MinimumWidth = 80; colEntrenador.HeaderText = "Entrenador actual"; colEntrenador.Name = "colEntrenador"; colEntrenador.FillWeight = 34; colEntrenador.MinimumWidth = 130; colEstado.HeaderText = "Estado"; colEstado.Name = "colEstado"; colEstado.FillWeight = 15; colEstado.MinimumWidth = 80; tabla.Columns.AddRange(new DataGridViewColumn[] { colId, colSocio, colPlan, colEntrenador, colEstado }); panelListado.Dock = DockStyle.Fill; panelListado.Controls.Add(tabla); panelListado.Controls.Add(lblListadoTitulo); splitContenido.Panel1.Controls.Add(panelListado);

            grupoFicha.Dock = DockStyle.Fill; grupoFicha.BackColor = Color.White; grupoFicha.Font = new Font("Segoe UI Semibold", 10F, FontStyle.Bold); grupoFicha.ForeColor = Color.FromArgb(30, 41, 59); grupoFicha.Padding = new Padding(16); grupoFicha.Text = "Vinculación";
            lblDetalleTitulo.Dock = DockStyle.Top; lblDetalleTitulo.Font = new Font("Segoe UI", 12F, FontStyle.Bold); lblDetalleTitulo.ForeColor = Color.FromArgb(79, 70, 229); lblDetalleTitulo.Height = 32; lblDetalleTitulo.Text = "Seleccioná una membresía";
            tablaFicha.ColumnCount = 2; tablaFicha.Dock = DockStyle.Fill; tablaFicha.Padding = new Padding(0, 8, 0, 0); tablaFicha.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 142F)); tablaFicha.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F)); tablaFicha.RowCount = 7; for (var i = 0; i < 7; i++) tablaFicha.RowStyles.Add(new RowStyle(SizeType.Percent, 14.2857F));
            ConfigurarEtiqueta(lblSocio, "Socio"); ConfigurarValor(lblSocioValor, "Seleccioná una membresía"); ConfigurarEtiqueta(lblDni, "DNI"); ConfigurarValor(lblDniValor, "-"); ConfigurarEtiqueta(lblPlan, "Plan"); ConfigurarValor(lblPlanValor, "-"); ConfigurarEtiqueta(lblVencimiento, "Vencimiento"); ConfigurarValor(lblVencimientoValor, "-"); ConfigurarEtiqueta(lblEstadoMembresia, "Estado membresía"); ConfigurarValor(lblEstadoMembresiaValor, "-"); ConfigurarEtiqueta(lblEntrenadorActual, "Entrenador actual"); ConfigurarValor(lblEntrenadorActualValor, "Sin asignar"); ConfigurarEtiqueta(lblNuevoEntrenador, "Nuevo entrenador"); entrenador.Dock = DockStyle.Fill; entrenador.DropDownStyle = ComboBoxStyle.DropDownList; entrenador.Enabled = false; entrenador.TabIndex = 0;
            tablaFicha.Controls.Add(lblSocio, 0, 0); tablaFicha.Controls.Add(lblSocioValor, 1, 0); tablaFicha.Controls.Add(lblDni, 0, 1); tablaFicha.Controls.Add(lblDniValor, 1, 1); tablaFicha.Controls.Add(lblPlan, 0, 2); tablaFicha.Controls.Add(lblPlanValor, 1, 2); tablaFicha.Controls.Add(lblVencimiento, 0, 3); tablaFicha.Controls.Add(lblVencimientoValor, 1, 3); tablaFicha.Controls.Add(lblEstadoMembresia, 0, 4); tablaFicha.Controls.Add(lblEstadoMembresiaValor, 1, 4); tablaFicha.Controls.Add(lblEntrenadorActual, 0, 5); tablaFicha.Controls.Add(lblEntrenadorActualValor, 1, 5); tablaFicha.Controls.Add(lblNuevoEntrenador, 0, 6); tablaFicha.Controls.Add(entrenador, 1, 6);
            accionesFicha.Dock = DockStyle.Bottom; accionesFicha.FlowDirection = FlowDirection.LeftToRight; accionesFicha.Height = 48; accionesFicha.Padding = new Padding(0, 8, 0, 0); accionesFicha.WrapContents = false;
            asignar.BackColor = Color.FromArgb(79, 70, 229); asignar.FlatAppearance.BorderSize = 0; asignar.FlatStyle = FlatStyle.Flat; asignar.ForeColor = Color.White; asignar.Size = new Size(170, 34); asignar.TabIndex = 5; asignar.Text = "Asignar entrenador"; asignar.UseVisualStyleBackColor = false; asignar.Visible = false; asignar.Click += asignar_Click;
            cambiar.BackColor = Color.FromArgb(79, 70, 229); cambiar.FlatAppearance.BorderSize = 0; cambiar.FlatStyle = FlatStyle.Flat; cambiar.ForeColor = Color.White; cambiar.Size = new Size(170, 34); cambiar.TabIndex = 6; cambiar.Text = "Cambiar entrenador"; cambiar.UseVisualStyleBackColor = false; cambiar.Visible = false; cambiar.Click += cambiar_Click;
            darDeBaja.BackColor = Color.FromArgb(254, 242, 242); darDeBaja.FlatAppearance.BorderSize = 0; darDeBaja.FlatStyle = FlatStyle.Flat; darDeBaja.ForeColor = Color.FromArgb(185, 28, 28); darDeBaja.Size = new Size(150, 34); darDeBaja.TabIndex = 7; darDeBaja.Text = "Dar de baja"; darDeBaja.UseVisualStyleBackColor = false; darDeBaja.Visible = false; darDeBaja.Click += darDeBaja_Click; accionesFicha.Controls.Add(asignar); accionesFicha.Controls.Add(cambiar); accionesFicha.Controls.Add(darDeBaja);
            grupoFicha.Controls.Add(tablaFicha); grupoFicha.Controls.Add(accionesFicha); grupoFicha.Controls.Add(lblDetalleTitulo); panelDetalle.Dock = DockStyle.Fill; panelDetalle.Controls.Add(grupoFicha); splitContenido.Panel2.Controls.Add(panelDetalle);
            Controls.Add(splitContenido); Controls.Add(lblEstado); Controls.Add(barraAcciones); Controls.Add(panelEncabezado);
            AutoScaleMode = AutoScaleMode.Font; BackColor = Color.FromArgb(241, 245, 249); ClientSize = new Size(1100, 680); Font = new Font("Segoe UI", 9.5F); MinimumSize = new Size(900, 560); Name = "GestionAsignacionesFormulario"; StartPosition = FormStartPosition.CenterParent; Text = "SysGym | Asignar entrenador"; Load += GestionAsignacionesFormulario_Load;
            splitContenido.Panel2.ResumeLayout(false); splitContenido.Panel1.ResumeLayout(false); ((ISupportInitialize)(splitContenido)).EndInit(); splitContenido.ResumeLayout(false); ((ISupportInitialize)(tabla)).EndInit(); ResumeLayout(false); PerformLayout(); splitContenido.SplitterDistance = 600;
        }

        private static void ConfigurarEtiqueta(Label etiqueta, string texto) { etiqueta.Dock = DockStyle.Fill; etiqueta.Text = texto; etiqueta.TextAlign = ContentAlignment.MiddleLeft; }
        private static void ConfigurarValor(Label etiqueta, string texto) { etiqueta.Dock = DockStyle.Fill; etiqueta.ForeColor = Color.FromArgb(51, 65, 85); etiqueta.Text = texto; etiqueta.TextAlign = ContentAlignment.MiddleLeft; }
    }
}
