using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Recepcionista
{
    partial class GestionPagosFormulario
    {
        private IContainer components;
        private Panel panelEncabezado; private Label lblTitulo; private Label lblDescripcion; private Button btnVolver; private Label lblEstado; private Panel panelContenido; private Panel contenedorContenido; private Panel panelListado; private Label lblListado; private Label lblAyuda; private Panel panelFiltro; private Label lblFiltro; private Panel panelDetalle; private Panel contenedorDetalle; private Label lblFormulario; private Panel contenedorCampos; private Panel panelAcciones; private Label lblMembresia; private Label lblCuota; private Label lblImporte; private Label lblMetodo; private Label lblEstadoPago; private Panel barraAcciones; private DataGridView tabla; private DataGridViewTextBoxColumn colIdCuota; private DataGridViewTextBoxColumn colIdPago; private DataGridViewTextBoxColumn colSocio; private DataGridViewTextBoxColumn colDni; private DataGridViewTextBoxColumn colPlan; private DataGridViewTextBoxColumn colPeriodo; private DataGridViewTextBoxColumn colImporte; private DataGridViewTextBoxColumn colEstadoTabla;
        private TextBox buscador; private ComboBox filtroEstado; private ComboBox membresia; private TextBox cuota; private TextBox importe; private ComboBox metodo; private ComboBox estado; private Button nuevo; private Button registrar; private Button anular; private Button reembolsar;

        protected override void Dispose(bool liberarRecursos) { if (liberarRecursos && components != null) components.Dispose(); base.Dispose(liberarRecursos); }

        private void InitializeComponent()
        {
            components = new Container(); panelEncabezado = new Panel(); lblTitulo = new Label(); lblDescripcion = new Label(); btnVolver = new Button(); barraAcciones = new Panel(); lblEstado = new Label(); panelContenido = new Panel(); contenedorContenido = new Panel(); panelListado = new Panel(); lblListado = new Label(); lblAyuda = new Label(); buscador = new TextBox(); panelFiltro = new Panel(); lblFiltro = new Label(); filtroEstado = new ComboBox(); panelDetalle = new Panel(); contenedorDetalle = new Panel(); lblFormulario = new Label(); contenedorCampos = new Panel(); panelAcciones = new Panel(); lblMembresia = new Label(); lblCuota = new Label(); lblImporte = new Label(); lblMetodo = new Label(); lblEstadoPago = new Label(); membresia = new ComboBox(); cuota = new TextBox(); importe = new TextBox(); metodo = new ComboBox(); estado = new ComboBox(); nuevo = new Button(); registrar = new Button(); anular = new Button(); reembolsar = new Button(); tabla = new DataGridView(); colIdCuota = new DataGridViewTextBoxColumn(); colIdPago = new DataGridViewTextBoxColumn(); colSocio = new DataGridViewTextBoxColumn(); colDni = new DataGridViewTextBoxColumn(); colPlan = new DataGridViewTextBoxColumn(); colPeriodo = new DataGridViewTextBoxColumn(); colImporte = new DataGridViewTextBoxColumn(); colEstadoTabla = new DataGridViewTextBoxColumn(); panelEncabezado.SuspendLayout(); panelContenido.SuspendLayout(); contenedorContenido.SuspendLayout(); panelListado.SuspendLayout(); panelFiltro.SuspendLayout(); ((ISupportInitialize)(tabla)).BeginInit(); panelDetalle.SuspendLayout(); contenedorDetalle.SuspendLayout(); contenedorCampos.SuspendLayout(); panelAcciones.SuspendLayout(); SuspendLayout();
            panelEncabezado.BackColor = Color.FromArgb(5, 150, 105);   panelEncabezado.Controls.Add(lblDescripcion); panelEncabezado.Controls.Add(lblTitulo); panelEncabezado.Controls.Add(btnVolver);  lblTitulo.Font = new Font("Segoe UI", 18F, FontStyle.Bold); lblTitulo.ForeColor = Color.White;  lblTitulo.Text = "Cuotas y pagos";  lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240);  lblDescripcion.Text = "Registro de pagos y consulta de cuotas";  btnVolver.BackColor = Color.White; btnVolver.FlatStyle = FlatStyle.Flat; btnVolver.FlatAppearance.BorderSize = 0; btnVolver.ForeColor = Color.FromArgb(5, 150, 105);   btnVolver.Text = "Volver"; btnVolver.UseVisualStyleBackColor = false;
             lblEstado.BackColor = Color.FromArgb(226, 232, 240);  lblEstado.ForeColor = Color.FromArgb(51, 65, 85);  lblEstado.Padding = new Padding(18, 8, 8, 0); lblEstado.Text = "Listo"; panelContenido.BackColor = Color.FromArgb(248, 250, 252);  panelContenido.Padding = new Padding(12); panelContenido.Controls.Add(contenedorContenido);     contenedorContenido.Controls.Add(panelListado); contenedorContenido.Controls.Add(panelDetalle);
            panelListado.BackColor = Color.White; panelListado.BorderStyle = BorderStyle.FixedSingle;  panelListado.Padding = new Padding(16); panelListado.Controls.Add(tabla); panelListado.Controls.Add(panelFiltro); panelListado.Controls.Add(lblAyuda); panelListado.Controls.Add(lblListado);  lblListado.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold); lblListado.ForeColor = Color.FromArgb(30, 41, 59);  lblListado.Text = "Cuotas";  lblAyuda.ForeColor = Color.FromArgb(100, 116, 139);  lblAyuda.Text = "Busca por socio, DNI o plan";    panelFiltro.Controls.Add(filtroEstado); panelFiltro.Controls.Add(lblFiltro); panelFiltro.Controls.Add(buscador);  lblFiltro.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);  lblFiltro.Text = "Mostrar";  buscador.BorderStyle = BorderStyle.FixedSingle;   filtroEstado.DropDownStyle = ComboBoxStyle.DropDownList;   filtroEstado.Items.AddRange(new object[] { "Todas", "Pendientes", "Pagadas" }); filtroEstado.SelectedIndex = 0;
            tabla.AllowUserToAddRows = false; tabla.AllowUserToDeleteRows = false; tabla.AllowUserToResizeRows = false; tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; tabla.BackgroundColor = Color.White; tabla.BorderStyle = BorderStyle.None; tabla.ColumnHeadersHeight = 38;  tabla.MultiSelect = false; tabla.ReadOnly = true; tabla.RowHeadersVisible = false; tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect; tabla.Columns.AddRange(new DataGridViewColumn[] { colIdCuota, colIdPago, colSocio, colDni, colPlan, colPeriodo, colImporte, colEstadoTabla }); colIdCuota.HeaderText = "IdCuota"; colIdCuota.Name = "colIdCuota"; colIdCuota.Visible = false; colIdPago.HeaderText = "IdPago"; colIdPago.Name = "colIdPago"; colIdPago.Visible = false; colSocio.HeaderText = "Socio"; colSocio.Name = "colSocio"; colDni.HeaderText = "DNI"; colDni.Name = "colDni"; colPlan.HeaderText = "Plan"; colPlan.Name = "colPlan"; colPeriodo.HeaderText = "Periodo"; colPeriodo.Name = "colPeriodo"; colImporte.HeaderText = "Importe"; colImporte.Name = "colImporte"; colEstadoTabla.HeaderText = "Estado"; colEstadoTabla.Name = "colEstadoTabla";
            panelDetalle.BackColor = Color.White; panelDetalle.BorderStyle = BorderStyle.FixedSingle;  panelDetalle.Padding = new Padding(16); panelDetalle.Controls.Add(contenedorDetalle);       contenedorDetalle.Controls.Add(lblFormulario); contenedorDetalle.Controls.Add(contenedorCampos); contenedorDetalle.Controls.Add(panelAcciones);  lblFormulario.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold); lblFormulario.ForeColor = Color.FromArgb(30, 41, 59); lblFormulario.Text = "Nuevo pago";
                      contenedorCampos.Controls.Add(lblMembresia); contenedorCampos.Controls.Add(membresia); contenedorCampos.Controls.Add(lblCuota); contenedorCampos.Controls.Add(cuota); contenedorCampos.Controls.Add(lblImporte); contenedorCampos.Controls.Add(importe); contenedorCampos.Controls.Add(lblMetodo); contenedorCampos.Controls.Add(metodo); contenedorCampos.Controls.Add(lblEstadoPago); contenedorCampos.Controls.Add(estado);  membresia.DropDownStyle = ComboBoxStyle.DropDownList;  cuota.ReadOnly = true; cuota.BackColor = Color.FromArgb(241, 245, 249);  importe.BorderStyle = BorderStyle.FixedSingle;  metodo.DropDownStyle = ComboBoxStyle.DropDownList;  estado.DropDownStyle = ComboBoxStyle.DropDownList; estado.Items.AddRange(new object[] { "Pendiente", "Aprobado", "Rechazado" }); estado.SelectedIndex = 1;
             panelAcciones.Controls.Add(nuevo); panelAcciones.Controls.Add(registrar); panelAcciones.Controls.Add(anular); panelAcciones.Controls.Add(reembolsar);
             panelEncabezado.Name = "panelEncabezado";  panelEncabezado.TabIndex = 0; lblTitulo.Name = "lblTitulo";  lblTitulo.TabIndex = 0; lblDescripcion.Name = "lblDescripcion";  lblDescripcion.TabIndex = 1; btnVolver.Name = "btnVolver"; btnVolver.TabIndex = 2;
            barraAcciones.BackColor = Color.White;   barraAcciones.Name = "barraAcciones"; barraAcciones.Padding = new Padding(16, 8, 16, 8);  barraAcciones.TabIndex = 1; 
             lblEstado.Name = "lblEstado";  lblEstado.TabIndex = 3;  panelContenido.Name = "panelContenido";  panelContenido.TabIndex = 2;  contenedorContenido.Name = "contenedorContenido";    contenedorContenido.TabIndex = 0;
            panelListado.Name = "panelListado"; panelListado.TabIndex = 0; lblListado.Name = "lblListado";  lblListado.TabIndex = 0; lblAyuda.Name = "lblAyuda";  lblAyuda.TabIndex = 1; panelFiltro.Name = "panelFiltro"; panelFiltro.TabIndex = 2; lblFiltro.ForeColor = Color.FromArgb(71, 85, 105); lblFiltro.Name = "lblFiltro"; lblFiltro.TabIndex = 1; buscador.Name = "buscador"; buscador.TabIndex = 0; filtroEstado.Name = "filtroEstado"; filtroEstado.TabIndex = 2;
               tabla.Name = "tabla";  tabla.TabIndex = 3; colIdCuota.Width = 50; colIdPago.Width = 50; colSocio.Width = 125; colDni.Width = 80; colPlan.Width = 90; colPeriodo.Width = 125; colImporte.Width = 90; colEstadoTabla.Width = 85;
            panelDetalle.Name = "panelDetalle"; panelDetalle.TabIndex = 1; contenedorDetalle.Name = "contenedorDetalle"; contenedorDetalle.TabIndex = 0; lblFormulario.Name = "lblFormulario";  lblFormulario.TabIndex = 0; contenedorCampos.Name = "contenedorCampos";  contenedorCampos.TabIndex = 1; panelAcciones.Name = "panelAcciones"; panelAcciones.TabIndex = 2;
              lblMembresia.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblMembresia.ForeColor = Color.FromArgb(51, 65, 85); lblMembresia.Name = "lblMembresia"; lblMembresia.Text = "Membresia:";   lblCuota.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblCuota.ForeColor = Color.FromArgb(51, 65, 85); lblCuota.Name = "lblCuota"; lblCuota.Text = "Cuota:";   lblImporte.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblImporte.ForeColor = Color.FromArgb(51, 65, 85); lblImporte.Name = "lblImporte"; lblImporte.Text = "Importe:";   lblMetodo.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblMetodo.ForeColor = Color.FromArgb(51, 65, 85); lblMetodo.Name = "lblMetodo"; lblMetodo.Text = "Metodo:";   lblEstadoPago.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblEstadoPago.ForeColor = Color.FromArgb(51, 65, 85); lblEstadoPago.Name = "lblEstadoPago"; lblEstadoPago.Text = "Estado:";
            membresia.Margin = new Padding(0, 4, 0, 4); membresia.Name = "membresia"; cuota.BorderStyle = BorderStyle.FixedSingle; cuota.Margin = new Padding(0, 4, 0, 4); cuota.Name = "cuota"; importe.Margin = new Padding(0, 4, 0, 4); importe.Name = "importe"; metodo.Margin = new Padding(0, 4, 0, 4); metodo.Name = "metodo"; estado.Margin = new Padding(0, 4, 0, 4); estado.Name = "estado";
            nuevo.BackColor = Color.FromArgb(5, 150, 105); nuevo.FlatAppearance.BorderSize = 0; nuevo.FlatStyle = FlatStyle.Flat; nuevo.ForeColor = Color.White;  nuevo.Name = "nuevo";  nuevo.Text = "+ Nuevo pago"; nuevo.UseVisualStyleBackColor = false; registrar.BackColor = Color.FromArgb(5, 150, 105); registrar.FlatAppearance.BorderSize = 0; registrar.FlatStyle = FlatStyle.Flat; registrar.ForeColor = Color.White;  registrar.Name = "registrar";  registrar.Text = "Registrar"; registrar.UseVisualStyleBackColor = false; anular.BackColor = Color.FromArgb(254, 242, 242); anular.FlatAppearance.BorderSize = 0; anular.FlatStyle = FlatStyle.Flat; anular.ForeColor = Color.FromArgb(185, 28, 28);  anular.Name = "anular";  anular.Text = "Anular"; anular.UseVisualStyleBackColor = false; reembolsar.BackColor = Color.FromArgb(226, 232, 240); reembolsar.FlatAppearance.BorderSize = 0; reembolsar.FlatStyle = FlatStyle.Flat; reembolsar.ForeColor = Color.FromArgb(30, 41, 59);  reembolsar.Name = "reembolsar";  reembolsar.Text = "Reembolsar"; reembolsar.UseVisualStyleBackColor = false;
            Controls.Add(panelContenido); Controls.Add(lblEstado); Controls.Add(barraAcciones); Controls.Add(panelEncabezado); AutoScaleMode = AutoScaleMode.Font; this.AutoScroll = true; BackColor = Color.FromArgb(241, 245, 249); ClientSize = new Size(1100, 680); Font = new Font("Segoe UI", 9.5F); MinimumSize = new Size(760, 540); this.Name = "GestionPagosFormulario"; StartPosition = FormStartPosition.CenterParent; Text = "SysGym | Cuotas y pagos";    

            this.panelEncabezado.AutoSize = false;
            this.panelEncabezado.Dock = System.Windows.Forms.DockStyle.None;
            this.panelEncabezado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelEncabezado.Location = new System.Drawing.Point(0, 0);
            this.panelEncabezado.Size = new System.Drawing.Size(1100, 80);
            this.lblTitulo.AutoSize = false;
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.None;
            this.lblTitulo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblTitulo.Location = new System.Drawing.Point(22, 10);
            this.lblTitulo.Size = new System.Drawing.Size(185, 38);
            this.lblDescripcion.AutoSize = false;
            this.lblDescripcion.Dock = System.Windows.Forms.DockStyle.None;
            this.lblDescripcion.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblDescripcion.Location = new System.Drawing.Point(24, 47);
            this.lblDescripcion.Size = new System.Drawing.Size(230, 22);
            this.btnVolver.AutoSize = false;
            this.btnVolver.Dock = System.Windows.Forms.DockStyle.None;
            this.btnVolver.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnVolver.Location = new System.Drawing.Point(930, 22);
            this.btnVolver.Size = new System.Drawing.Size(92, 34);
            this.lblEstado.AutoSize = false;
            this.lblEstado.Dock = System.Windows.Forms.DockStyle.None;
            this.lblEstado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblEstado.Location = new System.Drawing.Point(0, 648);
            this.lblEstado.Size = new System.Drawing.Size(1100, 32);
            this.panelContenido.AutoSize = false;
            this.panelContenido.Dock = System.Windows.Forms.DockStyle.None;
            this.panelContenido.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelContenido.Location = new System.Drawing.Point(0, 132);
            this.panelContenido.Size = new System.Drawing.Size(1100, 516);
            this.contenedorContenido.AutoSize = false;
            this.contenedorContenido.Dock = System.Windows.Forms.DockStyle.None;
            this.contenedorContenido.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.contenedorContenido.Location = new System.Drawing.Point(12, 12);
            this.contenedorContenido.Size = new System.Drawing.Size(1076, 492);
            this.panelListado.AutoSize = false;
            this.panelListado.Dock = System.Windows.Forms.DockStyle.None;
            this.panelListado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelListado.Location = new System.Drawing.Point(3, 3);
            this.panelListado.Size = new System.Drawing.Size(607, 486);
            this.lblListado.AutoSize = false;
            this.lblListado.Dock = System.Windows.Forms.DockStyle.None;
            this.lblListado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblListado.Location = new System.Drawing.Point(16, 14);
            this.lblListado.Size = new System.Drawing.Size(52, 25);
            this.lblAyuda.AutoSize = false;
            this.lblAyuda.Dock = System.Windows.Forms.DockStyle.None;
            this.lblAyuda.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblAyuda.Location = new System.Drawing.Point(16, 42);
            this.lblAyuda.Size = new System.Drawing.Size(163, 22);
            this.panelFiltro.AutoSize = false;
            this.panelFiltro.Dock = System.Windows.Forms.DockStyle.None;
            this.panelFiltro.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelFiltro.Location = new System.Drawing.Point(16, 68);
            this.panelFiltro.Size = new System.Drawing.Size(573, 54);
            this.lblFiltro.AutoSize = false;
            this.lblFiltro.Dock = System.Windows.Forms.DockStyle.None;
            this.lblFiltro.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblFiltro.Location = new System.Drawing.Point(310, 7);
            this.lblFiltro.Size = new System.Drawing.Size(49, 21);
            this.panelDetalle.AutoSize = false;
            this.panelDetalle.Dock = System.Windows.Forms.DockStyle.None;
            this.panelDetalle.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelDetalle.Location = new System.Drawing.Point(616, 3);
            this.panelDetalle.Size = new System.Drawing.Size(457, 486);
            this.contenedorDetalle.AutoSize = false;
            this.contenedorDetalle.Dock = System.Windows.Forms.DockStyle.None;
            this.contenedorDetalle.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.contenedorDetalle.Location = new System.Drawing.Point(16, 16);
            this.contenedorDetalle.Size = new System.Drawing.Size(423, 452);
            this.lblFormulario.AutoSize = false;
            this.lblFormulario.Dock = System.Windows.Forms.DockStyle.None;
            this.lblFormulario.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblFormulario.Location = new System.Drawing.Point(3, 0);
            this.lblFormulario.Size = new System.Drawing.Size(98, 27);
            this.contenedorCampos.AutoSize = false;
            this.contenedorCampos.Dock = System.Windows.Forms.DockStyle.None;
            this.contenedorCampos.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.contenedorCampos.Location = new System.Drawing.Point(3, 37);
            this.contenedorCampos.Size = new System.Drawing.Size(417, 210);
            this.panelAcciones.AutoSize = false;
            this.panelAcciones.Dock = System.Windows.Forms.DockStyle.None;
            this.panelAcciones.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.panelAcciones.Location = new System.Drawing.Point(3, 331);
            this.panelAcciones.Size = new System.Drawing.Size(417, 118);
            this.lblMembresia.AutoSize = false;
            this.lblMembresia.Dock = System.Windows.Forms.DockStyle.None;
            this.lblMembresia.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblMembresia.Location = new System.Drawing.Point(3, 10);
            this.lblMembresia.Size = new System.Drawing.Size(70, 21);
            this.lblCuota.AutoSize = false;
            this.lblCuota.Dock = System.Windows.Forms.DockStyle.None;
            this.lblCuota.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblCuota.Location = new System.Drawing.Point(3, 52);
            this.lblCuota.Size = new System.Drawing.Size(41, 21);
            this.lblImporte.AutoSize = false;
            this.lblImporte.Dock = System.Windows.Forms.DockStyle.None;
            this.lblImporte.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblImporte.Location = new System.Drawing.Point(3, 94);
            this.lblImporte.Size = new System.Drawing.Size(52, 21);
            this.lblMetodo.AutoSize = false;
            this.lblMetodo.Dock = System.Windows.Forms.DockStyle.None;
            this.lblMetodo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblMetodo.Location = new System.Drawing.Point(3, 136);
            this.lblMetodo.Size = new System.Drawing.Size(52, 21);
            this.lblEstadoPago.AutoSize = false;
            this.lblEstadoPago.Dock = System.Windows.Forms.DockStyle.None;
            this.lblEstadoPago.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblEstadoPago.Location = new System.Drawing.Point(3, 178);
            this.lblEstadoPago.Size = new System.Drawing.Size(45, 21);
            this.barraAcciones.AutoSize = false;
            this.barraAcciones.Dock = System.Windows.Forms.DockStyle.None;
            this.barraAcciones.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.barraAcciones.Location = new System.Drawing.Point(0, 80);
            this.barraAcciones.Size = new System.Drawing.Size(1100, 52);
            this.tabla.AutoSize = false;
            this.tabla.Dock = System.Windows.Forms.DockStyle.None;
            this.tabla.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.tabla.Location = new System.Drawing.Point(16, 128);
            this.tabla.Size = new System.Drawing.Size(573, 340);
            this.buscador.AutoSize = false;
            this.buscador.Dock = System.Windows.Forms.DockStyle.None;
            this.buscador.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.buscador.Location = new System.Drawing.Point(0, 22);
            this.buscador.Size = new System.Drawing.Size(298, 24);
            this.filtroEstado.AutoSize = false;
            this.filtroEstado.Dock = System.Windows.Forms.DockStyle.None;
            this.filtroEstado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.filtroEstado.Location = new System.Drawing.Point(310, 22);
            this.filtroEstado.Size = new System.Drawing.Size(190, 25);
            this.membresia.AutoSize = false;
            this.membresia.Dock = System.Windows.Forms.DockStyle.None;
            this.membresia.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.membresia.Location = new System.Drawing.Point(175, 4);
            this.membresia.Size = new System.Drawing.Size(242, 25);
            this.cuota.AutoSize = false;
            this.cuota.Dock = System.Windows.Forms.DockStyle.None;
            this.cuota.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.cuota.Location = new System.Drawing.Point(175, 46);
            this.cuota.Size = new System.Drawing.Size(242, 24);
            this.importe.AutoSize = false;
            this.importe.Dock = System.Windows.Forms.DockStyle.None;
            this.importe.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.importe.Location = new System.Drawing.Point(175, 88);
            this.importe.Size = new System.Drawing.Size(242, 24);
            this.metodo.AutoSize = false;
            this.metodo.Dock = System.Windows.Forms.DockStyle.None;
            this.metodo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.metodo.Location = new System.Drawing.Point(175, 130);
            this.metodo.Size = new System.Drawing.Size(242, 25);
            this.estado.AutoSize = false;
            this.estado.Dock = System.Windows.Forms.DockStyle.None;
            this.estado.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.estado.Location = new System.Drawing.Point(175, 172);
            this.estado.Size = new System.Drawing.Size(242, 25);
            this.nuevo.AutoSize = false;
            this.nuevo.Dock = System.Windows.Forms.DockStyle.None;
            this.nuevo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.nuevo.Location = new System.Drawing.Point(0, 2);
            this.nuevo.Size = new System.Drawing.Size(100, 32);
            this.registrar.AutoSize = false;
            this.registrar.Dock = System.Windows.Forms.DockStyle.None;
            this.registrar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.registrar.Location = new System.Drawing.Point(0, 44);
            this.registrar.Size = new System.Drawing.Size(100, 32);
            this.anular.AutoSize = false;
            this.anular.Dock = System.Windows.Forms.DockStyle.None;
            this.anular.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.anular.Location = new System.Drawing.Point(104, 44);
            this.anular.Size = new System.Drawing.Size(100, 32);
            this.reembolsar.AutoSize = false;
            this.reembolsar.Dock = System.Windows.Forms.DockStyle.None;
            this.reembolsar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.reembolsar.Location = new System.Drawing.Point(0, 84);
            this.reembolsar.Size = new System.Drawing.Size(100, 32);
            panelEncabezado.ResumeLayout(false); panelEncabezado.PerformLayout(); panelContenido.ResumeLayout(false); contenedorContenido.ResumeLayout(false); panelListado.ResumeLayout(false); panelListado.PerformLayout(); panelFiltro.ResumeLayout(false); panelFiltro.PerformLayout(); ((ISupportInitialize)(tabla)).EndInit(); panelDetalle.ResumeLayout(false); contenedorDetalle.ResumeLayout(false); contenedorDetalle.PerformLayout(); contenedorCampos.ResumeLayout(false); contenedorCampos.PerformLayout(); panelAcciones.ResumeLayout(false); ResumeLayout(false);

            this.Load += new System.EventHandler(this.GestionPagosFormulario_Load);
            this.btnVolver.Click += new System.EventHandler(this.btnVolver_Click);
            this.membresia.SelectedIndexChanged += new System.EventHandler(this.membresia_SelectedIndexChanged);
            this.tabla.SelectionChanged += new System.EventHandler(this.tabla_SelectionChanged);
            this.buscador.TextChanged += new System.EventHandler(this.buscador_TextChanged);
            this.filtroEstado.SelectedIndexChanged += new System.EventHandler(this.filtroEstado_SelectedIndexChanged);
            this.nuevo.Click += new System.EventHandler(this.nuevo_Click);
            this.registrar.Click += new System.EventHandler(this.registrar_Click);
            this.anular.Click += new System.EventHandler(this.anular_Click);
            this.reembolsar.Click += new System.EventHandler(this.reembolsar_Click);
                    this.importe.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.importe_KeyPress);
        }

    }
}
