namespace exxen2._0.capaVisual.Administrador
{
    partial class AnalisisFormulario
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel disposicion;
        private System.Windows.Forms.Panel encabezado;
        private System.Windows.Forms.Label titulo;
        private System.Windows.Forms.Label lblDesde;
        private System.Windows.Forms.Label lblHasta;
        private System.Windows.Forms.DateTimePicker desde;
        private System.Windows.Forms.DateTimePicker hasta;
        private System.Windows.Forms.Button aplicar;
        private System.Windows.Forms.Button exportarReporte;
        private System.Windows.Forms.TableLayoutPanel indicadores;
        private System.Windows.Forms.Label lblIngresosTitulo;
        private System.Windows.Forms.Label lblPagosTitulo;
        private System.Windows.Forms.Label lblActivosTitulo;
        private System.Windows.Forms.Label lblDeudaTitulo;
        private System.Windows.Forms.Label lblIngresos;
        private System.Windows.Forms.Label lblPagos;
        private System.Windows.Forms.Label lblActivos;
        private System.Windows.Forms.Label lblDeuda;
        private System.Windows.Forms.Label lblComparacion;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.Label lblPorcentajeActivos;
        private System.Windows.Forms.TabControl categorias;
        private System.Windows.Forms.TabPage tabResumen;
        private System.Windows.Forms.TabPage tabFinanzas;
        private System.Windows.Forms.TabPage tabSocios;
        private System.Windows.Forms.TabPage tabPlanes;
        private System.Windows.Forms.TabPage tabEntrenadores;
        private System.Windows.Forms.TableLayoutPanel disposicionSocios;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartIngresos;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartMetodos;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartAltas;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartActivos;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartDeuda;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartPlanes;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartEntrenadores;
        private System.Windows.Forms.TableLayoutPanel disposicionPlanes;
        private System.Windows.Forms.TabPage tabRutinas;
        private System.Windows.Forms.TabPage tabEjercicios;
        private System.Windows.Forms.TabPage tabComparar;
        private System.Windows.Forms.TabPage tabSocio;
        private System.Windows.Forms.Label lblSinRutina;
        private System.Windows.Forms.TableLayoutPanel tablaEjercicios;
        private System.Windows.Forms.Label lblEjerciciosSinUso;
        private System.Windows.Forms.DataGridView gridEjerciciosSinUso;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEjercicioNombre;
        private System.Windows.Forms.DataGridViewTextBoxColumn colEjercicioDescripcion;
        private System.Windows.Forms.TableLayoutPanel tablaComparar;
        private System.Windows.Forms.Panel filtrosComparar;
        private System.Windows.Forms.Label lblPeriodoA;
        private System.Windows.Forms.Label lblPeriodoB;
        private System.Windows.Forms.Label lblHastaA;
        private System.Windows.Forms.Label lblHastaB;
        private System.Windows.Forms.DateTimePicker desdeA;
        private System.Windows.Forms.DateTimePicker hastaA;
        private System.Windows.Forms.DateTimePicker desdeB;
        private System.Windows.Forms.DateTimePicker hastaB;
        private System.Windows.Forms.Button comparar;
        private System.Windows.Forms.TableLayoutPanel tablaChartsComparar;
        private System.Windows.Forms.DataGridView gridComparacion;
        private System.Windows.Forms.DataGridViewTextBoxColumn colIndicador;
        private System.Windows.Forms.DataGridViewTextBoxColumn colValorA;
        private System.Windows.Forms.DataGridViewTextBoxColumn colValorB;
        private System.Windows.Forms.DataGridViewTextBoxColumn colVariacion;
        private System.Windows.Forms.Label lblCompararEstado;
        private System.Windows.Forms.TableLayoutPanel tablaSocio;
        private System.Windows.Forms.Panel barraSocio;
        private System.Windows.Forms.Label lblBuscarSocio;
        private System.Windows.Forms.TextBox buscarSocio;
        private System.Windows.Forms.Button btnBuscarSocio;
        private System.Windows.Forms.ComboBox selectorSocio;
        private System.Windows.Forms.Label lblBusquedaEstado;
        private System.Windows.Forms.TableLayoutPanel tablaDetalleSocio;
        private System.Windows.Forms.DataGridView gridSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colDatoSocio;
        private System.Windows.Forms.DataGridViewTextBoxColumn colValorSocio;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartIngresosPlan;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartRutinas;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartEjercicios;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartCompararIngresos;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartCompararCantidades;
        private System.Windows.Forms.DataVisualization.Charting.Chart chartSocio;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.disposicion = new System.Windows.Forms.TableLayoutPanel();
            this.encabezado = new System.Windows.Forms.Panel();
            this.titulo = new System.Windows.Forms.Label();
            this.lblDesde = new System.Windows.Forms.Label();
            this.lblHasta = new System.Windows.Forms.Label();
            this.desde = new System.Windows.Forms.DateTimePicker();
            this.hasta = new System.Windows.Forms.DateTimePicker();
            this.aplicar = new System.Windows.Forms.Button();
            this.exportarReporte = new System.Windows.Forms.Button();
            this.indicadores = new System.Windows.Forms.TableLayoutPanel();
            this.lblIngresosTitulo = new System.Windows.Forms.Label();
            this.lblPagosTitulo = new System.Windows.Forms.Label();
            this.lblActivosTitulo = new System.Windows.Forms.Label();
            this.lblDeudaTitulo = new System.Windows.Forms.Label();
            this.lblIngresos = new System.Windows.Forms.Label();
            this.lblPagos = new System.Windows.Forms.Label();
            this.lblActivos = new System.Windows.Forms.Label();
            this.lblDeuda = new System.Windows.Forms.Label();
            this.lblComparacion = new System.Windows.Forms.Label();
            this.lblEstado = new System.Windows.Forms.Label();
            this.lblPorcentajeActivos = new System.Windows.Forms.Label();
            this.categorias = new System.Windows.Forms.TabControl();
            this.tabResumen = new System.Windows.Forms.TabPage();
            this.tabFinanzas = new System.Windows.Forms.TabPage();
            this.tabSocios = new System.Windows.Forms.TabPage();
            this.tabPlanes = new System.Windows.Forms.TabPage();
            this.tabEntrenadores = new System.Windows.Forms.TabPage();
            this.disposicionSocios = new System.Windows.Forms.TableLayoutPanel();
            this.chartIngresos = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartMetodos = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartAltas = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartActivos = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartDeuda = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartPlanes = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartEntrenadores = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.disposicionPlanes = new System.Windows.Forms.TableLayoutPanel();
            this.tabRutinas = new System.Windows.Forms.TabPage();
            this.tabEjercicios = new System.Windows.Forms.TabPage();
            this.tabComparar = new System.Windows.Forms.TabPage();
            this.tabSocio = new System.Windows.Forms.TabPage();
            this.lblSinRutina = new System.Windows.Forms.Label();
            this.tablaEjercicios = new System.Windows.Forms.TableLayoutPanel();
            this.lblEjerciciosSinUso = new System.Windows.Forms.Label();
            this.gridEjerciciosSinUso = new System.Windows.Forms.DataGridView();
            this.colEjercicioNombre = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colEjercicioDescripcion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tablaComparar = new System.Windows.Forms.TableLayoutPanel();
            this.filtrosComparar = new System.Windows.Forms.Panel();
            this.lblPeriodoA = new System.Windows.Forms.Label();
            this.lblPeriodoB = new System.Windows.Forms.Label();
            this.lblHastaA = new System.Windows.Forms.Label();
            this.lblHastaB = new System.Windows.Forms.Label();
            this.desdeA = new System.Windows.Forms.DateTimePicker();
            this.hastaA = new System.Windows.Forms.DateTimePicker();
            this.desdeB = new System.Windows.Forms.DateTimePicker();
            this.hastaB = new System.Windows.Forms.DateTimePicker();
            this.comparar = new System.Windows.Forms.Button();
            this.tablaChartsComparar = new System.Windows.Forms.TableLayoutPanel();
            this.gridComparacion = new System.Windows.Forms.DataGridView();
            this.colIndicador = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colValorA = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colValorB = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colVariacion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.lblCompararEstado = new System.Windows.Forms.Label();
            this.tablaSocio = new System.Windows.Forms.TableLayoutPanel();
            this.barraSocio = new System.Windows.Forms.Panel();
            this.lblBuscarSocio = new System.Windows.Forms.Label();
            this.buscarSocio = new System.Windows.Forms.TextBox();
            this.btnBuscarSocio = new System.Windows.Forms.Button();
            this.selectorSocio = new System.Windows.Forms.ComboBox();
            this.lblBusquedaEstado = new System.Windows.Forms.Label();
            this.tablaDetalleSocio = new System.Windows.Forms.TableLayoutPanel();
            this.gridSocio = new System.Windows.Forms.DataGridView();
            this.colDatoSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colValorSocio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.chartIngresosPlan = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartRutinas = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartEjercicios = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartCompararIngresos = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartCompararCantidades = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.chartSocio = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.disposicion.SuspendLayout();
            this.disposicionPlanes.SuspendLayout();
            this.tabRutinas.SuspendLayout();
            this.tabEjercicios.SuspendLayout();
            this.tabComparar.SuspendLayout();
            this.tabSocio.SuspendLayout();
            this.tablaEjercicios.SuspendLayout();
            this.tablaComparar.SuspendLayout();
            this.filtrosComparar.SuspendLayout();
            this.tablaChartsComparar.SuspendLayout();
            this.tablaSocio.SuspendLayout();
            this.barraSocio.SuspendLayout();
            this.tablaDetalleSocio.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chartIngresosPlan)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartRutinas)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartEjercicios)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartCompararIngresos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartCompararCantidades)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartSocio)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridEjerciciosSinUso)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridComparacion)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridSocio)).BeginInit();
            this.encabezado.SuspendLayout();
            this.indicadores.SuspendLayout();
            this.categorias.SuspendLayout();
            this.tabResumen.SuspendLayout();
            this.tabFinanzas.SuspendLayout();
            this.tabSocios.SuspendLayout();
            this.tabPlanes.SuspendLayout();
            this.tabEntrenadores.SuspendLayout();
            this.disposicionSocios.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chartIngresos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartMetodos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartAltas)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartActivos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartDeuda)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartPlanes)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartEntrenadores)).BeginInit();
            this.SuspendLayout();
            // disposicion
            this.disposicion.ColumnCount = 1;
            this.disposicion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.disposicion.Controls.Add(this.encabezado, 0, 0);
            this.disposicion.Controls.Add(this.indicadores, 0, 1);
            this.disposicion.Controls.Add(this.lblComparacion, 0, 2);
            this.disposicion.Controls.Add(this.lblEstado, 0, 4);
            this.disposicion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Location = new System.Drawing.Point(0, 0);
            this.disposicion.Size = new System.Drawing.Size(1080, 700);
            this.disposicion.Name = "disposicion";
            this.disposicion.RowCount = 5;
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 104F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 78F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 30F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 34F));
            // encabezado
            this.encabezado.BackColor = System.Drawing.Color.White;
            this.encabezado.Controls.Add(this.titulo);
            this.encabezado.Controls.Add(this.lblDesde);
            this.encabezado.Controls.Add(this.desde);
            this.encabezado.Controls.Add(this.lblHasta);
            this.encabezado.Controls.Add(this.hasta);
            this.encabezado.Controls.Add(this.aplicar);
            this.encabezado.Controls.Add(this.exportarReporte);
            this.encabezado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.encabezado.Size = new System.Drawing.Size(1074, 98);
            this.encabezado.Name = "encabezado";
            this.titulo.AutoSize = true;
            this.titulo.Font = new System.Drawing.Font("Segoe UI Semibold", 15F, System.Drawing.FontStyle.Bold);
            this.titulo.Location = new System.Drawing.Point(18, 8);
            this.titulo.Name = "titulo";
            this.titulo.Text = "Análisis del gimnasio";
            this.lblDesde.AutoSize = true;
            this.lblDesde.Location = new System.Drawing.Point(20, 62);
            this.lblDesde.Name = "lblDesde";
            this.lblDesde.Text = "Desde:";
            this.desde.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.desde.Location = new System.Drawing.Point(82, 59);
            this.desde.Name = "desde";
            this.desde.Size = new System.Drawing.Size(130, 24);
            this.lblHasta.AutoSize = true;
            this.lblHasta.Location = new System.Drawing.Point(226, 62);
            this.lblHasta.Name = "lblHasta";
            this.lblHasta.Text = "Hasta:";
            this.hasta.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.hasta.Location = new System.Drawing.Point(282, 59);
            this.hasta.Name = "hasta";
            this.hasta.Size = new System.Drawing.Size(130, 24);
            this.aplicar.Location = new System.Drawing.Point(430, 56);
            this.aplicar.Name = "aplicar";
            this.aplicar.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.aplicar.FlatAppearance.BorderSize = 0;
            this.aplicar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.aplicar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.aplicar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.aplicar.ForeColor = System.Drawing.Color.White;
            this.aplicar.UseVisualStyleBackColor = false;







            this.aplicar.Size = new System.Drawing.Size(96, 30);
            this.aplicar.Text = "Aplicar";
            this.aplicar.Click += new System.EventHandler(this.aplicar_Click);
            this.desde.ValueChanged += new System.EventHandler(this.periodoReporte_Cambiado);
            this.hasta.ValueChanged += new System.EventHandler(this.periodoReporte_Cambiado);
            this.desdeA.ValueChanged += new System.EventHandler(this.periodoComparacion_Cambiado);
            this.hastaA.ValueChanged += new System.EventHandler(this.periodoComparacion_Cambiado);
            this.desdeB.ValueChanged += new System.EventHandler(this.periodoComparacion_Cambiado);
            this.hastaB.ValueChanged += new System.EventHandler(this.periodoComparacion_Cambiado);
            // exportarReporte
            this.exportarReporte.Enabled = false;
            this.exportarReporte.Location = new System.Drawing.Point(542, 56);
            this.exportarReporte.Name = "exportarReporte";
            this.exportarReporte.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.exportarReporte.FlatAppearance.BorderSize = 0;
            this.exportarReporte.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.exportarReporte.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.exportarReporte.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.exportarReporte.ForeColor = System.Drawing.Color.White;
            this.exportarReporte.UseVisualStyleBackColor = false;







            this.exportarReporte.Size = new System.Drawing.Size(168, 30);
            this.exportarReporte.TabIndex = 3;
            this.exportarReporte.Text = "Exportar reporte PDF";
            this.exportarReporte.Click += new System.EventHandler(this.exportarReporte_Click);
            // indicadores
            this.indicadores.BackColor = System.Drawing.Color.White;
            this.indicadores.ColumnCount = 4;
            this.indicadores.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.indicadores.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.indicadores.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.indicadores.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 25F));
            this.indicadores.RowCount = 2;
            this.indicadores.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.indicadores.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.indicadores.Dock = System.Windows.Forms.DockStyle.Fill;
            this.indicadores.Size = new System.Drawing.Size(1074, 72);
            this.indicadores.Name = "indicadores";
            this.indicadores.Controls.Add(this.lblIngresosTitulo, 0, 0);
            this.indicadores.Controls.Add(this.lblPagosTitulo, 1, 0);
            this.indicadores.Controls.Add(this.lblActivosTitulo, 2, 0);
            this.indicadores.Controls.Add(this.lblDeudaTitulo, 3, 0);
            this.indicadores.Controls.Add(this.lblIngresos, 0, 1);
            this.indicadores.Controls.Add(this.lblPagos, 1, 1);
            this.indicadores.Controls.Add(this.lblActivos, 2, 1);
            this.indicadores.Controls.Add(this.lblDeuda, 3, 1);
            this.lblIngresosTitulo.Text = "Ingresos del período";
            this.lblPagosTitulo.Text = "Pagos aprobados";
            this.lblActivosTitulo.Text = "Socios activos";
            this.lblDeudaTitulo.Text = "Socios con deuda";
            this.lblIngresosTitulo.Name = "lblIngresosTitulo";
            this.lblIngresosTitulo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblIngresosTitulo.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            this.lblIngresosTitulo.Padding = new System.Windows.Forms.Padding(12, 8, 0, 0);
            this.lblIngresosTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPagosTitulo.Name = "lblPagosTitulo";
            this.lblPagosTitulo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPagosTitulo.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            this.lblPagosTitulo.Padding = new System.Windows.Forms.Padding(12, 8, 0, 0);
            this.lblPagosTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblActivosTitulo.Name = "lblActivosTitulo";
            this.lblActivosTitulo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblActivosTitulo.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            this.lblActivosTitulo.Padding = new System.Windows.Forms.Padding(12, 8, 0, 0);
            this.lblActivosTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDeudaTitulo.Name = "lblDeudaTitulo";
            this.lblDeudaTitulo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeudaTitulo.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            this.lblDeudaTitulo.Padding = new System.Windows.Forms.Padding(12, 8, 0, 0);
            this.lblDeudaTitulo.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblIngresos.Name = "lblIngresos";
            this.lblIngresos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblIngresos.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.lblIngresos.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.lblIngresos.Text = "—";
            this.lblIngresos.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblPagos.Name = "lblPagos";
            this.lblPagos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPagos.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.lblPagos.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.lblPagos.Text = "—";
            this.lblPagos.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblActivos.Name = "lblActivos";
            this.lblActivos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblActivos.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.lblActivos.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.lblActivos.Text = "—";
            this.lblActivos.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblDeuda.Name = "lblDeuda";
            this.lblDeuda.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblDeuda.Font = new System.Drawing.Font("Segoe UI Semibold", 13F, System.Drawing.FontStyle.Bold);
            this.lblDeuda.Padding = new System.Windows.Forms.Padding(12, 0, 0, 0);
            this.lblDeuda.Text = "—";
            this.lblDeuda.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblComparacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblComparacion.Name = "lblComparacion";
            this.lblComparacion.Padding = new System.Windows.Forms.Padding(15, 3, 0, 0);
            this.lblComparacion.Text = "Período anterior: —   |   Variación: —";
            this.lblEstado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEstado.Name = "lblEstado";
            this.lblEstado.Padding = new System.Windows.Forms.Padding(15, 4, 0, 0);
            this.lblEstado.Text = "Seleccione el período y pulse Aplicar.";
            // categorias
            this.categorias.Dock = System.Windows.Forms.DockStyle.Fill;
            this.categorias.Location = new System.Drawing.Point(3, 215);
            this.categorias.Multiline = true;
            this.categorias.Size = new System.Drawing.Size(1074, 448);
            this.categorias.Name = "categorias";
            this.categorias.TabIndex = 3;
            this.tabResumen.Name = "tabResumen";
            this.tabResumen.Text = "Resumen";
            this.tabResumen.UseVisualStyleBackColor = true;
            this.tabResumen.Controls.Add(this.chartIngresos);
            this.tabFinanzas.Name = "tabFinanzas";
            this.tabFinanzas.Text = "Finanzas";
            this.tabFinanzas.UseVisualStyleBackColor = true;
            this.tabFinanzas.Controls.Add(this.chartMetodos);
            this.tabSocios.Name = "tabSocios";
            this.tabSocios.Text = "Socios";
            this.tabSocios.UseVisualStyleBackColor = true;
            this.tabSocios.Controls.Add(this.disposicionSocios);
            this.tabPlanes.Name = "tabPlanes";
            this.tabPlanes.Text = "Planes";
            this.tabPlanes.UseVisualStyleBackColor = true;
            this.tabPlanes.Controls.Add(this.disposicionPlanes);
            this.tabEntrenadores.Name = "tabEntrenadores";
            this.tabEntrenadores.Text = "Entrenadores";
            this.tabEntrenadores.UseVisualStyleBackColor = true;
            this.tabEntrenadores.Controls.Add(this.chartEntrenadores);
            this.disposicionSocios.ColumnCount = 2;
            this.disposicionSocios.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.disposicionSocios.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.disposicionSocios.RowCount = 3;
            this.disposicionSocios.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
            this.disposicionSocios.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.disposicionSocios.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.disposicionSocios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicionSocios.Size = new System.Drawing.Size(1066, 420);
            this.disposicionSocios.Name = "disposicionSocios";
            this.disposicionSocios.Controls.Add(this.lblPorcentajeActivos, 0, 0);
            this.disposicionSocios.SetColumnSpan(this.lblPorcentajeActivos, 2);
            this.disposicionSocios.Controls.Add(this.chartAltas, 0, 1);
            this.disposicionSocios.Controls.Add(this.chartActivos, 1, 1);
            this.disposicionSocios.Controls.Add(this.chartDeuda, 0, 2);
            this.disposicionSocios.SetColumnSpan(this.chartDeuda, 2);
            this.lblPorcentajeActivos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblPorcentajeActivos.Name = "lblPorcentajeActivos";
            this.lblPorcentajeActivos.Text = "Total socios: —";
            this.chartIngresos.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartIngresos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartIngresos.Name = "chartIngresos";
            this.chartIngresos.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Ingresos por mes"));
            this.chartMetodos.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartMetodos.Legends.Add(new System.Windows.Forms.DataVisualization.Charting.Legend("Categorias"));
            this.chartMetodos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartMetodos.Name = "chartMetodos";
            this.chartMetodos.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Métodos de pago"));
            this.chartAltas.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartAltas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartAltas.Name = "chartAltas";
            this.chartAltas.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Altas de socios por mes"));
            this.chartActivos.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartActivos.Legends.Add(new System.Windows.Forms.DataVisualization.Charting.Legend("Categorias"));
            this.chartActivos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartActivos.Name = "chartActivos";
            this.chartActivos.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Socios activos e inactivos"));
            this.chartDeuda.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartDeuda.Legends.Add(new System.Windows.Forms.DataVisualization.Charting.Legend("Categorias"));
            this.chartDeuda.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartDeuda.Name = "chartDeuda";
            this.chartDeuda.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Estado de deuda"));
            this.chartPlanes.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartPlanes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartPlanes.Name = "chartPlanes";
            this.chartPlanes.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Planes más contratados"));
            this.chartEntrenadores.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartEntrenadores.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartEntrenadores.Name = "chartEntrenadores";
            this.chartEntrenadores.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Socios por entrenador"));
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.chartIngresosPlan.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartIngresosPlan.Name = "chartIngresosPlan";
            this.chartIngresosPlan.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartIngresosPlan.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Ingresos reales por plan"));
            this.chartRutinas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartRutinas.Name = "chartRutinas";
            this.chartRutinas.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartRutinas.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Rutinas más utilizadas"));
            this.chartEjercicios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartEjercicios.Name = "chartEjercicios";
            this.chartEjercicios.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartEjercicios.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Top 10 ejercicios: rutinas distintas"));
            this.chartCompararIngresos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartCompararIngresos.Name = "chartCompararIngresos";
            this.chartCompararIngresos.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartCompararIngresos.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Ingresos: A vs B"));
            this.chartCompararIngresos.Legends.Add(new System.Windows.Forms.DataVisualization.Charting.Legend("Periodos"));
            this.chartCompararCantidades.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartCompararCantidades.Name = "chartCompararCantidades";
            this.chartCompararCantidades.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartCompararCantidades.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Pagos y altas: A vs B"));
            this.chartCompararCantidades.Legends.Add(new System.Windows.Forms.DataVisualization.Charting.Legend("Periodos"));
            this.chartSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.chartSocio.Name = "chartSocio";
            this.chartSocio.ChartAreas.Add(new System.Windows.Forms.DataVisualization.Charting.ChartArea("Principal"));
            this.chartSocio.Titles.Add(new System.Windows.Forms.DataVisualization.Charting.Title("Pagos históricos del socio"));
            this.tabRutinas.Name = "tabRutinas";
            this.tabRutinas.Text = "Rutinas";
            this.tabRutinas.UseVisualStyleBackColor = true;
            this.tabEjercicios.Name = "tabEjercicios";
            this.tabEjercicios.Text = "Ejercicios";
            this.tabEjercicios.UseVisualStyleBackColor = true;
            this.tabComparar.Name = "tabComparar";
            this.tabComparar.Text = "Comparar";
            this.tabComparar.UseVisualStyleBackColor = true;
            this.tabSocio.Name = "tabSocio";
            this.tabSocio.Text = "Socio";
            this.tabSocio.UseVisualStyleBackColor = true;
            this.disposicionPlanes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicionPlanes.Size = new System.Drawing.Size(1066, 420);
            this.disposicionPlanes.Name = "disposicionPlanes";
            this.disposicionPlanes.ColumnCount = 2;
            this.disposicionPlanes.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.disposicionPlanes.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.disposicionPlanes.RowCount = 1;
            this.disposicionPlanes.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.disposicionPlanes.Controls.Add(this.chartPlanes, 0, 0);
            this.disposicionPlanes.Controls.Add(this.chartIngresosPlan, 1, 0);
            this.tabRutinas.Controls.Add(this.chartRutinas);
            this.tabRutinas.Controls.Add(this.lblSinRutina);
            this.lblSinRutina.Name = "lblSinRutina";
            this.lblSinRutina.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.lblSinRutina.Height = 30;
            this.lblSinRutina.Text = "Socios activos sin rutina activa: —";
            this.tablaEjercicios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tablaEjercicios.Size = new System.Drawing.Size(1066, 420);
            this.tablaEjercicios.Name = "tablaEjercicios";
            this.tablaEjercicios.ColumnCount = 2;
            this.tablaEjercicios.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.tablaEjercicios.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tablaEjercicios.RowCount = 2;
            this.tablaEjercicios.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.tablaEjercicios.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabEjercicios.Controls.Add(this.tablaEjercicios);
            this.tablaEjercicios.Controls.Add(this.chartEjercicios, 0, 0);
            this.tablaEjercicios.SetRowSpan(this.chartEjercicios, 2);
            this.tablaEjercicios.Controls.Add(this.lblEjerciciosSinUso, 1, 0);
            this.tablaEjercicios.Controls.Add(this.gridEjerciciosSinUso, 1, 1);
            this.lblEjerciciosSinUso.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEjerciciosSinUso.Name = "lblEjerciciosSinUso";
            this.lblEjerciciosSinUso.Text = "Ejercicios activos sin uso: —";
            this.gridEjerciciosSinUso.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridEjerciciosSinUso.Name = "gridEjerciciosSinUso";
            this.gridEjerciciosSinUso.AutoGenerateColumns = false;
            this.gridEjerciciosSinUso.ReadOnly = true;
            this.gridEjerciciosSinUso.AllowUserToAddRows = false;
            this.gridEjerciciosSinUso.AllowUserToDeleteRows = false;
            this.gridEjerciciosSinUso.RowHeadersVisible = false;
            this.gridEjerciciosSinUso.BackgroundColor = System.Drawing.Color.White;
            this.gridEjerciciosSinUso.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridEjerciciosSinUso.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridEjerciciosSinUso.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colEjercicioNombre, this.colEjercicioDescripcion });
            this.colEjercicioNombre.Name = "colEjercicioNombre";
            this.colEjercicioNombre.HeaderText = "Ejercicio";
            this.colEjercicioNombre.DataPropertyName = "Nombre";
            this.colEjercicioNombre.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colEjercicioDescripcion.Name = "colEjercicioDescripcion";
            this.colEjercicioDescripcion.HeaderText = "Descripción";
            this.colEjercicioDescripcion.DataPropertyName = "Descripcion";
            this.colEjercicioDescripcion.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.tablaComparar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tablaComparar.Size = new System.Drawing.Size(1066, 420);
            this.tablaComparar.Name = "tablaComparar";
            this.tablaComparar.ColumnCount = 2;
            this.tablaComparar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 68F));
            this.tablaComparar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 32F));
            this.tablaComparar.RowCount = 3;
            this.tablaComparar.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 88F));
            this.tablaComparar.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tablaComparar.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 38F));
            this.tabComparar.Controls.Add(this.tablaComparar);
            this.tablaComparar.Controls.Add(this.filtrosComparar, 0, 0);
            this.tablaComparar.SetColumnSpan(this.filtrosComparar, 2);
            this.tablaComparar.Controls.Add(this.tablaChartsComparar, 0, 1);
            this.tablaComparar.Controls.Add(this.gridComparacion, 1, 1);
            this.tablaComparar.Controls.Add(this.lblCompararEstado, 0, 2);
            this.tablaComparar.SetColumnSpan(this.lblCompararEstado, 2);
            this.filtrosComparar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.filtrosComparar.Size = new System.Drawing.Size(1060, 82);
            this.filtrosComparar.Name = "filtrosComparar";
            this.lblPeriodoA.Location = new System.Drawing.Point(12, 13);
            this.lblPeriodoA.Size = new System.Drawing.Size(96, 25);
            this.lblPeriodoA.Name = "lblPeriodoA";
            this.lblPeriodoA.Text = "Período A";
            this.lblPeriodoA.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.filtrosComparar.Controls.Add(this.lblPeriodoA);
            this.lblPeriodoB.Location = new System.Drawing.Point(12, 51);
            this.lblPeriodoB.Size = new System.Drawing.Size(96, 25);
            this.lblPeriodoB.Name = "lblPeriodoB";
            this.lblPeriodoB.Text = "Período B";
            this.lblPeriodoB.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.filtrosComparar.Controls.Add(this.lblPeriodoB);
            this.lblHastaA.Location = new System.Drawing.Point(284, 13);
            this.lblHastaA.Size = new System.Drawing.Size(52, 25);
            this.lblHastaA.Name = "lblHastaA";
            this.lblHastaA.Text = "Hasta";
            this.lblHastaA.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.filtrosComparar.Controls.Add(this.lblHastaA);
            this.lblHastaB.Location = new System.Drawing.Point(284, 51);
            this.lblHastaB.Size = new System.Drawing.Size(52, 25);
            this.lblHastaB.Name = "lblHastaB";
            this.lblHastaB.Text = "Hasta";
            this.lblHastaB.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.filtrosComparar.Controls.Add(this.lblHastaB);
            this.desdeA.Location = new System.Drawing.Point(116, 13);
            this.desdeA.Size = new System.Drawing.Size(138, 25);
            this.desdeA.Name = "desdeA";
            this.desdeA.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.filtrosComparar.Controls.Add(this.desdeA);
            this.hastaA.Location = new System.Drawing.Point(338, 13);
            this.hastaA.Size = new System.Drawing.Size(138, 25);
            this.hastaA.Name = "hastaA";
            this.hastaA.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.filtrosComparar.Controls.Add(this.hastaA);
            this.desdeB.Location = new System.Drawing.Point(116, 51);
            this.desdeB.Size = new System.Drawing.Size(138, 25);
            this.desdeB.Name = "desdeB";
            this.desdeB.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.filtrosComparar.Controls.Add(this.desdeB);
            this.hastaB.Location = new System.Drawing.Point(338, 51);
            this.hastaB.Size = new System.Drawing.Size(138, 25);
            this.hastaB.Name = "hastaB";
            this.hastaB.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.filtrosComparar.Controls.Add(this.hastaB);
            this.comparar.Anchor = (System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right);
            this.comparar.Location = new System.Drawing.Point(900, 25);
            this.comparar.Size = new System.Drawing.Size(148, 32);
            this.comparar.Name = "comparar";
            this.comparar.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.comparar.FlatAppearance.BorderSize = 0;
            this.comparar.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.comparar.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.comparar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.comparar.ForeColor = System.Drawing.Color.White;
            this.comparar.UseVisualStyleBackColor = false;







            this.comparar.Text = "Comparar períodos";
            this.comparar.Click += new System.EventHandler(this.comparar_Click);
            this.filtrosComparar.Controls.Add(this.comparar);
            this.tablaChartsComparar.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tablaChartsComparar.Size = new System.Drawing.Size(1060, 158);
            this.tablaChartsComparar.Name = "tablaChartsComparar";
            this.tablaChartsComparar.ColumnCount = 2;
            this.tablaChartsComparar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tablaChartsComparar.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tablaChartsComparar.RowCount = 1;
            this.tablaChartsComparar.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tablaChartsComparar.Controls.Add(this.chartCompararIngresos, 0, 0);
            this.tablaChartsComparar.Controls.Add(this.chartCompararCantidades, 1, 0);
            this.gridComparacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridComparacion.Name = "gridComparacion";
            this.gridComparacion.AutoGenerateColumns = false;
            this.gridComparacion.ReadOnly = true;
            this.gridComparacion.AllowUserToAddRows = false;
            this.gridComparacion.AllowUserToDeleteRows = false;
            this.gridComparacion.RowHeadersVisible = false;
            this.gridComparacion.BackgroundColor = System.Drawing.Color.White;
            this.gridComparacion.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridComparacion.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridComparacion.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colIndicador, this.colValorA, this.colValorB, this.colVariacion });
            this.colIndicador.Name = "colIndicador";
            this.colIndicador.HeaderText = "Indicador";
            this.colIndicador.FillWeight = 130F;
            this.colIndicador.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colValorA.Name = "colValorA";
            this.colValorA.HeaderText = "Valor A";
            this.colValorA.FillWeight = 90F;
            this.colValorA.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colValorB.Name = "colValorB";
            this.colValorB.HeaderText = "Valor B";
            this.colValorB.FillWeight = 90F;
            this.colValorB.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colVariacion.Name = "colVariacion";
            this.colVariacion.HeaderText = "Variación";
            this.colVariacion.FillWeight = 120F;
            this.colVariacion.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.lblCompararEstado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblCompararEstado.Name = "lblCompararEstado";
            this.lblCompararEstado.Text = "Seleccione A y B y pulse Comparar períodos. No hay historial suficiente de deuda.";
            this.tablaSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tablaSocio.Size = new System.Drawing.Size(1066, 420);
            this.tablaSocio.Name = "tablaSocio";
            this.tablaSocio.ColumnCount = 1;
            this.tablaSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tablaSocio.RowCount = 2;
            this.tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 106F));
            this.tablaSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tabSocio.Controls.Add(this.tablaSocio);
            this.tablaSocio.Controls.Add(this.barraSocio, 0, 0);
            this.tablaSocio.Controls.Add(this.tablaDetalleSocio, 0, 1);
            this.barraSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.barraSocio.Name = "barraSocio";
            this.barraSocio.Size = new System.Drawing.Size(1066, 106);
            this.lblBuscarSocio.Location = new System.Drawing.Point(12, 12);
            this.lblBuscarSocio.Size = new System.Drawing.Size(110, 24);
            this.lblBuscarSocio.Name = "lblBuscarSocio";
            this.lblBuscarSocio.Text = "Nombre o DNI:";
            this.buscarSocio.Location = new System.Drawing.Point(126, 10);
            this.buscarSocio.Size = new System.Drawing.Size(254, 25);
            this.buscarSocio.Name = "buscarSocio";
            this.btnBuscarSocio.Location = new System.Drawing.Point(392, 8);
            this.btnBuscarSocio.Size = new System.Drawing.Size(96, 30);
            this.btnBuscarSocio.Name = "btnBuscarSocio";
            this.btnBuscarSocio.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.btnBuscarSocio.FlatAppearance.BorderSize = 0;
            this.btnBuscarSocio.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.btnBuscarSocio.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.btnBuscarSocio.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnBuscarSocio.ForeColor = System.Drawing.Color.White;
            this.btnBuscarSocio.UseVisualStyleBackColor = false;







            this.btnBuscarSocio.Text = "Buscar";
            this.btnBuscarSocio.Click += new System.EventHandler(this.buscarSocio_Click);
            this.selectorSocio.Location = new System.Drawing.Point(12, 44);
            this.selectorSocio.Size = new System.Drawing.Size(1038, 26);
            this.selectorSocio.Name = "selectorSocio";
            this.selectorSocio.Anchor = (System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right);
            this.selectorSocio.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.selectorSocio.SelectedIndexChanged += new System.EventHandler(this.selectorSocio_SelectedIndexChanged);
            this.lblBusquedaEstado.Location = new System.Drawing.Point(12, 74);
            this.lblBusquedaEstado.Size = new System.Drawing.Size(1038, 26);
            this.lblBusquedaEstado.Name = "lblBusquedaEstado";
            this.lblBusquedaEstado.Anchor = (System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right);
            this.lblBusquedaEstado.Text = "Busque y seleccione un socio; consulta sin edición.";
            this.barraSocio.Controls.Add(this.lblBuscarSocio);
            this.barraSocio.Controls.Add(this.buscarSocio);
            this.barraSocio.Controls.Add(this.btnBuscarSocio);
            this.barraSocio.Controls.Add(this.selectorSocio);
            this.barraSocio.Controls.Add(this.lblBusquedaEstado);
            this.tablaDetalleSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tablaDetalleSocio.Size = new System.Drawing.Size(1060, 308);
            this.tablaDetalleSocio.Name = "tablaDetalleSocio";
            this.tablaDetalleSocio.ColumnCount = 2;
            this.tablaDetalleSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 46F));
            this.tablaDetalleSocio.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 54F));
            this.tablaDetalleSocio.RowCount = 1;
            this.tablaDetalleSocio.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tablaDetalleSocio.Controls.Add(this.gridSocio, 0, 0);
            this.tablaDetalleSocio.Controls.Add(this.chartSocio, 1, 0);
            this.gridSocio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridSocio.Name = "gridSocio";
            this.gridSocio.AutoGenerateColumns = false;
            this.gridSocio.ReadOnly = true;
            this.gridSocio.AllowUserToAddRows = false;
            this.gridSocio.AllowUserToDeleteRows = false;
            this.gridSocio.RowHeadersVisible = false;
            this.gridSocio.BackgroundColor = System.Drawing.Color.White;
            this.gridSocio.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.gridSocio.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.gridSocio.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colDatoSocio, this.colValorSocio });
            this.colDatoSocio.Name = "colDatoSocio";
            this.colDatoSocio.HeaderText = "Dato";
            this.colDatoSocio.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colValorSocio.Name = "colValorSocio";
            this.colValorSocio.HeaderText = "Valor";
            this.colValorSocio.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.categorias.Controls.Add(this.tabResumen);
            this.categorias.Controls.Add(this.tabFinanzas);
            this.categorias.Controls.Add(this.tabSocios);
            this.categorias.Controls.Add(this.tabPlanes);
            this.categorias.Controls.Add(this.tabEntrenadores);
            this.categorias.Controls.Add(this.tabRutinas);
            this.categorias.Controls.Add(this.tabEjercicios);
            this.categorias.Controls.Add(this.tabComparar);
            this.categorias.Controls.Add(this.tabSocio);
            this.categorias.SelectedIndex = 0;
            this.disposicion.Controls.Add(this.categorias, 0, 3);
            this.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.ClientSize = new System.Drawing.Size(1080, 700);
            this.Controls.Add(this.disposicion);
            this.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.Name = "AnalisisFormulario";
            this.Text = "SysGym";
            this.Load += new System.EventHandler(this.AnalisisFormulario_Load);
            this.encabezado.ResumeLayout(false);
            this.encabezado.PerformLayout();
            this.indicadores.ResumeLayout(false);
            this.tabResumen.ResumeLayout(false);
            this.tabFinanzas.ResumeLayout(false);
            this.tabSocios.ResumeLayout(false);
            this.tabPlanes.ResumeLayout(false);
            this.tabEntrenadores.ResumeLayout(false);
            this.disposicionSocios.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.chartIngresos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartMetodos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartAltas)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartActivos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartDeuda)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartPlanes)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartEntrenadores)).EndInit();
            this.disposicionPlanes.ResumeLayout(false);
            this.tabRutinas.ResumeLayout(false);
            this.tabEjercicios.ResumeLayout(false);
            this.tabComparar.ResumeLayout(false);
            this.tabSocio.ResumeLayout(false);
            this.tablaEjercicios.ResumeLayout(false);
            this.tablaComparar.ResumeLayout(false);
            this.filtrosComparar.ResumeLayout(false);
            this.tablaChartsComparar.ResumeLayout(false);
            this.tablaSocio.ResumeLayout(false);
            this.barraSocio.ResumeLayout(false);
            this.tablaDetalleSocio.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.chartIngresosPlan)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartRutinas)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartEjercicios)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartCompararIngresos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartCompararCantidades)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.chartSocio)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridEjerciciosSinUso)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridComparacion)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridSocio)).EndInit();
            this.categorias.ResumeLayout(false);
            this.disposicion.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
