using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Recepcionista
{
    partial class GestionAsignacionesForm
    {
        private IContainer components;
        private Panel panelEncabezado; private Label lblTitulo; private Label lblDescripcion; private Button btnVolver; private FlowLayoutPanel barraAcciones; private Label lblEstado; private Panel panelContenido; private Panel panelFormulario; private TableLayoutPanel layoutFormulario; private Label lblMembresia; private Label lblEntrenador; private DataGridView tabla; private DataGridViewTextBoxColumn colId; private DataGridViewTextBoxColumn colMembresia; private DataGridViewTextBoxColumn colEntrenador; private DataGridViewTextBoxColumn colEstado;
        private TextBox membresia; private ComboBox entrenador; private Button asignar; private Button cambiar; private Button consultar; private Button darDeBaja;
        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new Container(); panelEncabezado = new Panel(); lblTitulo = new Label(); lblDescripcion = new Label(); btnVolver = new Button(); barraAcciones = new FlowLayoutPanel(); asignar = new Button(); cambiar = new Button(); consultar = new Button(); darDeBaja = new Button(); lblEstado = new Label(); panelContenido = new Panel(); panelFormulario = new Panel(); layoutFormulario = new TableLayoutPanel(); lblMembresia = new Label(); membresia = new TextBox(); lblEntrenador = new Label(); entrenador = new ComboBox(); tabla = new DataGridView(); colId = new DataGridViewTextBoxColumn(); colMembresia = new DataGridViewTextBoxColumn(); colEntrenador = new DataGridViewTextBoxColumn(); colEstado = new DataGridViewTextBoxColumn(); panelEncabezado.SuspendLayout(); barraAcciones.SuspendLayout(); panelContenido.SuspendLayout(); panelFormulario.SuspendLayout(); layoutFormulario.SuspendLayout(); ((ISupportInitialize)(tabla)).BeginInit(); SuspendLayout();
            panelEncabezado.BackColor = Color.FromArgb(5, 150, 105); panelEncabezado.Dock = DockStyle.Top; panelEncabezado.Height = 80; panelEncabezado.Controls.Add(lblDescripcion); panelEncabezado.Controls.Add(lblTitulo); panelEncabezado.Controls.Add(btnVolver); lblTitulo.AutoSize = true; lblTitulo.Font = new Font("Segoe UI", 18F, FontStyle.Bold); lblTitulo.ForeColor = Color.White; lblTitulo.Location = new Point(22, 10); lblTitulo.Text = "Asignar entrenador"; lblDescripcion.AutoSize = true; lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240); lblDescripcion.Location = new Point(24, 47); lblDescripcion.Text = "Vinculacion de entrenadores con membresias"; btnVolver.Anchor = AnchorStyles.Top | AnchorStyles.Right; btnVolver.BackColor = Color.White; btnVolver.FlatStyle = FlatStyle.Flat; btnVolver.FlatAppearance.BorderSize = 0; btnVolver.ForeColor = Color.FromArgb(5, 150, 105); btnVolver.Location = new Point(930, 22); btnVolver.Size = new Size(92, 34); btnVolver.Text = "Volver"; btnVolver.UseVisualStyleBackColor = false;
            barraAcciones.BackColor = Color.White; barraAcciones.Dock = DockStyle.Top; barraAcciones.Height = 52; barraAcciones.Padding = new Padding(16, 8, 16, 8); barraAcciones.WrapContents = false; barraAcciones.Controls.Add(asignar); barraAcciones.Controls.Add(cambiar); barraAcciones.Controls.Add(consultar); barraAcciones.Controls.Add(darDeBaja);
            lblEstado.AutoSize = false; lblEstado.BackColor = Color.FromArgb(226, 232, 240); lblEstado.Dock = DockStyle.Bottom; lblEstado.ForeColor = Color.FromArgb(51, 65, 85); lblEstado.Height = 32; lblEstado.Padding = new Padding(18, 8, 8, 0); lblEstado.Text = "Listo"; panelContenido.BackColor = Color.FromArgb(248, 250, 252); panelContenido.Dock = DockStyle.Fill; panelContenido.Padding = new Padding(20); panelContenido.Controls.Add(tabla); panelContenido.Controls.Add(panelFormulario); panelFormulario.BackColor = Color.White; panelFormulario.BorderStyle = BorderStyle.FixedSingle; panelFormulario.Dock = DockStyle.Top; panelFormulario.Height = 96; panelFormulario.Padding = new Padding(12); panelFormulario.Controls.Add(layoutFormulario); layoutFormulario.ColumnCount = 4; layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 35F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90F)); layoutFormulario.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 65F)); layoutFormulario.Dock = DockStyle.Fill; layoutFormulario.Controls.Add(lblMembresia, 0, 0); layoutFormulario.Controls.Add(membresia, 1, 0); layoutFormulario.Controls.Add(lblEntrenador, 2, 0); layoutFormulario.Controls.Add(entrenador, 3, 0); membresia.Dock = DockStyle.Fill; membresia.BorderStyle = BorderStyle.FixedSingle; entrenador.Dock = DockStyle.Fill; entrenador.DropDownStyle = ComboBoxStyle.DropDownList;
            tabla.AllowUserToAddRows = false; tabla.AllowUserToDeleteRows = false; tabla.AllowUserToResizeRows = false; tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; tabla.BackgroundColor = Color.White; tabla.BorderStyle = BorderStyle.None; tabla.ColumnHeadersHeight = 38; tabla.Dock = DockStyle.Fill; tabla.MultiSelect = false; tabla.ReadOnly = true; tabla.RowHeadersVisible = false; tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect; tabla.Columns.AddRange(new DataGridViewColumn[] { colId, colMembresia, colEntrenador, colEstado }); colId.HeaderText = "Id"; colId.Name = "colId"; colId.Visible = false; colMembresia.HeaderText = "Membresia"; colMembresia.Name = "colMembresia"; colEntrenador.HeaderText = "Entrenador"; colEntrenador.Name = "colEntrenador"; colEstado.HeaderText = "Estado"; colEstado.Name = "colEstado";
            panelEncabezado.Location = new Point(0, 0); panelEncabezado.Name = "panelEncabezado"; panelEncabezado.Size = new Size(1100, 80); panelEncabezado.TabIndex = 0;
            lblTitulo.Name = "lblTitulo"; lblTitulo.Size = new Size(245, 32); lblTitulo.TabIndex = 0;
            lblDescripcion.Name = "lblDescripcion"; lblDescripcion.Size = new Size(301, 17); lblDescripcion.TabIndex = 1;
            btnVolver.Name = "btnVolver"; btnVolver.TabIndex = 2;
            barraAcciones.Location = new Point(0, 80); barraAcciones.Name = "barraAcciones"; barraAcciones.Size = new Size(1100, 52); barraAcciones.TabIndex = 1;
            asignar.AutoSize = true; asignar.BackColor = Color.FromArgb(5, 150, 105); asignar.FlatAppearance.BorderSize = 0; asignar.FlatStyle = FlatStyle.Flat; asignar.ForeColor = Color.White; asignar.Height = 36; asignar.Location = new Point(20, 8); asignar.Margin = new Padding(4, 0, 4, 0); asignar.Name = "asignar"; asignar.Padding = new Padding(12, 0, 12, 0); asignar.Size = new Size(88, 36); asignar.TabIndex = 0; asignar.Text = "Asignar"; asignar.UseVisualStyleBackColor = false;
            cambiar.AutoSize = true; cambiar.BackColor = Color.FromArgb(226, 232, 240); cambiar.FlatAppearance.BorderSize = 0; cambiar.FlatStyle = FlatStyle.Flat; cambiar.ForeColor = Color.FromArgb(30, 41, 59); cambiar.Height = 36; cambiar.Location = new Point(116, 8); cambiar.Margin = new Padding(4, 0, 4, 0); cambiar.Name = "cambiar"; cambiar.Padding = new Padding(12, 0, 12, 0); cambiar.Size = new Size(91, 36); cambiar.TabIndex = 1; cambiar.Text = "Cambiar"; cambiar.UseVisualStyleBackColor = false;
            consultar.AutoSize = true; consultar.BackColor = Color.FromArgb(226, 232, 240); consultar.FlatAppearance.BorderSize = 0; consultar.FlatStyle = FlatStyle.Flat; consultar.ForeColor = Color.FromArgb(30, 41, 59); consultar.Height = 36; consultar.Location = new Point(215, 8); consultar.Margin = new Padding(4, 0, 4, 0); consultar.Name = "consultar"; consultar.Padding = new Padding(12, 0, 12, 0); consultar.Size = new Size(102, 36); consultar.TabIndex = 2; consultar.Text = "Consultar"; consultar.UseVisualStyleBackColor = false;
            darDeBaja.AutoSize = true; darDeBaja.BackColor = Color.FromArgb(254, 242, 242); darDeBaja.FlatAppearance.BorderSize = 0; darDeBaja.FlatStyle = FlatStyle.Flat; darDeBaja.ForeColor = Color.FromArgb(185, 28, 28); darDeBaja.Height = 36; darDeBaja.Location = new Point(325, 8); darDeBaja.Margin = new Padding(4, 0, 4, 0); darDeBaja.Name = "darDeBaja"; darDeBaja.Padding = new Padding(12, 0, 12, 0); darDeBaja.Size = new Size(111, 36); darDeBaja.TabIndex = 3; darDeBaja.Text = "Dar de baja"; darDeBaja.UseVisualStyleBackColor = false;
            lblEstado.Location = new Point(0, 648); lblEstado.Name = "lblEstado"; lblEstado.Size = new Size(1100, 32); lblEstado.TabIndex = 3;
            panelContenido.Location = new Point(0, 132); panelContenido.Name = "panelContenido"; panelContenido.Size = new Size(1100, 516); panelContenido.TabIndex = 2;
            panelFormulario.Location = new Point(20, 20); panelFormulario.Name = "panelFormulario"; panelFormulario.Size = new Size(1060, 96); panelFormulario.TabIndex = 0;
            layoutFormulario.Location = new Point(12, 12); layoutFormulario.Name = "layoutFormulario"; layoutFormulario.RowCount = 1; layoutFormulario.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); layoutFormulario.Size = new Size(1034, 70); layoutFormulario.TabIndex = 0;
            lblMembresia.Anchor = AnchorStyles.Left; lblMembresia.AutoSize = true; lblMembresia.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblMembresia.ForeColor = Color.FromArgb(51, 65, 85); lblMembresia.Name = "lblMembresia"; lblMembresia.Size = new Size(73, 15); lblMembresia.TabIndex = 0; lblMembresia.Text = "Membresia:";
            membresia.Margin = new Padding(0, 4, 8, 4); membresia.Name = "membresia"; membresia.Size = new Size(286, 25); membresia.TabIndex = 1;
            lblEntrenador.Anchor = AnchorStyles.Left; lblEntrenador.AutoSize = true; lblEntrenador.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblEntrenador.ForeColor = Color.FromArgb(51, 65, 85); lblEntrenador.Name = "lblEntrenador"; lblEntrenador.Size = new Size(70, 15); lblEntrenador.TabIndex = 2; lblEntrenador.Text = "Entrenador:";
            entrenador.Margin = new Padding(0, 4, 0, 4); entrenador.Name = "entrenador"; entrenador.Size = new Size(617, 25); entrenador.TabIndex = 3;
            tabla.Location = new Point(20, 116); tabla.Name = "tabla"; tabla.Size = new Size(1060, 380); tabla.TabIndex = 1;
            colId.Width = 60; colMembresia.Width = 250; colEntrenador.Width = 500; colEstado.Width = 250;
            Controls.Add(panelContenido); Controls.Add(lblEstado); Controls.Add(barraAcciones); Controls.Add(panelEncabezado); AutoScaleMode = AutoScaleMode.Font; BackColor = Color.FromArgb(241, 245, 249); ClientSize = new Size(1100, 680); Font = new Font("Segoe UI", 9.5F); MinimumSize = new Size(760, 540); Name = "GestionAsignacionesForm"; StartPosition = FormStartPosition.CenterParent; Text = "SysGym | Asignar entrenador"; panelEncabezado.ResumeLayout(false); panelEncabezado.PerformLayout(); barraAcciones.ResumeLayout(false); barraAcciones.PerformLayout(); panelContenido.ResumeLayout(false); panelFormulario.ResumeLayout(false); layoutFormulario.ResumeLayout(false); layoutFormulario.PerformLayout(); ((ISupportInitialize)(tabla)).EndInit(); ResumeLayout(false);
        }

    }
}
