using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Recepcionista
{
    partial class GestionPagosForm
    {
        private IContainer components;
        private Panel panelEncabezado; private Label lblTitulo; private Label lblDescripcion; private Button btnVolver; private Label lblEstado; private Panel panelContenido; private TableLayoutPanel layoutContenido; private Panel panelListado; private Label lblListado; private Label lblAyuda; private Panel panelFiltro; private Label lblFiltro; private Panel panelDetalle; private TableLayoutPanel layoutDetalle; private Label lblFormulario; private TableLayoutPanel layoutCampos; private Panel panelAcciones; private Label lblMembresia; private Label lblCuota; private Label lblImporte; private Label lblMetodo; private Label lblEstadoPago; private FlowLayoutPanel barraAcciones; private DataGridView tabla; private DataGridViewTextBoxColumn colIdCuota; private DataGridViewTextBoxColumn colIdPago; private DataGridViewTextBoxColumn colSocio; private DataGridViewTextBoxColumn colDni; private DataGridViewTextBoxColumn colPlan; private DataGridViewTextBoxColumn colPeriodo; private DataGridViewTextBoxColumn colImporte; private DataGridViewTextBoxColumn colEstadoTabla;
        private TextBox buscador; private ComboBox filtroEstado; private ComboBox membresia; private TextBox cuota; private TextBox importe; private ComboBox metodo; private ComboBox estado; private Button nuevo; private Button registrar; private Button anular; private Button reembolsar;

        protected override void Dispose(bool disposing) { if (disposing && components != null) components.Dispose(); base.Dispose(disposing); }

        private void InitializeComponent()
        {
            components = new Container(); panelEncabezado = new Panel(); lblTitulo = new Label(); lblDescripcion = new Label(); btnVolver = new Button(); barraAcciones = new FlowLayoutPanel(); lblEstado = new Label(); panelContenido = new Panel(); layoutContenido = new TableLayoutPanel(); panelListado = new Panel(); lblListado = new Label(); lblAyuda = new Label(); buscador = new TextBox(); panelFiltro = new Panel(); lblFiltro = new Label(); filtroEstado = new ComboBox(); panelDetalle = new Panel(); layoutDetalle = new TableLayoutPanel(); lblFormulario = new Label(); layoutCampos = new TableLayoutPanel(); panelAcciones = new Panel(); lblMembresia = new Label(); lblCuota = new Label(); lblImporte = new Label(); lblMetodo = new Label(); lblEstadoPago = new Label(); membresia = new ComboBox(); cuota = new TextBox(); importe = new TextBox(); metodo = new ComboBox(); estado = new ComboBox(); nuevo = new Button(); registrar = new Button(); anular = new Button(); reembolsar = new Button(); tabla = new DataGridView(); colIdCuota = new DataGridViewTextBoxColumn(); colIdPago = new DataGridViewTextBoxColumn(); colSocio = new DataGridViewTextBoxColumn(); colDni = new DataGridViewTextBoxColumn(); colPlan = new DataGridViewTextBoxColumn(); colPeriodo = new DataGridViewTextBoxColumn(); colImporte = new DataGridViewTextBoxColumn(); colEstadoTabla = new DataGridViewTextBoxColumn(); panelEncabezado.SuspendLayout(); panelContenido.SuspendLayout(); layoutContenido.SuspendLayout(); panelListado.SuspendLayout(); panelFiltro.SuspendLayout(); ((ISupportInitialize)(tabla)).BeginInit(); panelDetalle.SuspendLayout(); layoutDetalle.SuspendLayout(); layoutCampos.SuspendLayout(); panelAcciones.SuspendLayout(); SuspendLayout();
            panelEncabezado.BackColor = Color.FromArgb(5, 150, 105); panelEncabezado.Dock = DockStyle.Top; panelEncabezado.Height = 80; panelEncabezado.Controls.Add(lblDescripcion); panelEncabezado.Controls.Add(lblTitulo); panelEncabezado.Controls.Add(btnVolver); lblTitulo.AutoSize = true; lblTitulo.Font = new Font("Segoe UI", 18F, FontStyle.Bold); lblTitulo.ForeColor = Color.White; lblTitulo.Location = new Point(22, 10); lblTitulo.Text = "Cuotas y pagos"; lblDescripcion.AutoSize = true; lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240); lblDescripcion.Location = new Point(24, 47); lblDescripcion.Text = "Registro de pagos y consulta de cuotas"; btnVolver.Anchor = AnchorStyles.Top | AnchorStyles.Right; btnVolver.BackColor = Color.White; btnVolver.FlatStyle = FlatStyle.Flat; btnVolver.FlatAppearance.BorderSize = 0; btnVolver.ForeColor = Color.FromArgb(5, 150, 105); btnVolver.Location = new Point(930, 22); btnVolver.Size = new Size(92, 34); btnVolver.Text = "Volver"; btnVolver.UseVisualStyleBackColor = false;
            lblEstado.AutoSize = false; lblEstado.BackColor = Color.FromArgb(226, 232, 240); lblEstado.Dock = DockStyle.Bottom; lblEstado.ForeColor = Color.FromArgb(51, 65, 85); lblEstado.Height = 32; lblEstado.Padding = new Padding(18, 8, 8, 0); lblEstado.Text = "Listo"; panelContenido.BackColor = Color.FromArgb(248, 250, 252); panelContenido.Dock = DockStyle.Fill; panelContenido.Padding = new Padding(12); panelContenido.Controls.Add(layoutContenido); layoutContenido.ColumnCount = 2; layoutContenido.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 57F)); layoutContenido.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 43F)); layoutContenido.Dock = DockStyle.Fill; layoutContenido.Controls.Add(panelListado, 0, 0); layoutContenido.Controls.Add(panelDetalle, 1, 0);
            panelListado.BackColor = Color.White; panelListado.BorderStyle = BorderStyle.FixedSingle; panelListado.Dock = DockStyle.Fill; panelListado.Padding = new Padding(16); panelListado.Controls.Add(tabla); panelListado.Controls.Add(panelFiltro); panelListado.Controls.Add(lblAyuda); panelListado.Controls.Add(lblListado); lblListado.AutoSize = true; lblListado.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold); lblListado.ForeColor = Color.FromArgb(30, 41, 59); lblListado.Location = new Point(16, 14); lblListado.Text = "Cuotas"; lblAyuda.AutoSize = true; lblAyuda.ForeColor = Color.FromArgb(100, 116, 139); lblAyuda.Location = new Point(16, 42); lblAyuda.Text = "Busca por socio, DNI o plan"; panelFiltro.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right; panelFiltro.Location = new Point(16, 68); panelFiltro.Size = new Size(560, 54); panelFiltro.Controls.Add(filtroEstado); panelFiltro.Controls.Add(lblFiltro); panelFiltro.Controls.Add(buscador); lblFiltro.AutoSize = true; lblFiltro.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblFiltro.Location = new Point(310, 7); lblFiltro.Text = "Mostrar"; buscador.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right; buscador.BorderStyle = BorderStyle.FixedSingle; buscador.Location = new Point(0, 22); buscador.Size = new Size(285, 26); filtroEstado.DropDownStyle = ComboBoxStyle.DropDownList; filtroEstado.Location = new Point(310, 22); filtroEstado.Size = new Size(190, 26); filtroEstado.Items.AddRange(new object[] { "Todas", "Pendientes", "Pagadas" }); filtroEstado.SelectedIndex = 0;
            tabla.AllowUserToAddRows = false; tabla.AllowUserToDeleteRows = false; tabla.AllowUserToResizeRows = false; tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; tabla.BackgroundColor = Color.White; tabla.BorderStyle = BorderStyle.None; tabla.ColumnHeadersHeight = 38; tabla.Dock = DockStyle.Fill; tabla.MultiSelect = false; tabla.ReadOnly = true; tabla.RowHeadersVisible = false; tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect; tabla.Columns.AddRange(new DataGridViewColumn[] { colIdCuota, colIdPago, colSocio, colDni, colPlan, colPeriodo, colImporte, colEstadoTabla }); colIdCuota.HeaderText = "IdCuota"; colIdCuota.Name = "colIdCuota"; colIdCuota.Visible = false; colIdPago.HeaderText = "IdPago"; colIdPago.Name = "colIdPago"; colIdPago.Visible = false; colSocio.HeaderText = "Socio"; colSocio.Name = "colSocio"; colDni.HeaderText = "DNI"; colDni.Name = "colDni"; colPlan.HeaderText = "Plan"; colPlan.Name = "colPlan"; colPeriodo.HeaderText = "Periodo"; colPeriodo.Name = "colPeriodo"; colImporte.HeaderText = "Importe"; colImporte.Name = "colImporte"; colEstadoTabla.HeaderText = "Estado"; colEstadoTabla.Name = "colEstadoTabla";
            panelDetalle.BackColor = Color.White; panelDetalle.BorderStyle = BorderStyle.FixedSingle; panelDetalle.Dock = DockStyle.Fill; panelDetalle.Padding = new Padding(16); panelDetalle.Controls.Add(layoutDetalle); layoutDetalle.ColumnCount = 1; layoutDetalle.Dock = DockStyle.Fill; layoutDetalle.RowCount = 3; layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F)); layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Absolute, 124F)); layoutDetalle.Controls.Add(lblFormulario, 0, 0); layoutDetalle.Controls.Add(layoutCampos, 0, 1); layoutDetalle.Controls.Add(panelAcciones, 0, 2); lblFormulario.AutoSize = true; lblFormulario.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold); lblFormulario.ForeColor = Color.FromArgb(30, 41, 59); lblFormulario.Text = "Nuevo pago";
            layoutCampos.ColumnCount = 2; layoutCampos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42F)); layoutCampos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58F)); layoutCampos.Dock = DockStyle.Top; layoutCampos.RowCount = 5; layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.Controls.Add(lblMembresia, 0, 0); layoutCampos.Controls.Add(membresia, 1, 0); layoutCampos.Controls.Add(lblCuota, 0, 1); layoutCampos.Controls.Add(cuota, 1, 1); layoutCampos.Controls.Add(lblImporte, 0, 2); layoutCampos.Controls.Add(importe, 1, 2); layoutCampos.Controls.Add(lblMetodo, 0, 3); layoutCampos.Controls.Add(metodo, 1, 3); layoutCampos.Controls.Add(lblEstadoPago, 0, 4); layoutCampos.Controls.Add(estado, 1, 4); membresia.Dock = DockStyle.Fill; membresia.DropDownStyle = ComboBoxStyle.DropDownList; cuota.Dock = DockStyle.Fill; cuota.ReadOnly = true; cuota.BackColor = Color.FromArgb(241, 245, 249); importe.Dock = DockStyle.Fill; importe.BorderStyle = BorderStyle.FixedSingle; metodo.Dock = DockStyle.Fill; metodo.DropDownStyle = ComboBoxStyle.DropDownList; estado.Dock = DockStyle.Fill; estado.DropDownStyle = ComboBoxStyle.DropDownList; estado.Items.AddRange(new object[] { "Pendiente", "Aprobado", "Rechazado" }); estado.SelectedIndex = 1;
            panelAcciones.Dock = DockStyle.Fill; panelAcciones.Controls.Add(nuevo); panelAcciones.Controls.Add(registrar); panelAcciones.Controls.Add(anular); panelAcciones.Controls.Add(reembolsar);
            panelEncabezado.Location = new Point(0, 0); panelEncabezado.Name = "panelEncabezado"; panelEncabezado.Size = new Size(1100, 80); panelEncabezado.TabIndex = 0; lblTitulo.Name = "lblTitulo"; lblTitulo.Size = new Size(211, 32); lblTitulo.TabIndex = 0; lblDescripcion.Name = "lblDescripcion"; lblDescripcion.Size = new Size(263, 17); lblDescripcion.TabIndex = 1; btnVolver.Name = "btnVolver"; btnVolver.TabIndex = 2;
            barraAcciones.BackColor = Color.White; barraAcciones.Dock = DockStyle.Top; barraAcciones.Location = new Point(0, 80); barraAcciones.Name = "barraAcciones"; barraAcciones.Padding = new Padding(16, 8, 16, 8); barraAcciones.Size = new Size(1100, 52); barraAcciones.TabIndex = 1; barraAcciones.WrapContents = false;
            lblEstado.Location = new Point(0, 648); lblEstado.Name = "lblEstado"; lblEstado.Size = new Size(1100, 32); lblEstado.TabIndex = 3; panelContenido.Location = new Point(0, 132); panelContenido.Name = "panelContenido"; panelContenido.Size = new Size(1100, 516); panelContenido.TabIndex = 2; layoutContenido.Location = new Point(12, 12); layoutContenido.Name = "layoutContenido"; layoutContenido.RowCount = 1; layoutContenido.RowStyles.Add(new RowStyle(SizeType.Percent, 100F)); layoutContenido.Size = new Size(1076, 492); layoutContenido.TabIndex = 0;
            panelListado.Name = "panelListado"; panelListado.TabIndex = 0; lblListado.Name = "lblListado"; lblListado.Size = new Size(57, 20); lblListado.TabIndex = 0; lblAyuda.Name = "lblAyuda"; lblAyuda.Size = new Size(178, 17); lblAyuda.TabIndex = 1; panelFiltro.Name = "panelFiltro"; panelFiltro.TabIndex = 2; lblFiltro.ForeColor = Color.FromArgb(71, 85, 105); lblFiltro.Name = "lblFiltro"; lblFiltro.TabIndex = 1; buscador.Name = "buscador"; buscador.TabIndex = 0; filtroEstado.Name = "filtroEstado"; filtroEstado.TabIndex = 2;
            tabla.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right; tabla.Dock = DockStyle.None; tabla.Location = new Point(16, 128); tabla.Name = "tabla"; tabla.Size = new Size(577, 346); tabla.TabIndex = 3; colIdCuota.Width = 50; colIdPago.Width = 50; colSocio.Width = 125; colDni.Width = 80; colPlan.Width = 90; colPeriodo.Width = 125; colImporte.Width = 90; colEstadoTabla.Width = 85;
            panelDetalle.Name = "panelDetalle"; panelDetalle.TabIndex = 1; layoutDetalle.Name = "layoutDetalle"; layoutDetalle.TabIndex = 0; lblFormulario.Name = "lblFormulario"; lblFormulario.Size = new Size(117, 21); lblFormulario.TabIndex = 0; layoutCampos.Name = "layoutCampos"; layoutCampos.Size = new Size(414, 210); layoutCampos.TabIndex = 1; panelAcciones.Name = "panelAcciones"; panelAcciones.TabIndex = 2;
            lblMembresia.Anchor = AnchorStyles.Left; lblMembresia.AutoSize = true; lblMembresia.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblMembresia.ForeColor = Color.FromArgb(51, 65, 85); lblMembresia.Name = "lblMembresia"; lblMembresia.Text = "Membresia:"; lblCuota.Anchor = AnchorStyles.Left; lblCuota.AutoSize = true; lblCuota.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblCuota.ForeColor = Color.FromArgb(51, 65, 85); lblCuota.Name = "lblCuota"; lblCuota.Text = "Cuota:"; lblImporte.Anchor = AnchorStyles.Left; lblImporte.AutoSize = true; lblImporte.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblImporte.ForeColor = Color.FromArgb(51, 65, 85); lblImporte.Name = "lblImporte"; lblImporte.Text = "Importe:"; lblMetodo.Anchor = AnchorStyles.Left; lblMetodo.AutoSize = true; lblMetodo.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblMetodo.ForeColor = Color.FromArgb(51, 65, 85); lblMetodo.Name = "lblMetodo"; lblMetodo.Text = "Metodo:"; lblEstadoPago.Anchor = AnchorStyles.Left; lblEstadoPago.AutoSize = true; lblEstadoPago.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblEstadoPago.ForeColor = Color.FromArgb(51, 65, 85); lblEstadoPago.Name = "lblEstadoPago"; lblEstadoPago.Text = "Estado:";
            membresia.Margin = new Padding(0, 4, 0, 4); membresia.Name = "membresia"; cuota.BorderStyle = BorderStyle.FixedSingle; cuota.Margin = new Padding(0, 4, 0, 4); cuota.Name = "cuota"; importe.Margin = new Padding(0, 4, 0, 4); importe.Name = "importe"; metodo.Margin = new Padding(0, 4, 0, 4); metodo.Name = "metodo"; estado.Margin = new Padding(0, 4, 0, 4); estado.Name = "estado";
            nuevo.BackColor = Color.FromArgb(5, 150, 105); nuevo.FlatAppearance.BorderSize = 0; nuevo.FlatStyle = FlatStyle.Flat; nuevo.ForeColor = Color.White; nuevo.Location = new Point(0, 2); nuevo.Name = "nuevo"; nuevo.Size = new Size(100, 32); nuevo.Text = "+ Nuevo pago"; nuevo.UseVisualStyleBackColor = false; registrar.BackColor = Color.FromArgb(5, 150, 105); registrar.FlatAppearance.BorderSize = 0; registrar.FlatStyle = FlatStyle.Flat; registrar.ForeColor = Color.White; registrar.Location = new Point(0, 44); registrar.Name = "registrar"; registrar.Size = new Size(100, 32); registrar.Text = "Registrar"; registrar.UseVisualStyleBackColor = false; anular.BackColor = Color.FromArgb(254, 242, 242); anular.FlatAppearance.BorderSize = 0; anular.FlatStyle = FlatStyle.Flat; anular.ForeColor = Color.FromArgb(185, 28, 28); anular.Location = new Point(104, 44); anular.Name = "anular"; anular.Size = new Size(100, 32); anular.Text = "Anular"; anular.UseVisualStyleBackColor = false; reembolsar.BackColor = Color.FromArgb(226, 232, 240); reembolsar.FlatAppearance.BorderSize = 0; reembolsar.FlatStyle = FlatStyle.Flat; reembolsar.ForeColor = Color.FromArgb(30, 41, 59); reembolsar.Location = new Point(0, 84); reembolsar.Name = "reembolsar"; reembolsar.Size = new Size(100, 32); reembolsar.Text = "Reembolsar"; reembolsar.UseVisualStyleBackColor = false;
            Controls.Add(panelContenido); Controls.Add(lblEstado); Controls.Add(barraAcciones); Controls.Add(panelEncabezado); AutoScaleMode = AutoScaleMode.Font; BackColor = Color.FromArgb(241, 245, 249); ClientSize = new Size(1100, 680); Font = new Font("Segoe UI", 9.5F); MinimumSize = new Size(760, 540); Name = "GestionPagosForm"; StartPosition = FormStartPosition.CenterParent; Text = "SysGym | Cuotas y pagos"; nuevo.Click += NuevoPago; registrar.Click += Registrar; anular.Click += Anular; reembolsar.Click += Reembolsar;
            panelEncabezado.ResumeLayout(false); panelEncabezado.PerformLayout(); panelContenido.ResumeLayout(false); layoutContenido.ResumeLayout(false); panelListado.ResumeLayout(false); panelListado.PerformLayout(); panelFiltro.ResumeLayout(false); panelFiltro.PerformLayout(); ((ISupportInitialize)(tabla)).EndInit(); panelDetalle.ResumeLayout(false); layoutDetalle.ResumeLayout(false); layoutDetalle.PerformLayout(); layoutCampos.ResumeLayout(false); layoutCampos.PerformLayout(); panelAcciones.ResumeLayout(false); ResumeLayout(false);
        }

    }
}
