namespace exxen2._0.capaVisual.Compartido
{
    partial class FichaSocioFormulario
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (fotoSocio != null && fotoSocio.Image != null) fotoSocio.Image.Dispose();
                if (components != null) components.Dispose();
            }
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.disposicion = new System.Windows.Forms.TableLayoutPanel();
            this.encabezado = new System.Windows.Forms.Panel();
            this.secciones = new System.Windows.Forms.TableLayoutPanel();
            this.acciones = new System.Windows.Forms.TableLayoutPanel();
            this.fotoSocio = new System.Windows.Forms.PictureBox();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblNombre = new System.Windows.Forms.Label();
            this.lblDatos = new System.Windows.Forms.Label();
            this.lblMembresia = new System.Windows.Forms.Label();
            this.lblEntrenador = new System.Windows.Forms.Label();
            this.lblRutina = new System.Windows.Forms.Label();
            this.lblFinanzas = new System.Windows.Forms.Label();
            this.lblEstado = new System.Windows.Forms.Label();
            this.tabla = new System.Windows.Forms.DataGridView();
            this.btnHistorial = new System.Windows.Forms.Button();
            this.btnPago = new System.Windows.Forms.Button();
            this.btnMembresia = new System.Windows.Forms.Button();
            this.btnRutina = new System.Windows.Forms.Button();
            this.btnExportarPago = new System.Windows.Forms.Button();
            this.btnExportarTodos = new System.Windows.Forms.Button();
            this.dialogoPdf = new System.Windows.Forms.SaveFileDialog();
            this.colFecha = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colPeriodo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colMetodo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colImporte = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.colRegistrador = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.disposicion.SuspendLayout();
            this.encabezado.SuspendLayout();
            this.secciones.SuspendLayout();
            this.acciones.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.fotoSocio)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).BeginInit();
            this.SuspendLayout();
            this.disposicion.Name = "disposicion";
            this.encabezado.Name = "encabezado";
            this.secciones.Name = "secciones";
            this.acciones.Name = "acciones";
            this.acciones.ColumnCount = 3;
            this.acciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.3333F));
            this.acciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.3333F));
            this.acciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.3334F));
            this.acciones.RowCount = 2;
            this.acciones.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.acciones.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.fotoSocio.Name = "fotoSocio";
            this.lblTitulo.Name = "lblTitulo";
            this.lblNombre.Name = "lblNombre";
            this.lblDatos.Name = "lblDatos";
            this.lblMembresia.Name = "lblMembresia";
            this.lblEntrenador.Name = "lblEntrenador";
            this.lblRutina.Name = "lblRutina";
            this.lblFinanzas.Name = "lblFinanzas";
            this.lblEstado.Name = "lblEstado";
            this.tabla.Name = "tabla";
            this.btnHistorial.Name = "btnHistorial";
            this.btnHistorial.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.btnHistorial.FlatAppearance.BorderSize = 0;
            this.btnHistorial.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.btnHistorial.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.btnHistorial.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnHistorial.ForeColor = System.Drawing.Color.White;
            this.btnHistorial.UseVisualStyleBackColor = false;
            this.btnPago.Name = "btnPago";
            this.btnPago.BackColor = System.Drawing.Color.FromArgb(46, 125, 50);
            this.btnPago.FlatAppearance.BorderSize = 0;
            this.btnPago.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(27, 75, 31);
            this.btnPago.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(37, 101, 41);
            this.btnPago.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnPago.ForeColor = System.Drawing.Color.White;
            this.btnPago.UseVisualStyleBackColor = false;
            this.btnMembresia.Name = "btnMembresia";
            this.btnMembresia.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.btnMembresia.FlatAppearance.BorderSize = 0;
            this.btnMembresia.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.btnMembresia.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.btnMembresia.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnMembresia.ForeColor = System.Drawing.Color.White;
            this.btnMembresia.UseVisualStyleBackColor = false;
            this.btnRutina.Name = "btnRutina";
            this.btnRutina.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.btnRutina.FlatAppearance.BorderSize = 0;
            this.btnRutina.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.btnRutina.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.btnRutina.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRutina.ForeColor = System.Drawing.Color.White;
            this.btnRutina.UseVisualStyleBackColor = false;
            this.btnExportarPago.Name = "btnExportarPago";
            this.btnExportarPago.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.btnExportarPago.FlatAppearance.BorderSize = 0;
            this.btnExportarPago.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.btnExportarPago.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.btnExportarPago.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExportarPago.ForeColor = System.Drawing.Color.White;
            this.btnExportarPago.UseVisualStyleBackColor = false;
            this.btnExportarTodos.Name = "btnExportarTodos";
            this.btnExportarTodos.BackColor = System.Drawing.Color.FromArgb(91, 75, 138);
            this.btnExportarTodos.FlatAppearance.BorderSize = 0;
            this.btnExportarTodos.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(58, 48, 89);
            this.btnExportarTodos.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(74, 61, 112);
            this.btnExportarTodos.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnExportarTodos.ForeColor = System.Drawing.Color.White;
            this.btnExportarTodos.UseVisualStyleBackColor = false;
            this.disposicion.ColumnCount = 1;
            this.disposicion.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.disposicion.RowCount = 7;
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 32F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 120F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 130F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 100F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 86F));
            this.disposicion.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.disposicion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Padding = new System.Windows.Forms.Padding(12);
            this.disposicion.Size = new System.Drawing.Size(1000, 700);
            this.disposicion.MinimumSize = new System.Drawing.Size(850, 620);
            this.disposicion.Controls.Add(this.lblTitulo, 0, 0);
            this.lblTitulo.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Controls.Add(this.encabezado, 0, 1);
            this.encabezado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Controls.Add(this.secciones, 0, 2);
            this.secciones.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Controls.Add(this.lblFinanzas, 0, 3);
            this.lblFinanzas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Controls.Add(this.tabla, 0, 4);
            this.tabla.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Controls.Add(this.acciones, 0, 5);
            this.acciones.Dock = System.Windows.Forms.DockStyle.Fill;
            this.disposicion.Controls.Add(this.lblEstado, 0, 6);
            this.lblEstado.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblTitulo.Text = "FICHA DEL SOCIO";
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI", 15F, System.Drawing.FontStyle.Bold);
            this.fotoSocio.Location = new System.Drawing.Point(0, 4);
            this.fotoSocio.Size = new System.Drawing.Size(104, 104);
            this.fotoSocio.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.lblNombre.Location = new System.Drawing.Point(120, 2);
            this.lblNombre.Size = new System.Drawing.Size(820, 32);
            this.lblNombre.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblDatos.Location = new System.Drawing.Point(120, 36);
            this.lblDatos.Size = new System.Drawing.Size(820, 76);
            this.lblDatos.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.lblNombre.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.lblNombre.Text = "Nombre y apellido";
            this.lblDatos.Text = "DNI · Estado\r\nNacimiento · Alta · Antigüedad";
            this.encabezado.Controls.Add(this.fotoSocio);
            this.encabezado.Controls.Add(this.lblNombre);
            this.encabezado.Controls.Add(this.lblDatos);
            this.secciones.ColumnCount = 3;
            this.secciones.RowCount = 1;
            this.secciones.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.secciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 44F));
            this.secciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28F));
            this.secciones.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 28F));
            this.secciones.Controls.Add(this.lblMembresia, 0, 0);
            this.lblMembresia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblMembresia.Padding = new System.Windows.Forms.Padding(8);
            this.lblMembresia.BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            this.secciones.Controls.Add(this.lblEntrenador, 1, 0);
            this.lblEntrenador.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblEntrenador.Padding = new System.Windows.Forms.Padding(8);
            this.lblEntrenador.BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            this.secciones.Controls.Add(this.lblRutina, 2, 0);
            this.lblRutina.Dock = System.Windows.Forms.DockStyle.Fill;
            this.lblRutina.Padding = new System.Windows.Forms.Padding(8);
            this.lblRutina.BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            this.lblMembresia.Text = "MEMBRESÍA\r\nPlan · Estado\r\nInicio · Cuotas hasta\r\nDeuda · Límite";
            this.lblEntrenador.Text = "ENTRENADOR\r\nSin asignar";
            this.lblRutina.Text = "RUTINA\r\nSin rutina";
            this.lblFinanzas.Text = "RESUMEN FINANCIERO\r\nTotal abonado · Pagos · Cuotas pagadas\r\nDeuda · Pendientes · Vencidas\r\nÚltimo pago · Próximo vencimiento";
            this.lblFinanzas.Padding = new System.Windows.Forms.Padding(4, 8, 4, 0);
            this.tabla.AllowUserToAddRows = false;
            this.tabla.AllowUserToDeleteRows = false;
            this.tabla.ReadOnly = true;
            this.tabla.MultiSelect = false;
            this.tabla.RowHeadersVisible = false;
            this.tabla.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.tabla.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.tabla.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.tabla.BackgroundColor = System.Drawing.Color.White;
            this.tabla.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.colFecha, this.colPeriodo, this.colMetodo, this.colImporte, this.colRegistrador });
            this.colFecha.Name = "colFecha";
            this.colFecha.HeaderText = "Fecha";
            this.colFecha.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colPeriodo.Name = "colPeriodo";
            this.colPeriodo.HeaderText = "Período";
            this.colPeriodo.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colMetodo.Name = "colMetodo";
            this.colMetodo.HeaderText = "Método";
            this.colMetodo.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colImporte.Name = "colImporte";
            this.colImporte.HeaderText = "Importe";
            this.colImporte.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colRegistrador.Name = "colRegistrador";
            this.colRegistrador.HeaderText = "Registrado por";
            this.colRegistrador.SortMode = System.Windows.Forms.DataGridViewColumnSortMode.NotSortable;
            this.colPeriodo.FillWeight = 145F;
            this.colRegistrador.FillWeight = 150F;
            this.colRegistrador.DefaultCellStyle.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.tabla.SelectionChanged += new System.EventHandler(this.tabla_SelectionChanged);
            this.btnHistorial.Text = "Ver historial completo";
            this.btnHistorial.Size = new System.Drawing.Size(165, 34);
            this.btnHistorial.Enabled = false;
            this.btnHistorial.TabIndex = 0;
            this.btnHistorial.Click += new System.EventHandler(this.btnHistorial_Click);
            this.acciones.Controls.Add(this.btnHistorial, 0, 0);
            this.btnHistorial.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnHistorial.Margin = new System.Windows.Forms.Padding(3);
            this.btnPago.Text = "Registrar pago";
            this.btnPago.Size = new System.Drawing.Size(130, 34);
            this.btnPago.Enabled = false;
            this.btnPago.TabIndex = 1;
            this.btnPago.Click += new System.EventHandler(this.btnPago_Click);
            this.acciones.Controls.Add(this.btnPago, 1, 0);
            this.btnPago.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnPago.Margin = new System.Windows.Forms.Padding(3);
            this.btnMembresia.Text = "Ver membresía";
            this.btnMembresia.Size = new System.Drawing.Size(130, 34);
            this.btnMembresia.Enabled = false;
            this.btnMembresia.TabIndex = 2;
            this.btnMembresia.Click += new System.EventHandler(this.btnMembresia_Click);
            this.acciones.Controls.Add(this.btnMembresia, 2, 0);
            this.btnMembresia.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnMembresia.Margin = new System.Windows.Forms.Padding(3);
            this.btnRutina.Text = "Ver rutina";
            this.btnRutina.Size = new System.Drawing.Size(110, 34);
            this.btnRutina.Enabled = false;
            this.btnRutina.TabIndex = 3;
            this.btnRutina.Click += new System.EventHandler(this.btnRutina_Click);
            this.acciones.Controls.Add(this.btnRutina, 0, 1);
            this.btnRutina.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnRutina.Margin = new System.Windows.Forms.Padding(3);
            this.btnExportarPago.Text = "Exportar pago seleccionado";
            this.btnExportarPago.Size = new System.Drawing.Size(210, 34);
            this.btnExportarPago.Enabled = false;
            this.btnExportarPago.TabIndex = 4;
            this.btnExportarPago.Click += new System.EventHandler(this.btnExportarPago_Click);
            this.acciones.Controls.Add(this.btnExportarPago, 1, 1);
            this.btnExportarPago.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnExportarPago.Margin = new System.Windows.Forms.Padding(3);
            this.btnExportarTodos.Text = "Exportar todos los pagos";
            this.btnExportarTodos.Size = new System.Drawing.Size(200, 34);
            this.btnExportarTodos.Enabled = false;
            this.btnExportarTodos.TabIndex = 5;
            this.btnExportarTodos.Click += new System.EventHandler(this.btnExportarTodos_Click);
            this.acciones.Controls.Add(this.btnExportarTodos, 2, 1);
            this.btnExportarTodos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.btnExportarTodos.Margin = new System.Windows.Forms.Padding(3);
            this.lblEstado.Text = "Seleccioná un socio para consultar su ficha.";
            this.dialogoPdf.DefaultExt = "pdf";
            this.dialogoPdf.Filter = "Documento PDF (*.pdf)|*.pdf";
            this.dialogoPdf.Title = "Guardar reporte de pagos";
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.ClientSize = new System.Drawing.Size(1000, 700);
            this.MinimumSize = new System.Drawing.Size(900, 660);
            this.Controls.Add(this.disposicion);
            this.Name = "FichaSocioFormulario";
            this.Text = "SysGym";
            this.Load += new System.EventHandler(this.FichaSocioFormulario_Load);
            ((System.ComponentModel.ISupportInitialize)(this.fotoSocio)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tabla)).EndInit();
            this.encabezado.ResumeLayout(false);
            this.secciones.ResumeLayout(false);
            this.acciones.ResumeLayout(false);
            this.disposicion.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        private System.Windows.Forms.TableLayoutPanel disposicion;
        private System.Windows.Forms.Panel encabezado;
        private System.Windows.Forms.TableLayoutPanel secciones;
        private System.Windows.Forms.TableLayoutPanel acciones;
        private System.Windows.Forms.PictureBox fotoSocio;
        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblNombre;
        private System.Windows.Forms.Label lblDatos;
        private System.Windows.Forms.Label lblMembresia;
        private System.Windows.Forms.Label lblEntrenador;
        private System.Windows.Forms.Label lblRutina;
        private System.Windows.Forms.Label lblFinanzas;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.DataGridView tabla;
        private System.Windows.Forms.Button btnHistorial;
        private System.Windows.Forms.Button btnPago;
        private System.Windows.Forms.Button btnMembresia;
        private System.Windows.Forms.Button btnRutina;
        private System.Windows.Forms.Button btnExportarPago;
        private System.Windows.Forms.Button btnExportarTodos;
        private System.Windows.Forms.SaveFileDialog dialogoPdf;
        private System.Windows.Forms.DataGridViewTextBoxColumn colFecha;
        private System.Windows.Forms.DataGridViewTextBoxColumn colPeriodo;
        private System.Windows.Forms.DataGridViewTextBoxColumn colMetodo;
        private System.Windows.Forms.DataGridViewTextBoxColumn colImporte;
        private System.Windows.Forms.DataGridViewTextBoxColumn colRegistrador;
    }
}
