using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace exxen2._0.capaVisual.Compartido
{
    partial class GestionSociosForm
    {
        private IContainer components;
        private Panel panelEncabezado;
        private Label lblTitulo;
        private Label lblDescripcion;
        private Button btnVolver;
        private FlowLayoutPanel barraAcciones;
        private Label lblEstado;
        private TextBox nombre;
        private TextBox apellido;
        private TextBox dni;
        private DateTimePicker fechaNacimiento;
        private TextBox peso;
        private TextBox altura;
        private Button nuevo;
        private Button guardar;
        private Button actualizar;
        private Button darDeBaja;
        private Button reactivar;
        private Button calcularImc;
        private ComboBox filtroEstado;
        private TextBox buscador;
        private Panel panelContenido;
        private TableLayoutPanel layoutContenido;
        private Panel panelListado;
        private Label lblListado;
        private Label lblAyuda;
        private Panel panelFiltro;
        private Label lblFiltro;
        private Panel panelDetalle;
        private TableLayoutPanel layoutDetalle;
        private TableLayoutPanel layoutCampos;
        private Panel panelAcciones;
        private Label lblFormulario;
        private Label lblNombre;
        private Label lblApellido;
        private Label lblDni;
        private Label lblFechaNacimiento;
        private Label lblPeso;
        private Label lblAltura;
        private DataGridView tabla;
        private DataGridViewTextBoxColumn colId;
        private DataGridViewTextBoxColumn colNombre;
        private DataGridViewTextBoxColumn colDni;
        private DataGridViewTextBoxColumn colNacimiento;
        private DataGridViewTextBoxColumn colEstado;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new Container();
            panelEncabezado = new Panel();
            lblTitulo = new Label();
            lblDescripcion = new Label();
            btnVolver = new Button();
            barraAcciones = new FlowLayoutPanel();
            lblEstado = new Label();
            panelContenido = new Panel();
            layoutContenido = new TableLayoutPanel();
            panelListado = new Panel();
            lblListado = new Label();
            lblAyuda = new Label();
            panelFiltro = new Panel();
            lblFiltro = new Label();
            buscador = new TextBox();
            filtroEstado = new ComboBox();
            tabla = new DataGridView();
            colId = new DataGridViewTextBoxColumn();
            colNombre = new DataGridViewTextBoxColumn();
            colDni = new DataGridViewTextBoxColumn();
            colNacimiento = new DataGridViewTextBoxColumn();
            colEstado = new DataGridViewTextBoxColumn();
            panelDetalle = new Panel();
            layoutDetalle = new TableLayoutPanel();
            lblFormulario = new Label();
            layoutCampos = new TableLayoutPanel();
            lblNombre = new Label();
            nombre = new TextBox();
            lblApellido = new Label();
            apellido = new TextBox();
            lblDni = new Label();
            dni = new TextBox();
            lblFechaNacimiento = new Label();
            fechaNacimiento = new DateTimePicker();
            lblPeso = new Label();
            peso = new TextBox();
            lblAltura = new Label();
            altura = new TextBox();
            panelAcciones = new Panel();
            nuevo = new Button();
            guardar = new Button();
            actualizar = new Button();
            darDeBaja = new Button();
            reactivar = new Button();
            calcularImc = new Button();
            panelEncabezado.SuspendLayout();
            panelContenido.SuspendLayout();
            layoutContenido.SuspendLayout();
            panelListado.SuspendLayout();
            panelFiltro.SuspendLayout();
            ((ISupportInitialize)(tabla)).BeginInit();
            panelDetalle.SuspendLayout();
            layoutDetalle.SuspendLayout();
            layoutCampos.SuspendLayout();
            panelAcciones.SuspendLayout();
            SuspendLayout();

            panelEncabezado.BackColor = Color.FromArgb(79, 70, 229);
            panelEncabezado.Dock = DockStyle.Top;
            panelEncabezado.Height = 80;
            panelEncabezado.Controls.Add(lblDescripcion);
            panelEncabezado.Controls.Add(lblTitulo);
            panelEncabezado.Controls.Add(btnVolver);
            lblTitulo.AutoSize = true;
            lblTitulo.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblTitulo.ForeColor = Color.White;
            lblTitulo.Location = new Point(22, 10);
            lblTitulo.Text = "Socios";
            lblDescripcion.AutoSize = true;
            lblDescripcion.Font = new Font("Segoe UI", 9.5F);
            lblDescripcion.ForeColor = Color.FromArgb(226, 232, 240);
            lblDescripcion.Location = new Point(24, 47);
            lblDescripcion.Text = "Alta, actualizacion, baja logica y consulta de IMC";
            btnVolver.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnVolver.BackColor = Color.White;
            btnVolver.FlatStyle = FlatStyle.Flat;
            btnVolver.FlatAppearance.BorderSize = 0;
            btnVolver.Font = new Font("Segoe UI Semibold", 9.5F, FontStyle.Bold);
            btnVolver.ForeColor = Color.FromArgb(79, 70, 229);
            btnVolver.Location = new Point(930, 22);
            btnVolver.Size = new Size(92, 34);
            btnVolver.Text = "Volver";
            btnVolver.UseVisualStyleBackColor = false;

            barraAcciones.BackColor = Color.White;
            barraAcciones.Dock = DockStyle.Top;
            barraAcciones.Height = 52;
            barraAcciones.Padding = new Padding(16, 8, 16, 8);
            barraAcciones.Visible = true;
            lblEstado.AutoSize = false; lblEstado.BackColor = Color.FromArgb(226, 232, 240); lblEstado.Dock = DockStyle.Bottom; lblEstado.ForeColor = Color.FromArgb(51, 65, 85); lblEstado.Height = 32; lblEstado.Padding = new Padding(18, 8, 8, 0); lblEstado.Text = "Listo";
            panelContenido.BackColor = Color.FromArgb(248, 250, 252);
            panelContenido.Dock = DockStyle.Fill;
            panelContenido.Padding = new Padding(12);
            layoutContenido.ColumnCount = 2;
            layoutContenido.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 56F));
            layoutContenido.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 44F));
            layoutContenido.Dock = DockStyle.Fill;
            layoutContenido.RowCount = 1;
            layoutContenido.Controls.Add(panelListado, 0, 0);
            layoutContenido.Controls.Add(panelDetalle, 1, 0);
            panelContenido.Controls.Add(layoutContenido);

            panelListado.BackColor = Color.White;
            panelListado.BorderStyle = BorderStyle.FixedSingle;
            panelListado.Dock = DockStyle.Fill;
            panelListado.Padding = new Padding(16);
            panelListado.Controls.Add(tabla);
            panelListado.Controls.Add(panelFiltro);
            panelListado.Controls.Add(lblAyuda);
            panelListado.Controls.Add(lblListado);
            lblListado.AutoSize = true;
            lblListado.Font = new Font("Segoe UI Semibold", 11F, FontStyle.Bold);
            lblListado.ForeColor = Color.FromArgb(30, 41, 59);
            lblListado.Location = new Point(16, 14);
            lblListado.Text = "Listado de socios";
            lblAyuda.AutoSize = true;
            lblAyuda.ForeColor = Color.FromArgb(100, 116, 139);
            lblAyuda.Location = new Point(16, 42);
            lblAyuda.Text = "Busca por nombre o DNI";
            panelFiltro.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            panelFiltro.BackColor = Color.White;
            panelFiltro.Location = new Point(16, 68);
            panelFiltro.Size = new Size(560, 54);
            panelFiltro.Controls.Add(filtroEstado);
            panelFiltro.Controls.Add(lblFiltro);
            panelFiltro.Controls.Add(buscador);
            lblFiltro.AutoSize = true;
            lblFiltro.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold);
            lblFiltro.ForeColor = Color.FromArgb(71, 85, 105);
            lblFiltro.Location = new Point(310, 7);
            lblFiltro.Text = "Estado";
            buscador.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            buscador.BorderStyle = BorderStyle.FixedSingle;
            buscador.Location = new Point(0, 22);
            buscador.Size = new Size(285, 26);
            filtroEstado.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            filtroEstado.DropDownStyle = ComboBoxStyle.DropDownList;
            filtroEstado.Location = new Point(310, 22);
            filtroEstado.Size = new Size(190, 26);
            filtroEstado.Items.AddRange(new object[] { "Todos", "Activos", "Inactivos" });
            filtroEstado.SelectedIndex = 0;
            tabla.AllowUserToAddRows = false;
            tabla.AllowUserToDeleteRows = false;
            tabla.AllowUserToResizeRows = false;
            tabla.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            tabla.BackgroundColor = Color.White;
            tabla.BorderStyle = BorderStyle.None;
            tabla.ColumnHeadersHeight = 38;
            tabla.Dock = DockStyle.Fill;
            tabla.MultiSelect = false;
            tabla.ReadOnly = true;
            tabla.RowHeadersVisible = false;
            tabla.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            tabla.Columns.AddRange(new DataGridViewColumn[] { colId, colNombre, colDni, colNacimiento, colEstado });
            colId.HeaderText = "Id"; colId.Name = "colId"; colId.Visible = false;
            colNombre.HeaderText = "Nombre"; colNombre.Name = "colNombre"; colNombre.FillWeight = 150;
            colDni.HeaderText = "DNI"; colDni.Name = "colDni"; colDni.FillWeight = 95;
            colNacimiento.HeaderText = "Nacimiento"; colNacimiento.Name = "colNacimiento"; colNacimiento.FillWeight = 95;
            colEstado.HeaderText = "Estado"; colEstado.Name = "colEstado"; colEstado.FillWeight = 70;

            panelDetalle.BackColor = Color.White;
            panelDetalle.BorderStyle = BorderStyle.FixedSingle;
            panelDetalle.Dock = DockStyle.Fill;
            panelDetalle.Padding = new Padding(16);
            layoutDetalle.ColumnCount = 1;
            layoutDetalle.Dock = DockStyle.Fill;
            layoutDetalle.RowCount = 3;
            layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            layoutDetalle.RowStyles.Add(new RowStyle(SizeType.Absolute, 124F));
            layoutDetalle.Controls.Add(lblFormulario, 0, 0);
            layoutDetalle.Controls.Add(layoutCampos, 0, 1);
            layoutDetalle.Controls.Add(panelAcciones, 0, 2);
            panelDetalle.Controls.Add(layoutDetalle);
            lblFormulario.AutoSize = true;
            lblFormulario.Font = new Font("Segoe UI Semibold", 12F, FontStyle.Bold);
            lblFormulario.ForeColor = Color.FromArgb(30, 41, 59);
            lblFormulario.Text = "Nuevo socio";
            layoutCampos.ColumnCount = 2;
            layoutCampos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 38F));
            layoutCampos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 62F));
            layoutCampos.Dock = DockStyle.Top;
            layoutCampos.RowCount = 6;
            layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F)); layoutCampos.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            layoutCampos.Controls.Add(lblNombre, 0, 0); layoutCampos.Controls.Add(nombre, 1, 0);
            layoutCampos.Controls.Add(lblApellido, 0, 1); layoutCampos.Controls.Add(apellido, 1, 1);
            layoutCampos.Controls.Add(lblDni, 0, 2); layoutCampos.Controls.Add(dni, 1, 2);
            layoutCampos.Controls.Add(lblFechaNacimiento, 0, 3); layoutCampos.Controls.Add(fechaNacimiento, 1, 3);
            layoutCampos.Controls.Add(lblPeso, 0, 4); layoutCampos.Controls.Add(peso, 1, 4);
            layoutCampos.Controls.Add(lblAltura, 0, 5); layoutCampos.Controls.Add(altura, 1, 5);
            fechaNacimiento.Format = DateTimePickerFormat.Short;
            fechaNacimiento.ShowCheckBox = true;
            fechaNacimiento.Dock = DockStyle.Fill;
            panelAcciones.Dock = DockStyle.Fill;
            panelAcciones.Controls.Add(calcularImc); panelAcciones.Controls.Add(reactivar); panelAcciones.Controls.Add(darDeBaja);
            panelAcciones.Controls.Add(actualizar); panelAcciones.Controls.Add(guardar); panelAcciones.Controls.Add(nuevo);
            panelEncabezado.Location = new Point(0, 0); panelEncabezado.Name = "panelEncabezado"; panelEncabezado.Size = new Size(1100, 80); panelEncabezado.TabIndex = 0; lblTitulo.Name = "lblTitulo"; lblTitulo.Size = new Size(91, 32); lblTitulo.TabIndex = 0; lblDescripcion.Name = "lblDescripcion"; lblDescripcion.Size = new Size(328, 17); lblDescripcion.TabIndex = 1; btnVolver.Name = "btnVolver"; btnVolver.TabIndex = 2;
            barraAcciones.Location = new Point(0, 80); barraAcciones.Name = "barraAcciones"; barraAcciones.Size = new Size(1100, 52); barraAcciones.TabIndex = 1; lblEstado.Location = new Point(0, 648); lblEstado.Name = "lblEstado"; lblEstado.Size = new Size(1100, 32); lblEstado.TabIndex = 3; panelContenido.Location = new Point(0, 132); panelContenido.Name = "panelContenido"; panelContenido.Size = new Size(1100, 516); panelContenido.TabIndex = 2; layoutContenido.Location = new Point(12, 12); layoutContenido.Name = "layoutContenido"; layoutContenido.Size = new Size(1076, 492); layoutContenido.TabIndex = 0;
            panelListado.Name = "panelListado"; panelListado.TabIndex = 0; lblListado.Name = "lblListado"; lblListado.Size = new Size(131, 20); lblListado.TabIndex = 0; lblAyuda.Name = "lblAyuda"; lblAyuda.Size = new Size(153, 17); lblAyuda.TabIndex = 1; panelFiltro.Name = "panelFiltro"; panelFiltro.TabIndex = 2; lblFiltro.Name = "lblFiltro"; lblFiltro.TabIndex = 1; buscador.Name = "buscador"; buscador.TabIndex = 0; filtroEstado.Name = "filtroEstado"; filtroEstado.TabIndex = 2;
            tabla.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right; tabla.Dock = DockStyle.None; tabla.Location = new Point(16, 128); tabla.Name = "tabla"; tabla.Size = new Size(567, 346); tabla.TabIndex = 3; colId.Width = 50; colNombre.Width = 210; colDni.Width = 125; colNacimiento.Width = 125; colEstado.Width = 90;
            panelDetalle.Name = "panelDetalle"; panelDetalle.TabIndex = 1; layoutDetalle.Name = "layoutDetalle"; layoutDetalle.TabIndex = 0; lblFormulario.Name = "lblFormulario"; lblFormulario.Size = new Size(112, 21); lblFormulario.TabIndex = 0; layoutCampos.Name = "layoutCampos"; layoutCampos.Size = new Size(430, 252); layoutCampos.TabIndex = 1; panelAcciones.Name = "panelAcciones"; panelAcciones.TabIndex = 2;
            lblNombre.Anchor = AnchorStyles.Left; lblNombre.AutoSize = true; lblNombre.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblNombre.ForeColor = Color.FromArgb(51, 65, 85); lblNombre.Name = "lblNombre"; lblNombre.Text = "Nombre:"; lblApellido.Anchor = AnchorStyles.Left; lblApellido.AutoSize = true; lblApellido.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblApellido.ForeColor = Color.FromArgb(51, 65, 85); lblApellido.Name = "lblApellido"; lblApellido.Text = "Apellido:"; lblDni.Anchor = AnchorStyles.Left; lblDni.AutoSize = true; lblDni.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblDni.ForeColor = Color.FromArgb(51, 65, 85); lblDni.Name = "lblDni"; lblDni.Text = "DNI:"; lblFechaNacimiento.Anchor = AnchorStyles.Left; lblFechaNacimiento.AutoSize = true; lblFechaNacimiento.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblFechaNacimiento.ForeColor = Color.FromArgb(51, 65, 85); lblFechaNacimiento.Name = "lblFechaNacimiento"; lblFechaNacimiento.Text = "Nacimiento:"; lblPeso.Anchor = AnchorStyles.Left; lblPeso.AutoSize = true; lblPeso.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblPeso.ForeColor = Color.FromArgb(51, 65, 85); lblPeso.Name = "lblPeso"; lblPeso.Text = "Peso (kg):"; lblAltura.Anchor = AnchorStyles.Left; lblAltura.AutoSize = true; lblAltura.Font = new Font("Segoe UI Semibold", 9F, FontStyle.Bold); lblAltura.ForeColor = Color.FromArgb(51, 65, 85); lblAltura.Name = "lblAltura"; lblAltura.Text = "Altura (m):";
            nombre.BorderStyle = BorderStyle.FixedSingle; nombre.Dock = DockStyle.Fill; nombre.Name = "nombre"; apellido.BorderStyle = BorderStyle.FixedSingle; apellido.Dock = DockStyle.Fill; apellido.Name = "apellido"; dni.BorderStyle = BorderStyle.FixedSingle; dni.Dock = DockStyle.Fill; dni.Name = "dni"; fechaNacimiento.Name = "fechaNacimiento"; peso.BorderStyle = BorderStyle.FixedSingle; peso.Dock = DockStyle.Fill; peso.Name = "peso"; altura.BorderStyle = BorderStyle.FixedSingle; altura.Dock = DockStyle.Fill; altura.Name = "altura";
            nuevo.BackColor = Color.FromArgb(79, 70, 229); nuevo.FlatAppearance.BorderSize = 0; nuevo.FlatStyle = FlatStyle.Flat; nuevo.ForeColor = Color.White; nuevo.Location = new Point(0, 4); nuevo.Name = "nuevo"; nuevo.Size = new Size(98, 32); nuevo.Text = "+ Nuevo socio"; nuevo.UseVisualStyleBackColor = false; guardar.BackColor = Color.FromArgb(79, 70, 229); guardar.FlatAppearance.BorderSize = 0; guardar.FlatStyle = FlatStyle.Flat; guardar.ForeColor = Color.White; guardar.Location = new Point(0, 48); guardar.Name = "guardar"; guardar.Size = new Size(98, 32); guardar.Text = "Guardar"; guardar.UseVisualStyleBackColor = false; actualizar.BackColor = Color.FromArgb(226, 232, 240); actualizar.FlatAppearance.BorderSize = 0; actualizar.FlatStyle = FlatStyle.Flat; actualizar.ForeColor = Color.FromArgb(30, 41, 59); actualizar.Location = new Point(104, 48); actualizar.Name = "actualizar"; actualizar.Size = new Size(98, 32); actualizar.Text = "Actualizar"; actualizar.UseVisualStyleBackColor = false; darDeBaja.BackColor = Color.FromArgb(254, 242, 242); darDeBaja.FlatAppearance.BorderSize = 0; darDeBaja.FlatStyle = FlatStyle.Flat; darDeBaja.ForeColor = Color.FromArgb(185, 28, 28); darDeBaja.Location = new Point(0, 88); darDeBaja.Name = "darDeBaja"; darDeBaja.Size = new Size(98, 32); darDeBaja.Text = "Dar de baja"; darDeBaja.UseVisualStyleBackColor = false; reactivar.BackColor = Color.FromArgb(226, 232, 240); reactivar.FlatAppearance.BorderSize = 0; reactivar.FlatStyle = FlatStyle.Flat; reactivar.ForeColor = Color.FromArgb(30, 41, 59); reactivar.Location = new Point(104, 88); reactivar.Name = "reactivar"; reactivar.Size = new Size(98, 32); reactivar.Text = "Reactivar"; reactivar.UseVisualStyleBackColor = false; calcularImc.BackColor = Color.FromArgb(226, 232, 240); calcularImc.FlatAppearance.BorderSize = 0; calcularImc.FlatStyle = FlatStyle.Flat; calcularImc.ForeColor = Color.FromArgb(30, 41, 59); calcularImc.Location = new Point(208, 88); calcularImc.Name = "calcularImc"; calcularImc.Size = new Size(98, 32); calcularImc.Text = "Calcular IMC"; calcularImc.UseVisualStyleBackColor = false;
            Controls.Add(panelContenido);
            Controls.Add(lblEstado);
            Controls.Add(barraAcciones);
            Controls.Add(panelEncabezado);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.FromArgb(241, 245, 249);
            ClientSize = new Size(1100, 680);
            Font = new Font("Segoe UI", 9.5F);
            MinimumSize = new Size(760, 540);
            Name = "GestionSociosForm";
            StartPosition = FormStartPosition.CenterParent;
            Text = "SysGym | Socios";
            nuevo.Click += NuevoSocio;
            guardar.Click += GuardarNuevo;
            actualizar.Click += Actualizar;
            darDeBaja.Click += DarDeBaja;
            reactivar.Click += Reactivar;
            calcularImc.Click += CalcularImc;
            panelEncabezado.ResumeLayout(false); panelEncabezado.PerformLayout();
            panelContenido.ResumeLayout(false); layoutContenido.ResumeLayout(false); panelListado.ResumeLayout(false); panelListado.PerformLayout();
            panelFiltro.ResumeLayout(false); panelFiltro.PerformLayout(); ((ISupportInitialize)(tabla)).EndInit();
            panelDetalle.ResumeLayout(false); layoutDetalle.ResumeLayout(false); layoutDetalle.PerformLayout(); layoutCampos.ResumeLayout(false); layoutCampos.PerformLayout();
            panelAcciones.ResumeLayout(false); ResumeLayout(false);
        }

    }
}
